### ISSUE TITLE
Question: How to approach adding minification to handlebars plugin?

### ISSUE THREAD

**Issue by MeoMix** [systemjs/systemjs#1001]
Heya,

I was looking into this a bit and posted on the Gitter channel, but thought it would be prudent to post a full-fledged question here.

I'm hoping to add two features to the Handlebars plugin. I suspect one of them will be 'free' once I know how to do the other:

- Add support for minification of templates using https://github.com/kangax/html-minifier
- Add support for relative URL paths within templates.

Here's what the Handlebars plugin currently looks like:

```
'use strict';

import Handlebars from 'handlebars';

const handlebarsRuntimePath = System.normalizeSync('handlebars/handlebars.runtime', __moduleName);

export function translate(load) {
  var precompiled = Handlebars.precompile(load.source);
  load.source = `module.exports = require('${handlebarsRuntimePath}').template(${precompiled});`;
}
```

My initial confusion arises from the use of `translate`. I've only worked with `css` and `jspm-loader-css` plugins thus far. Both of these plugins make use of `fetch` and `bundle` rather than `translate`. After reading the (sparse) [documentation](https://github.com/systemjs/systemjs/blob/master/docs/creating-plugins.md) I'm only slightly less confused. The docs don't mention bundle at all. They imply you need to use `translate` to inline into bundles, but that's what `bundle` does, right? So, I'm a bit lost there.

Regardless, that's not the real issue.

So, the above code takes source, precompiles it, and overwrites source with a Handlebars template function using the precompiled html. It needs to do this before `bundle` because the template function will be used in development.

When the `bundle` hook is ran... it's difficult and hacky to extract the precompiled HTML. I was thinking I could create a Map which maps some unique identifier (load.source...? module name?) to the precompiled HTML. Then, in `bundle`, I could minify the pre-compiled HTML and swap out the existing precompiled html in `load.source`... but that might have bugs in it and feels really ass-backwards.

How should I be approaching this? Should this be broken up into fetch/bundle? Thanks!

CC @davis

**Comment by guybedford** [comment]
Hey, I'm glad to hear you're motivated and making progress on this!

What is the reason you need the bundle hook at all here? Can you not just include your minification and paths remappings within the translate layer?

The bundle hook is designed to cater to minification that needs to do reductions across multiple loads. Consider for example CSS where two separate files may have the same CSS property so we know we can reduce it. But I'd suggest only using the bundle hook if you really have to, and sticking to translate if you can.

Since handlebars compiles templates to functions (which is correct), I'm not sure where in that process you would fit in the HTML-based minfication and URL handling. You may find this is a limitation of Handlebars itself, although there will likely be some good ideas around these problems already within the Ember community to work with.

**Comment by guybedford** [comment]
Let me know if you have any further questions here at all.

**Comment by MeoMix** [comment]
I will! Going to take a look at this today.
