### ISSUE TITLE
Still breaking change in 0.19.12

### ISSUE THREAD

**Issue by stefanocke** [systemjs/systemjs#1015]
Hi again,

this bug is very similar to #1008, but this time the scenario is a bit more complex:

- index.html loads component1
- component1 loads component2 using SystemJS
- Both, component1 and component2 depend on foobar/core

- with 0.19.9 both components are loaded succesfully. With 0.19.12, component2 fails, since it tries to load foobar/core from app/foobar/core.js

Plunkr: https://plnkr.co/edit/bRNHHfGvzp2Q6wMNqiTT?p=preview

Again, foobar/core could be smothing like angular2 and component1 and 2 are angular components where one component dynamically loads the other...

**Comment by guybedford** [comment]
If you have a path rule like `'*': `app/*``, then `foobar/core` normalizes into `app/foobar/core` and should be available at that location.

That is, either don't use a `*` path, or define foobar/core as `app/foobar/core`.

If anything I think the bug is that `foobar/core` is loadable at all here by the component, rather than it isn't by the other. There will be some tightening up of the normalization in the next deprecation release along these lines.

**Comment by guybedford** [comment]
Actually sorry it isn't that. This is entirely around the `defaultJSExtensions` so is a regression.

**Comment by stefanocke** [comment]
Okay, thanks. So you say the '*': 'app/*' was kind of accidentally working for foobar/core in my case? Does this mean you will remove the fix for #1008 again?

**Comment by guybedford** [comment]
Thanks so much for the detailed checking, I believe I've captured all these now.

**Comment by guybedford** [comment]
Released in 0.19.13.
