### ISSUE TITLE
system-polyfills.js is applied even if Promise is already polyfilled

### ISSUE THREAD

**Issue by mpfau** [systemjs/systemjs#1023]
If Promise has already been polyfilled (e.g. with bluebird), the polyfill is overridden with systemjs `system-polyfills.js` if `URL` is not available. This problem occurs in older browsers (e.g. Android WebView / or Chrome 19) where bluebird is loaded before systemjs.

See system.src.js: 
```
if (typeof Promise === 'undefined' || !hasURL) {
  // document.write
  if (typeof document !== 'undefined') {
    var scripts = document.getElementsByTagName('script');
    $__curScript = scripts[scripts.length - 1];
    var curPath = $__curScript.src;
    var basePath = curPath.substr(0, curPath.lastIndexOf('/') + 1);
    window.systemJSBootstrap = bootstrap;
    document.write(
      '<' + 'script type="text/javascript" src="' + basePath + 'system-polyfills.js">' + '<' + '/script>'
    );
  }
```

**Comment by guybedford** [comment]
In older browsers, the native Promise implementation is generally slower than when.js so the fact that loading the polyfills file also polyfills Promises is not actually a problem I don't think.

Rather your issue is specifically that you're wanting to use Bluebird for promises rather than when and so you shouldn't even be loading when.js in your app at all.

The way to do this would be to either create a custom polyfills build, or simply ensure that the URL polyfill is included in the page.

The URL polyfill used by SystemJS is exactly this file - https://github.com/ModuleLoader/es6-module-loader/blob/master/src/url-polyfill.js.

**Comment by mpfau** [comment]
OK, thanks. Just switched to pre-loading of the URL polyfill and bluebird.
