### ISSUE TITLE
Ignoring "deps ../css/bootstrap.css!"

### ISSUE THREAD

**Issue by sberney** [systemjs/systemjs#1028]
So far I've been unable to find a way to tell SystemJS not to load bootstrap's built in css, which I am distributing manually before SystemJS loads. jspm adds `"deps ../css/bootstrap.css!"` as metadata at the top of `bootstrap.js`. Normally that's great, but I don't want it to be sent at all. While there's some help out there about configuration to exclude entire *dependencies*, how about excluding just a css file or two? I'm in development mode, not packaging files with the builder.

```javascript
{
  meta: {
    'bootstrap': {
      'format': 'global',
      'deps': ['jquery']  // doesn't override deps in the file
    }
}
```

**Comment by guybedford** [comment]
This can be altered with the use of an override:

```
  jspm install bootstrap -o "{shim:{}}"
```

By setting the `shim` to an empty object, it will null out the shim provided at https://github.com/jspm/registry/blob/master/package-overrides/github/twbs/bootstrap%403.1.0.json.

Which version of Bootstrap are you using though? Because the latest 3.x and 4.x don't do CSS shimming.

**Comment by sberney** [comment]
I'm using Bootstrap 3.1.1 from github. Is there no way to do this after the initial jspm installation?

**Comment by guybedford** [comment]
@sberney overrides can be put directly in the package.json too, but always apply when running `jspm install`.

**Comment by sberney** [comment]
Thanks! That would explain some of my confusion about manually adding overrides, I'm guessing sometimes I ran jspm install and other times I didn't :)
