### ISSUE TITLE
Lazy loading SystemJS

### ISSUE THREAD

**Issue by laurentgoudet** [systemjs/systemjs#1051]
When using `System.import` statements to load SystemJS modules, ideally they should be included high on the page for the browser to execute them and start fetching the modules/bundles, while parsing the rest of the page. This is especially true if the page weight more (gzipped) than 14kb, due to the nature of TCP slow start and the (modern) initial value of the congestion window (IW10).

However, currently `system.js` has to be loaded as a synchronous script, preventing the rest of the page to be parsed and executed while the script is fetched. The "best practice" with render-blocking script is to include them before the closing `</body>` tag, which conflicts with the need of having the modules fetched as soon as possible.

Defining an async callback on the `window` object would allow SystemJS to be loaded in a non render-blocking, similar to most JavaScript SDKs nowadays. It does mean that all the API calls have then to be enclosed in that callback `System.import`, `System.config`, especially since most browsers don't have native Promise support.

**Comment by guybedford** [comment]
The alternative to a `window`-level callback might be to just to set a `System.config({ main: 'x.js' })`. Then the SystemJS and config scripts can be set to `defer`.

**Comment by guybedford** [comment]
Hmm...

```javascript
System.config({
  main: 'app'
});
```

or

```javascript
System.config({
  entryPoint: 'app'
});
```

?

**Comment by probins** [comment]
as I see it, `System.import` is intended for dynamic loading, so wouldn't be executed in the initial page load anyway. Much of the weight in SystemJS at the moment is loading the loader, which won't be necessary once that's implemented in browsers.

**Comment by guybedford** [comment]
@probins the voice of sanity as always. Ok I will resist this implementation again. It is crossing boundaries, effectively allowing System.config to be a sort of proxy to System.import. They are different functions, call them one by one. config is also designed to work across all pages of an app, so attaching that to a per-page import is a bad idea. System.import isn't that much typing...

In short, script defer will work with SystemJS today catering for the original use case fine. So closing again for now.

**Comment by truongsinh** [comment]
@guybedford 
> as I see it, System.import is intended for dynamic loading, so wouldn't be executed in the initial page load anyway.

I beg the difference. Most of modern webapp is single-page-app, and needless to say, dynamic loading is the one of the very first JS to be executed.

> Much of the weight in SystemJS at the moment is loading the loader, which won't be necessary once that's implemented in browsers.

I don't clearly understand this point.

Anyway, we face the exactly same problem as @laurentgoudet, and are happy to make pull request

**Comment by truongsinh** [comment]
Here's the proof of concept
```
<script>
window.System = (function (d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0], s = window.System || {};
  if (d.getElementById(id)) return s;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.24/system-csp-production.js";
  fjs.parentNode.insertBefore(js, fjs);
  if (s.then) return s;
  s.then = function (f) {
    s.then.l.push(f);
  };
  s.then.l = [];
  return s;
}(document, "script", "systemjs"));

System.then(function(System){
// set our baseURL reference path
  System.config({
    baseURL: '/app'
  });

// loads /app/main.js
  System.import('main.js');
});

</script>
```

**Comment by probins** [comment]
> Most of modern webapp is single-page-app, and needless to say, dynamic loading is the one of the very first JS to be executed.

dynamic loading is for loading extra code after the initial load. Your initial load ('home page' equivalent in SPA) would be from html, something like:
```
<script type="module">
  import './homepage.js';
<\script>
```
You can't really do that atm with the polyfill, which is why you have to load SystemJS (which in turn loads the polyfill) upfront. But that need will go away once `<script type="module">` is implemented in browsers (which will probably start happening later this year some time).

You use `System.import` to load code dynamically when the user wants to move on to another 'page'. If you're bundling all your code into a build (which I wouldn't advise for SPA), you don't need `System.import` at all.

The polyfill is just trying to emulate how the loader will work once implemented. It's not 100%, but I don't think it's worth spending time adding stuff which won't be needed in the long term. SystemJS is just a bunch of small add-ons, with the polyfill included in the download as a convenience. Once the loader is implemented, I expect it can just be a series of small modules that can be imported in 'homepage.js' as needed.
