### ISSUE TITLE
Is it possible to use plugins chain

### ISSUE THREAD

**Issue by pavel06081991** [systemjs/systemjs#1053]
For example I want to use SASS plugin(https://github.com/mobilexag/plugin-sass) and TEXT plugin(https://github.com/systemjs/plugin-text) together. In webpack I can use loaders chain, for example:
```javascript
import myModuleCss from '!raw!sass!./my-module.sass';
```
Is it possible to do this with systemjs?

**Comment by guybedford** [comment]
No, SystemJS doesn't support plugin chaining. The suggested approach is to create a new plugin using class extension. The motivation behind this is that plugin communication should be high-bandwidth, so that a compound plugin is preferable. Multiple loaders in webpack cal also often end up reparsing the syntax tree, while the approach trying to be advised here is to say just use a Babel or PostCSS loader, which then can have a plugin pipeline itself providing the same features as chaining but at the level of the plugin itself.
