### ISSUE TITLE
silly filepaths in evaluation output

### ISSUE THREAD

**Issue by HansHammel** [systemjs/systemjs#1072]
I get silly paths in Evaluation Output like 

	Evaluating file:///C:/project/client/jspm_packages/github/jspm/nodelibs-fs@0.1.2.js

There is no such file! It's a directory, that - for whatever reason - got ".js" appended!? The index file resides at "file:///C:/project/client/jspm_packages/github/jspm/nodelibs-fs@0.1.2/index.js". For the whole output see https://github.com/systemjs/plugin-css/issues/75.
btw, why don't you output a stack trace/ call stack in the usual format, including functions and line-numbers!?

**Comment by guybedford** [comment]
@HansHammel that file should definitely exist. Can you share the install you ran to replicate it?

Because execution is interleaved eval statements, SystemJS creates its own execution stack list to avoid unnecessary SystemJS code showing in the stack and to ensure that it displays correctly. Contributions for a better stack trace are always welcome.
