### ISSUE TITLE
Getting 404 on jspm_packages/npm/rxjs@5.0.0-beta.2/observable/.js

### ISSUE THREAD

**Issue by tianyangj** [systemjs/systemjs#1122]
Here is the repo, https://github.com/tianyangj/Angular2-JumpStart/tree/jspm.

Here is my package.json,

"jspm": {
    "dependencies": {
      "angular2": "npm:angular2@^2.0.0-beta.7"
    },
    "devDependencies": {}
  }

my index.html,

<script src="../jspm_packages/system.js"></script>
    <script src="../config.js"></script>
    <script>
        System.import('src/app/main.js');
    </script>

In the network tab, I got the following, all other dependencies loads fine.
Live reload enabled.
system.src.js:4868 GET http://127.0.0.1:8080/jspm_packages/npm/rxjs@5.0.0-beta.2/observable/.js 404 (Not Found)J @ system.src.js:4868(anonymous function) @ system.src.js:4868(anonymous function) @ system.src.js:4868(anonymous function) @ system.src.js:4868(anonymous function) @ system.src.js:4868(anonymous function) @ system.src.js:4868(anonymous function) @ system.src.js:4868(anonymous function) @ system.src.js:4868(anonymous function) @ system.src.js:4868(anonymous function) @ system.src.js:4868
system.src.js:4868 Uncaught (in promise) Error: XHR error (404 Not Found) loading http://127.0.0.1:8080/jspm_packages/npm/rxjs@5.0.0-beta.2/observable/.js(…)

Anyone can help?

**Comment by tianyangj** [comment]
It works on Mac, closing.

**Comment by guybedford** [comment]
If it's a Windows bug it's still a bug! If I try out the test case will it be possible to reproduce on windows?

**Comment by EdarLazar** [comment]
I'm having the same issue in Windows.

https://github.com/ReactiveX/RxJS/blob/master/src/observable/PromiseObservable.ts

Has this import:

```javascript
import {Observable} from '../Observable';
```
Which in Windows is transpiled as:
```javascript
var Observable_1 = require('.js');
```
Thus failing. In OS X -in the other hand- is correctly transpiled as:
```javascript
var Observable_1 = require('../Observable');
```

I don't know if transpiled is the right verb to use here, I'm just starting with all these :)

**Comment by guybedford** [comment]
If this is being removed by the transpiler itself in the transpilation layer then that would be related to TypeScript rather than SystemJS.

**Comment by dougludlow** [comment]
This issue has been mentioned a couple times in the comments of a recent blog post I wrote (https://royaljay.com/development/angular2-tutorial/) and I wanted to clear some things up.

@EdarLazar you had this note in your config.js:
```
/*
=== RxJs  Fix for Windows ===
Go to:
jspm_packages/npm/rxjs@5.0.0-beta.2/observable/PromiseObservable.js
And change:
var Observable_1 = require('.js');
To:
var Observable_1 = require('../Observable');
*/
```

The `PromiseObservable.js` is an asset that is generated prior to publishing and is included in the npm package and therefore will be the same on any platform.

I'm not sure how it changed in this circumstance. Perhaps tsconfig's `exclude` property was not being honored in your particular version of typescript and it was therefore being recompiled? A hiccup in a release of rxjs?

Regardless, I have downloaded and extracted the published npm package (http://registry.npmjs.org/rxjs/-/rxjs-5.0.0-beta.2.tgz) and noted that line 8 of `PromiseObservable.js` is as expected:

```
var Observable_1 = require('../Observable');
```

**Comment by EdarLazar** [comment]
Thank you for the followup.

@dougludlow I can reproduce the issue in Windows anytime. 

I don't know when the compilation of the original typescript file happens. I though it came in the package already and you're showing that, but then I can't explain why I get a different version. Maybe Visual Studio is taking to itself to recompile the library? (since I'm using jspm I did turn off VS typescript compilation to let jspm do the work).

I just did to confirm Visual Studio is not touching the files:

1. cloned the repo to a new folder
2. ran npm install and jspm install from wwwroot
3. ran dnx web from the root folder of the project

All command line, no tools. In Windows the file is "bugged".

Replaying the same process in OS X works, the file is correct.

**Comment by EdarLazar** [comment]
I used to have several versions of TypeScript installed. Several -different- versions of TypeScript Visual Studio Tools (1.5.3, 1.7.9 and 1.8.6 I believe). I have also the latest version of TypeScript installed as a global npm module. My path points to this version.

Since then I removed all Visual Studio versions to leave just the latest version and make sure any way a TypeScript compiler is called by Visual Studio or otherwise it is the same version (and the latest). I aso have the external web tools paths of VS pointed to my global npm modules folder.

This setup from which I ran the test above. I will keep looking for the solution.

**Comment by dougludlow** [comment]
Interesting... I wonder what is different in our environments. I cloned your repo and followed your steps exactly and it worked fine for me ("Hello from Angular2!"). Checked the `PromiseObservable.js` and it was what it was supposed to be.

```
tsc -v
message TS6029: Version 1.7.5
```

I wonder if it's a somehow a corrupt release of rxjs's npm package and it's cached?

Curious what shows up for you in `%APPDATA%\npm-cache\rxjs`. The following should clean it out:

```
npm cache clean
```

I'm not sure if jspm uses a separate cache or not. Perhaps @guybedford could shed some light on that?

**Comment by dougludlow** [comment]
Ah, looking at the jspm-cli code, it looks like it is cached here on windows: `%LOCALAPPDATA%\.jspm\packages\npm\rxjs@5.0.0-beta.2` and there's an undocumented (it's not in the docs, but it is in the command help) comment to clear it: `jspm cache-clear`.

**Comment by dougludlow** [comment]
@EdarLazar I'm curious, is `%LOCALAPPDATA%\.jspm\packages\npm\rxjs@5.0.0-beta.2\observable\PromiseObservable.js` messed up for you?

**Comment by EdarLazar** [comment]
@dougludlow That was it! Thank you. Cleared both caches and tried again, now everything works fine.

Didn't knew about the cache, it's an important thing to know when you're dealing with beta software. I will add the clear commands to my workflow. Because I had this problem with rxjs@5.0.0-beta.0 and rxjs@5.0.0-beta.2 I disregarded cache issues but the cache of course is file based :P

Problem solved. RXJS had a botched release and now it's fixed.

**Comment by dougludlow** [comment]
:thumbsup:

**Comment by patelmaulik** [comment]
![image](https://cloud.githubusercontent.com/assets/5690877/14170031/330b259a-f723-11e5-91f9-587982d2caa4.png)

Sorry for the delayed response, I have done what you suggested.
Still getting those errors..
