### ISSUE TITLE
Support for GopherJS

### ISSUE THREAD

**Issue by JacoSmit** [systemjs/systemjs#1136]
Hi,

Does Systemjs support GopherJS? I would like to use a library written Go that is then compiled to JavaScript via GopherJS but before I go through all the hassle of doing this, does SystemJs support this?

PS. Sorry for the stupid question, new to this.

Kind regards
Jaco Smit

**Comment by guybedford** [comment]
I don't know of any existing Gopher plugins and haven't used it myself, but if the output of Gopher is a global or standard JS module then SystemJS will load that fine. Perhaps just do a full build and load the output file? The next thing to think about is how to make single file compilation to a module format work, which may require a custom plugin, but otherwise just stick with the first approach.

**Comment by guybedford** [comment]
Just let me know if I can help further here.

**Comment by JacoSmit** [comment]
Will do thanks. I am currently using a workaround than what I wanted to do.

**Comment by edrex** [comment]
I think you can export as CommonJS like `'js.Module.Get("exports").Set("exportName", ...)`, see
 https://godoc.org/github.com/gopherjs/gopherjs/js#Module. It doesn't seem like any additional support from SystemJS is needed. I think a lot of GopherJS builds will be integrated with a Go project and use Go tooling.
