### ISSUE TITLE
"Require is not defined", weird deps issue

### ISSUE THREAD

**Issue by onwsk8r** [systemjs/systemjs#1144]
So I was using someone's hacked together Browsersync script (which worked), and I decided to fix it from:
```js
server {
    baseDir: './',
    index: 'build/index.html'
},
rewriteRules: [{
    match: '/\/app\/(.+)',
    replace: '/build/app/$1'
}]
```
To:
```js
server: {
    baseDir: './build',
    index: 'index.html',
    routes: { "/node_modules": "node_modules" }
}
```

The browser was aware of the rewrites in the first snippet - `/app/boot.js` gave me a 404 while `/build/app/boot.js` loaded properly. This is an ng2 app, and working with beta software is difficult enough.

The second variety works fine, however after loading the systemJS file and the first JS file with System.import (which, keep in mind, had worked fine 30 seconds prior), it said "function require is not defined". It loaded the exact same files in the exact same order both times - the only changes were to the BS configs.
When I changed my tsconfig for the source and System.config({}) for the JS I was serving to be "amd" instead of "register", everything worked fine.

I experienced this same issue in a different environment several months ago (require is not defined) and fixed it the same way (s/register/amd/) then, although the cause had nothing to do with Browsersync - if I can remember what caused it, I'll post that.

**Comment by guybedford** [comment]
It's only really possible to make suggestions here based on context. It sounds like this is just about ensuring modules are treated with the right format interpretation in SystemJS? ES modules transpiled to System.register won't have a `require` defined certainly because that isn't part of the module system. So it would depend on what was doing a `require` and why.

**Comment by onwsk8r** [comment]
The plot thickens!

The .js files that tsc spit out were identical before and after I changed the Browsersync config (obviously) - they just had different url's because of that ghastly rewrite. 

I was looking here - https://github.com/systemjs/systemjs/blob/master/docs/system-api.md
and wondering if it was finding `require` via `window.require` (ergo not erroring), but couldn't figure out why that would have changed.

Basically I had a file that used SystemJS parlance with four require()'s inside the IIFE to other files, which then loaded more files (Angular2 is _heavily_ componentized :). I was working on a clean version of the repo (git status = no changes), I changed the BS config, and it died. I git stash'd, it worked again. git stash apply'd, it broke. Git diff? Sure enough - just a few lines of BS configs in a Gulpfile. I did this a number of times because I couldn't believe what I was seeing. The LOC I pasted earlier were the _only_ changes from working to breaking.
Then, the 1 LOC change to tsconfig.json and 1 LOC change to system.config fixed everything.

One other thing worth noting with those BS rewrites - they must have come across in the BS JS file and happened in the browser; when I typed in a path that should have been rewritten directly (ie /app/file.js), it did not get rewritten to /build/app/file.js; I got a 404.

So basically what I'm getting at is that I had identical files before and after the BS breaking change. One set of URLs were getting rewritten by the browser, one set was not. I'm trying to find the correlation between that and `require` is not defined.

Or, at the very least, have a handy solution for anyone else that encounters this issue - Googs was not helpful for me.

**Comment by guybedford** [comment]
It's really important on issue queues like this to be succinct. I hope you can understand that as a maintainer there is limited time to understand your issue.

Right now all I can gather is that something happened in your workflow which was unexpected, you have a main type of file that uses the CJS require to load other things, and then you got the error after the unexpected change.

The only thing I can suggest from that is that if your main file expects to be able to use `require` then it needs to be treated as CommonJS by SystemJS. If you're using meta or other ways of setting for the format, then that may be interfering with this.

Try

```javascript
System.config({
  meta: {
    'path/to/main/with/require.js': { format: 'cjs' }
  }
});
```

Please try to get to a point where you can clearly state what your inputs and outputs are in future. I may not be able to continue to help you here otherwise.

**Comment by onwsk8r** [comment]
My JS files are Typescript. I have the Typescript compiler set to
```json
"compilerOptions": {
    "module": "system",
    ...
```

My system.config, which is JS, has
```js
packages: {
    app: {
        format: 'register',
        defaultExtension: 'js'
    }
}
```

When I changed my BS config, as I mentioned in the OP, it broke until I changed over to AMD. Why?

**Comment by guybedford** [comment]
You mentioned you had a file that contained four `require()` statements. My best guess is it sounds like these were giving the require is undefined issue from the information you've given me, although it could be any require in your app without seeing the full stack trace.

A `require` statement is not defined to work inside ES modules, globals or System.register in SystemJS, as that is something specifically for the CommonJS module format.

This issue queue isn't really for long support threads, so I'm closing this, but feel free to continue to ask any questions you might have and I will answer where I can.

**Comment by onwsk8r** [comment]
Thanks for your help.
