### ISSUE TITLE
ES6 class usage issue: self = this

### ISSUE THREAD

**Issue by alexkolt** [systemjs/systemjs#1154]
Honestly, I'm not sure of what is the cause for the behavior: systemjs, babel or my own fault. I'm using class for custom control controller and saving class reference in self variable. Apparently that gets overriden by any subsequent controller instances.

I created a simple repository to demonstrate:
clone, install, run live-server or your preferred server. You will see 2 buttons, each is a custom control. Clicking on a button only affects one control.

https://github.com/alexkolt/selfIsThis

How can I get this working with ES6 class?

**Comment by amenadiel** [comment]
You're declaring `self` outside the scope of the class constructor. That's why every time you instance the controller you overwrite it, affecting every existing instance.

If you really needed to preserve the value of `this` (unlike the provided example), you could declare `var self = this;` inside the method that needs it. Not in the outer scope nor in the constructor.

**Comment by alexkolt** [comment]
Yep, that'd be my problem. I thought babel wraps every file in anonymous block and self would only be scoped to that.

Please close the issue.
