### ISSUE TITLE
import problem without .js extension

### ISSUE THREAD

**Issue by Alphapage** [systemjs/systemjs#1169]
Hello,

I'm using es6 and systemjs throws an error when I don't add the .js extension in import like this:
```js
import * from './Test';
```
But I don't get any error with this code:
```js
import * from './Test.js';
```

Both code are valid es6.

This doesn't work for ```System.import('./Test')``` too.

Do I need a plugin ? I think it should be built in.

Thank you in advance for your help.

**Comment by guybedford** [comment]
Default extensions can be defined for packages - https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages. The point is to encapsulate this behaviour as assuming extensions is itself a non-standard operation. Otherwise including the extensions is actually also recommended in many cases, even in Node these days.
