### ISSUE TITLE
how to import module that in bundle?

### ISSUE THREAD

**Issue by khomyakov42** [systemjs/systemjs#1174]
I have bundle index.js containing named modules
```

System.register('app/bootstrap', ['./router'], function() {
   return {
    setters: [...],
    execute: function() {...}
});
System.register('app/router', function() {
   return {
    setters: [...],
    execute: function() {...}
})

```

I try to import the app/bootstrap module in index.html

```
<html lang="en">
<head>
   ...
   <script src="/index.js"></script>
</head>
<body>
  System.config({
        baseURL: "/",
        defaultJSExtensions: 'js',
        transpiler: false,
        packages: {
            'app': {
                format: 'register',
                defaultExtension: 'js'
            }
        }
    });
    System.import('app/bootstrap').then(null, console.error.bind(console));
</body>
</html>
```

I see that the module is in the variable System.defined but systemjs makes a request for the URL /app/bootstrap.js. Maybe a bug in SystemJs?

**Comment by asapach** [comment]
Try including your script after `System.config()` but before `System.import()`

**Comment by khomyakov42** [comment]
I gave the wrong information. SystemJs makes a request to the app/bootstrap and can not find it

**Comment by jpeters5392** [comment]
@khomyakov42 I think it has to do with your use of `defaultExtensions` and the order of your config/bundle in your page.  Your modules are getting registered without extensions prior to configuring SystemJS with a defaultExtension of `js`, so the value of your `System.defined` property should include keys *without* extensions.  When you call `System.import` it is after your configuration block so System will normalize the imported module name to have a `.js` extension which does not match your registry.  You can either fix this by moving your System configuration prior to loading your bundle which will result in your registered modules to have the extension added, changing your bundle to include the extensions in the names of the modules, or modify your System configuration to turn off defaultExtensions so that System does not normalize your import request to include the `.js` extension.

**Comment by kresli** [comment]
Could you paste here the error from the log?

**Comment by guybedford** [comment]
The suggestions here are exactly right. @khomyakov42 did you make any progress?

**Comment by khomyakov42** [comment]
at the moment I'm having other problems, I'll let you know how the information will be

**Comment by fantaclaus** [comment]
I've found two solutions for that:

1. Remove `defaultExtension: 'js'` but keep `defaultJSExtensions: 'js'` in the config.

1. In both calls to `System.register` add `.js` extension to the module name (first argument).
