### ISSUE TITLE
Loading broken JS fails without stack trace with defer

### ISSUE THREAD

**Issue by alexisvincent** [systemjs/systemjs#1181]
When loading a js file with some error. Stack trace is not shown in the case where defer's were used to load SystemJS. This could just be because I don't properly understand how defers work. But really seems like it should.

There's a repo to replicate here: https://github.com/alexisvincent/system-ja-stack-trace-error

**Comment by guybedford** [comment]
Yes, promises need a catch handler to get the error depending on the js environment. I'd suggest going through a promises tutorial here if you can.

**Comment by alexisvincent** [comment]
Oh right. Thanks

**Comment by laurentgoudet** [comment]
Stumbled on the same issue: when the SystemJS `script` tag has the `defer` attribute on it, which allows to offload the CPU during the initial page rendering - cutting down the TTMC - and fix a Google PageSpeed Insight warning, synchronous errors have missing stack traces:

<img width="1280" alt="screen shot 2016-07-19 at 2 17 22 pm" src="https://cloud.githubusercontent.com/assets/2169585/16949521/8c2556b6-4dbb-11e6-80af-e09cab59e24d.png">

The reason is that, in `addToError`, SystemJS matches `$__curScript.src` to determine what gets filtered from the stack trace or not:

```
 function addToError(err, msg) {
    // parse the stack removing loader code lines for simplification
    if (!err.originalErr) {
      var stack = (err.stack || err.message || err).toString().split('\n');
      var newStack = [];
      for (var i = 0; i < stack.length; i++) {
        if (typeof $__curScript == 'undefined' || stack[i].indexOf($__curScript.src) == -1)
          newStack.push(stack[i]);
      }
    }
```

With `$__curScript` being set through:

```
var scripts = document.getElementsByTagName('script');
$__curScript = scripts[scripts.length - 1];
```

However, when `defer` is used, `scripts[scripts.length - 1]` isn't the SystemJS `script` tag but the last `script` tag of the document. In my case, it is an inline `script` with an empty string (`""`) `src` attribute, causing `addToError` to remove everything from the stack trace:

![screen shot 2016-07-19 at 1 53 01 pm](https://cloud.githubusercontent.com/assets/2169585/16949711/8b52b3c2-4dbc-11e6-97c9-7508d0918939.png)

Enabling `loaderErrorStack` works around the issue but the stack trace isn't filtered anymore:

```
      System.config({
        loaderErrorStack: true
      });
```

<img width="1280" alt="screen shot 2016-07-19 at 2 29 08 pm" src="https://cloud.githubusercontent.com/assets/2169585/16949834/2e5bf54c-4dbd-11e6-9aed-b4a3644520fa.png">

**Comment by guybedford** [comment]
@laurentgoudet thanks does https://github.com/systemjs/systemjs/commit/adb5fdad65903992c9cccef6f0d16acd8f03b940 work for you here then?
