### ISSUE TITLE
require() calls fail

### ISSUE THREAD

**Issue by johnjbarton** [systemjs/systemjs#1194]
Hi Guy

In https://github.com/systemjs/systemjs/blob/master/lib/global-eval.js#L23 we read:
```js
return (wrap ? '(function(System, SystemJS, require) {' : '') + load.source + (wrap ? '\n})(System, System);' : '')
```
The parameter `require` has no call value.  So `require()` in the enclosed module fails.  Is this intended? Maybe I'm not set up correctly?

**Comment by johnjbarton** [comment]
FWIW I added `(System, System)` -> `(System, System, require)` and I'm fixed ;-)

**Comment by guybedford** [comment]
@johnjbarton glad to see you trying it out here! Due to the nature of linking in SystemJS we treat all modules as only of one format type. So the `require` is set to be undefined here exactly.

The reason for this is that SystemJS does a single pass linking process, not a two-pass linking which would be required for supporting `require` inside of ES modules.

If you're looking to load NodeJS core modules, that can be done via `import '@node/fs'` for example. Other node requires are not supported by default though, although the node require is available at `System._nodeRequire` for alternative (non-encouraged!) workflows.

The reason being that we're trying to build an ecosystem that isn't dependent on NodeJS assumptions.

**Comment by johnjbarton** [comment]
Thanks!  What do I do to load pre-existing but non-core nodejs modules?

**Comment by johnjbarton** [comment]
Well I seem to be blocked.

You know my commitment to es modules. But they have to win on value. We can't win on "it's standard". We can win on "I'm using import everywhere, I write my node module with import but I use older npm modules via `require()`.

However, I can't use systemjs to write my node code with import because it actively poisons require().   By that I mean, a solution where `require()` only works for `node_modules` is a good compromise: I'd use import for all of my (relative) modules and `require()` for npm.  I can't do that because even the global require is poisoned in systemjs by the wrapper. That leaves the only viable solution as `require()` for both my relative modules and npm modules. 

Am I missing something?

**Comment by guybedford** [comment]
@johnjbarton we don't poison the global require but we do scope it to create a unified module system.

You can load CommonJS modules with SystemJS but the issues become all the complex edge cases where NodeJS resolution doesn't match SystemJS resolution.

Using custom SystemJS map and package configuration though, all of these edge cases can be individually tackled.

Perhaps let me know what package you are trying to load here, and I can explain what configuration is necessary?

Also this is where jspm comes in as well, as it handles automatically generating the correct configuration for existing npm packages.

I know it is somewhat frustrating, but just let me know if you have any further questions at all.

**Comment by johnjbarton** [comment]
I just want to import an npm module
```js
let React = require('react');
```
In this case I am unconcerned about any differences between nodejs and SystemJS resolution: I'm not asking SystemJS for anything.  Specifically I am not asking SystemJS to support `require('./mymodule.js')` which would require module-redefinition of `require()`.  I'll use `import` for all my code, but for pre-existing nodejs modules I think `require(<package>)` makes sense. 

I think its entirely reasonable for me to discover that `require('./mymodule.js')` does not work inside SystemJS loaded modules.  I'm not asking for SystemJS to do any compatibility work at all. But I don't think it's reasonable to discover that `require()` is a `TypeError` as a side effect of using SystemJS.   SystemJS can just do it's job and leave `require()` alone.

**Comment by guybedford** [comment]
In NodeJS, `require` is not a global, but a variable available in the execution scope. SystemJS doesn't touch any require global, rather it just ensures that non-CommonJS modules executed by SystemJS do not have a `require` in scope, and that CommonJS modules get the SystemJS `require` in scope.

React has a lot of dependencies making it something that you'd either need to load a browser build of through SystemJS, or use jspm (the [beta guide](http://jspm.io/0.17-beta-guide/) actually uses React in an example app), or use the Node require something like -

app.js
```javascript
var System = require('systemjs');
System.set('react', System.newModule({ default: require('react') });
System.config(...);
System.import('main.js');
```

Where `main.js` can then `import react from 'react'`.

**Comment by guybedford** [comment]
(and there's always the option of `var React = System._nodeRequire('react')` as well)

**Comment by johnjbarton** [comment]
Maybe SystemJS can read the `package.json` file and build the wrapper modules?

The current nodejs paradigm is:
- global: `npm install package --save`
- point-of-use: `var package = require('package');`

Your current solution:
- global: `npm install package --save`
- global: `System.set('react', System.newModule({ default: require('react') });`
- point-of-use: `import package from 'package';`

From the development and maintenance point of view systemjs has extra work.

By building the wrappers from `package.json`, systemjs would become competitive: 
- global: `npm install package --save`
- point-of-use: `import package from 'package';`

(I can't imagine using the non-standard and idiosyncratic `System._nodeRequire()` to access the de-facto standard `require()`;  if I used systemjs unpatched I would use `global.require()`. I still think patching systemjs to remove the require parameter is the best solution).

**Comment by guybedford** [comment]
SystemJS can actually support loading the NodeJS package.json files to read the main entry point with the configuration:

```javascript
System.config({
  baseURL: 'node_modules',
  packageConfigPaths: ['*/package.json']
});
```

Then `System.import('./main.js')` can import say `react` and have SystemJS read the package.json for `node_modules/react/package.json` read the main, then load the correct main.

The problem is there are a huge number of exceptions between the SystemJS resolution and the NodeJS module resolution (default extensions, Buffer and process globals, directory requires, core module mappings, etc, etc)

jspm will pick up exactly all these cases, making it competitive. SystemJS aims simply to be a consistent and predictable piece of software.

**Comment by johnjbarton** [comment]
Thanks for your help!
