### ISSUE TITLE
Bundled Angular2 app slower on 0.17 beta

### ISSUE THREAD

**Issue by tuurbo** [systemjs/systemjs#1200]
tested on chrome 49
both use npm:angular2@2.0.0-beta.13

jspm: 0.17.0-beta.12
init time: ~1.16s
https://plnkr.co/edit/SS2zvnHtuPvsXCrlihKU?p=preview
Couldn't get angular to load without running ```jspm depcache app/boot``` first

jspm: 0.16.12
init time: ~720ms
https://plnkr.co/edit/vTflk0Xs5HIU3lRxG5gc?p=preview

-------

The load times are worse on my larger company app.
jspm: 0.17.0-beta.12
init time: ~4s

jspm: 0.16.12
init time: ~1.6s

**Comment by guybedford** [comment]
You shouldn't need to depCache a bundled app. That may well be what is slowing things down here too.

It sounds like you're using the depCache to get around an execution ordering issue where `injector` is not defined properly? It may be worth trying to track down this ordering issue and using metadata to create the correct dependency relationship instead of depCache.
