### ISSUE TITLE
Proposal: Integrate HMR primitives into SystemJS Core

### ISSUE THREAD

**Issue by alexisvincent** [systemjs/systemjs#1222]
I would like to propose that we integrate HMR primitives into SystemJS Core. I think this would add to the  tooling capacity of the project and allow for interesting integrations. While [capaj/systemjs-hot-reloader](https://github.com/capaj/systemjs-hot-reloader) is great at an application level, it forces you to use its own events API which is problematic for anyone trying to create tooling around SystemJS & HMR. And while you can implement your own HMR logic void of an events system, HMR is a straight forward enough problem (at least where SystemJS is concerned) that this logic could be appropriately included into the core project.

I think the lack of supporting tooling built around SystemJS is one of the core reasons SystemJS feels 'hard' for new users and I think proper HMR support would go a long way to increase developer interest in the project.

@gaearon has released an alpha for [React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61#issuecomment-211627184) that will play brilliantly with SystemJS, allowing us to reload components without loosing state or destroying the DOM. Since JSPM 0.17 now uses Babel 6, @gaearon's react-hot-loader/babel transform would serve the vast majority of people. Otherwise it shouldn't be hard to implement a SystemJS plugin to do this. 

My proposal for SystemJS HMR would be to quite simply expose a

``` js
System.reload("./someModule.js")
```

Internally it could function almost exactly like [capaj/systemjs-hot-reloader](https://github.com/capaj/systemjs-hot-reloader), recursively deleting modules up the dependency tree and then reimporting them. While this is a simple extension I think it would act as an enabler for further tooling.

At this point it might be worth thinking about a potential plugin unload hook. That would fire on a

``` js
System.delete("./someModule")
```

Let's say for instance that a JS unload hook might call `__unload()` if such a function is exported from the module. This would cater both for https://github.com/capaj/systemjs-hot-reloader#unload as well as a general use case if a module is forcefully deleted.

Added loader unload hooks would also solve issues like https://github.com/systemjs/plugin-css/issues/81 and some extension of this idea might solve https://github.com/capaj/systemjs-hot-reloader/issues/37. Providing us with true CSS/SCSS reloading.

With regards to hydrating state after a reload I can see two ways to do this. The first would be the way [capaj/systemjs-hot-reloader](https://github.com/capaj/systemjs-hot-reloader) currently does it, which is to export a `__reload(module)` function and have that fired after the module has rerun on reload.

This works well until you want to incorporate reload logic into your standard module initialisation code and perhaps export a variable that might exist on the previous module instance. My suggestion would be to pass in the old instance of the module as a 'local/global' variable directly available to the module. This would allow for more complex handling of reload logic when required. Cleaning up reload behaviour for production (if required) could be easily handled via dead code removal as is standard in the industry (via JSPM's `bundle --production` flag?).

Implementing something similar to the above proposal would change the focus of [capaj/systemjs-hot-reloader](https://github.com/capaj/systemjs-hot-reloader) and other tooling rather into one of handling file change events. This would also make it trivial for developers to build their own bundling logic if they so required.

Some extra food for thought:
A `System.reload("./someModule.js")` function could additionally take in **_source code**_ as a second argument.

``` js
System.reload("./someModule.js", source)
```

This would mean that a file-watcher/socket system could pass the new code to the client directly. For a satisfyingly fast development loop.

@guybedford Let me know what you think.
Also, @tyscorp this might interest you.

**Comment by guybedford** [comment]
@alexisvincent thanks for considering these perspectives, it's really great to hear you're interested in how to improve the hot reloading experience in SystemJS.

Any suggestions you have re how to support the React Hot Reloader 3 work would be great to hear here.

Just to backtrack a little, your argument seems to stem from the fact that systemjs-hot-reloader on its own is not enough, primarily because it locks you into an eventing API. Do you think it would be possible to separate this project from its eventing API perhaps?

I certainly agree that bringing features like this into core will better enable an ecosystem around it, but at the same time, we have to be very careful about anything we bring into SystemJS core as core has to be backwards-compatible.

Since SystemJS provides an open loader API, we can potentially build tooling around SystemJS that creates methods like this `System.reload` (which sounds great to me), but that is still a third-party project that is loaded in.

I'd be much happier bringing something like this into core if it was already existing and proven as a third-party project, before jumping straight to any core implementation. There is a lot that can be done through the extension techniques here.

Perhaps it would be possible to restructure the systemjs-hot-reloader project to be based on these public `System.reload` and `System.unload` methods, and then that would provide a separation of the messaging API from the reloading API allowing better hot-reloading tools on top of such a base?

**Comment by alexisvincent** [comment]
@guybedford Sure :) I'm a huge fan of the project and I'm keen to support the great work you do.

Regarding React Hot Reloader 3, it would seem as if the project should work in SystemJS without modification. Haven't tested this yet, however theoretically it should be fine. All that's happening is essentially a compile time transform where a property is added to any exported function that remotely looks like a react component. There's a babel plugin for this, so most people are fine there. Then RHL3 monkey patches the createElement function to do all the state preserving with react proxy. So there doesn't seem to be any specific work done here to get it to work in SystemJS.

I hear you with regards to being careful about what is added to core, especially regarding backwards compatibility and stability. I think it probably would be a good bet to start a more modular hot reloader project as an external project (with minor forward thinking support in core) and then later bring it in to core once its stable. To implement some of the support I proposed I struggle to see how this would be achievable without introducing certain changes to core.

I am specifically referring to:

**Loader unload behaviour**
This is a change that would require an addition to the loader api. Not just adding a ```System.unload``` function and as such an external plugin would not be able to add this. Plugins would be able to optionally export an ```__unload('./module.ext')``` behaviour.

**State Hydration**
This is also something I'm not sure how to do without core support?

> My suggestion would be to pass in the old instance of the module as a 'local/global' variable directly available to the module. This would allow for more complex handling of reload logic when required.

How would you feel about the above two issues?

I do think that once this is stable however it would be important to merge the project into core. It luckily also has a small api surface area and so backwards compatibility from a user perspective shouldn't be too much of an issue. Thoughts?

Let's imagine we decide to create a new HMR project for SystemJS with a focus on modularity and a goal of merging into core. I think it would be important that it be under the systemjs github namespace. This will go a step towards developer trust while it's still an external project.

**Comment by alexisvincent** [comment]
Also, HMR can be done better currently (without loosing state or destroying the DOM) even without RHL3, if I get time I'll submit a PR to the JSPM 17 docs.

**Comment by guybedford** [comment]
I wonder if the React hot reloader could be attached by traversing all the modules in the registry and all their exports which are functions and doing the same thing there?

If `System.unload` was added might that not work as an alternative to `System.delete` which runs things like the `__unload` hook?

Doing state hydration through a local variable still feels like an aesthetic argument to me, since we get the same feature from a `__reload` hook. Supporting this would be possible outside of core though, through translation of the ES module to add a local scope variable, possible through the loader hooking process.

I'm not sure though that forking the existing hot reloader would be beneficial. Experimental projects on the side that don't aim to grow a user base are always fine, but usually much more can be gained by having discussions with the existing project and sharing the existing expertise.

**Comment by alexisvincent** [comment]
@guybedford Yes actually that way would work really well, then we can have it as a client side transform. Might also be worth having this implemented as an translate hook on a js loader to do this automatically, since this would need to be run on load anyway.

Not sure what you mean with regards to ```System.unload```. My suggestion was not to add ```System.unload```, however this might be clearer? What I was suggesting instead was to add an unload hook to loaders, but I can see how this might have been confusing.

The idea is for loaders to export an unload behaviour that gets fired when ```System.delete``` gets called. 
For example, the js loader could export an unload behaviour that runs an optional exported ```__unload``` function on the module getting deleted. A CSS loader could expose a behaviour that deletes the css link node from the head of the DOM, etc.

> This would cater both for [the capaj/systemjs-hot-reloader unload behaviour](https://github.com/capaj/systemjs-hot-reloader#unload) as well as a general use case if a module is forcefully deleted.

Do you see what I mean?

For the state hydration, the reason I suggested a local variable is primarily because I've personally experienced non aesthetic limitations of the ```__reload``` function. Specifically if for instance you want to export a variable in your module that relies on the previous module state. Since ```__reload``` is fired after the module has been imported and run (and consequently all exports have happened). But I'm glad this can be done without relying on core.

I agree with you regarding forking. I'd be happy to help with this project, however I don't have a very good grasp of core. I've tried to go through the source a few times, but it's a bit challenging without prior architectural understanding (however those new docs might come in handy).

What would your advice be for moving this forwards? What do you think of the proposal? Would you be able to dedicate some time towards this in the coming weeks?

**Comment by guybedford** [comment]
Overloading `System.delete` or creating a new `System.unload` could both work. I think the important thing is that it is extending the API to deal with this case. I tend to prefer a `System.unload` because then `System.delete` remains predictable, so using `System.unload` in the hot reloader itself could be considered an API refactoring. I can't really comment too much on any refactoring public API as I haven't thought a massive amount about it.

Note that exports in ES6 modules are live, so you can update the bindings after the exports have "run". For example:

```javascript
export var num = 5;
export function changeNum() {
  num = Math.rand();
}
```

Allows altering the export of the module by calling its `changeNum` function.

In terms of moving forward, I don't have any time for this area unfortunately (see https://github.com/jspm/project/blob/master/ROADMAP.md). Perhaps do some experiments here yourself, and share your ideas with @capaj here. But feel free to fill me in on any issues.

**Comment by capaj** [comment]
@guybedford thanks for CCying. I am swamped with work for the next 6 days, but I will try to make the separation from the eventing API inside systemjs-hot-reloader. I would probably create a project **systemjs-reloader** which would then be utilized in systemjs-hot-reloader.
systemjs-reloader would provide only to methods:

- System.unload
- System.reload

@alexisvincent good idea to allow providing the string-that should speed things up

**Comment by alexisvincent** [comment]
@guybedford What would be the function of ```System.unload```? Would it simply be a ```System.delete``` wrapper that additionally implements the loader unload hooks I suggested? Or something else? It's not entirely clear what you mean.
Thanks for the live reloading clarification.

@capaj Do you call ```__reload``` directly after a module has loaded, or once the full dependency tree has been imported?

**Comment by alexisvincent** [comment]
@guybedford thoughts?

**Comment by guybedford** [comment]
@alexisvincent `System.unload` would just be an alternative to `System.delete` that runs the `__unload` hook on modules, and also unloads all the parent modules that import that module. Perhaps `System.unloadTree` would be a better name, or even to simply combine it with the hot reloading and just have a single `System.hotReload(moduleName, moduleValue)` function.

**Comment by alexisvincent** [comment]
@guybedford Cool, I would suggest a clean ```System.reload('moduleName', 'moduleValue')```. This can be the sum total of the api (keeping it light). Then later if you would like to introduce it to the api the unload part can be moved to the responsibility of ```System.delete```.

**Comment by guybedford** [comment]
Sounds good to me.

**Comment by whitecolor** [comment]
Hi there. I too have my HMR module working for system.js based loader StealJS.
https://github.com/whitecolor/steal-hmr

It doesn't support System.js itself currently but it is easy to add.

I've used it with react-hot-loader (and hot reloaders for other frameworks), it worked fine.

I think HMR capability could be built in in the core, but also could go as separate plugin,
What I think that it is a good idea to support webpack/browserify `module.hot` API with accept and dispose methods.

@guybedford what is the best way currently to get the dependants  of current module?

**Comment by alexisvincent** [comment]
For anyone else who stumbles upon this issue. The project adding the System.reload extension to SystemJS is [alexisvincent/systemjs-hmr](https://github.com/alexisvincent/systemjs-hmr). systems-hot-reloader now relies on it. So this is making progress.
