### ISSUE TITLE
Typescript: `import * as module from 'module'`

### ISSUE THREAD

**Issue by Mosho1** [systemjs/systemjs#1251]
When trying to use the syntax in the title:

```
import * as flow from 'lodash/flow';
console.log(flow)
```

Transpiles into: 

```
var flow_1 = require('lodash/flow');
console.log(flow_1);
```

Which is fine in node (`flow_1` is the function) but in the module exported using systemjs `flow_1.default` is the module.

Is there a way to regulate this?

**Comment by guybedford** [comment]
Use `import flow from 'lodash/flow'`, which was designed for this compatibility use case.

**Comment by Mosho1** [comment]
I was, which worked with system but not in node (transpiles to `flow_1.default`). I asked and was told to use `import * as flow from 'lodash/flow` to avoid it.

**Comment by guybedford** [comment]
`import flow from 'lodash/flow'` is the correct import form for loading CommonJS from ES6 modules. The interop case should be handled by the transpilation layer (for example Babel has an `__esModule` check for this when compiling to CommonJS).

**Comment by Mosho1** [comment]
(This)[http://i.imgur.com/TuSxy2B.png] is what I see being imported, while the function itself is imported as the exports in current node. Shouldn't the two be aligned?

**Comment by guybedford** [comment]
How are you transpiling the TypeScript?

**Comment by Mosho1** [comment]
Letting System do it. Here's the config:

```
/* ... */
transpiler: "ts",
  typescriptOptions: {
    "module": "system",
    "noImplicitAny": false,
    "typeCheck": "strict",
    "tsconfig": true
  },
/* ... */
```

Using System 0.19.26 Standard and TypeScript 1.8.9

**Comment by guybedford** [comment]
Try setting the `allowSyntheticDefaultImports: true` option there.

**Comment by Mosho1** [comment]
No dice. This seems relevant though:

https://github.com/Microsoft/TypeScript/issues/7518

**Comment by mhegazy** [comment]
`allowSyntheticDefaultImports` is set to tru by default if `"module": "system"`. is there a sample i can look at?

**Comment by Mosho1** [comment]
@mhegazy Nothing to it really, https://github.com/Mosho1/systemjs-typescript-import-example

**Comment by guybedford** [comment]
@Mosho1 by running in Node do you mean through `jspm run` here?

**Comment by guybedford** [comment]
Also note that using https://github.com/frankwallis/plugin-typescript is the recommended workflow for TypeScript.

**Comment by Mosho1** [comment]
Using the plugin (which I used in the project where I saw the problem) yields the same results. And by running in Node I mean transpiling and running in node (or just using `require('lodash/flow')` in the node REPL).

**Comment by guybedford** [comment]
@Mosho1 but then how are you running the System module format in Node? This is offered through `jspm run module` for full jspm support.

**Comment by Mosho1** [comment]
I didn't mean I did that, just that the same code transpiled to `require` syntax and to System format behaves differently, with regards to exported modules. `lodash/flow` has no `default` export (`module.exports = flow`) which is the case for running in node but not System.

**Comment by guybedford** [comment]
Right ok I see what you mean. Yes as far as I'm aware TypeScript doesn't implement a NodeJS interop like Babel compilation to CommonJS does. I'd suggest looking into `jspm run` or using SystemJS directly in Node for these use cases to execute System.register output with interop.

**Comment by DanielRosenwasser** [comment]
Yes, it's looking like we'll need to implement the downlevel CommonJS interop and we're investigating it. As a temporary workaround, you should be able to import both using `--allowSyntheticDefaultImports` and writing something like

```ts
import flowD from "lodash/flow";
import * as flowN from "lodash/flow";
const flow = flowD || flowN;
```

Let me know if that works.

**Comment by djflex68** [comment]
Hello, I don't know if my problem is linked to this one but I have a similar issue for which I can't find any solution.
My app consists of 
- a server part that compiles to CommonJS
- a client part that compiles to SystemJS (flag allowSyntheticDefaultImports on)
- a shared part that is imported (copied) into both client and server parts.
I cannot figure out how to import some libs like bluebird or lodash without having either the compiler complaining about something or an exception at execution level. I used definitions files provided by DefinitivelyTyped for bluebird/lodash.

I tried all import syntaxes I could find, but without success

`import Promise from 'bluebird';` do not compile on CommonJS,

> Module '"bluebird"' has no exported member '_'.

`import {Promise} from 'bluebird';` still do not compile on CommonJS,

> Module '"bluebird"' has no exported member '_'.

`import * as Promise from 'bluebird';` compile on both CommonJS and SystemJS, but crashes during execution, on some functions that directly use Promise as constructor

`import Promise = require ('bluebird')` old syntax compiles on both CommonJS and SystemJS. But crashes at execution on SystemJS, because Promise cannot be used directly as constructor/function. 

> Error: TypeError: Promise is not a constructor(…)

Do you have any solutions for this problem ? What is the right way to do in this case ?

**Comment by Mosho1** [comment]
@DanielRosenwasser Yeah, that's what I did. Should suffice for now.
@djflex68 Sounds like you are indeed having the same problem. Try what Daniel suggested.
