### ISSUE TITLE
Consider deprecating plugin syntax entirely

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1326]
Plugins via configuration are always the preferred mechanism.

I'm kind of on the fence with this but I'm going to leave this up here to consider further. If anyone has a really good reason for why we shouldn't deprecate plugin syntax I'd be very interested to hear.

See also https://github.com/systemjs/systemjs/issues/1092.

**Comment by brainkim** [comment]
Hey! I come from webpack world and might have some experience with building and maintaining systems that use “plugin syntax.” I realize now from experience that using code as innocuous as `require("foo.js!raw-loader")` tightly couples your code to the webpack build process, especially when targeting node.js environments, and I worry that `import` plugin syntax could cause the same sorts of problems for SystemJS, especially if the node community ever gets around to implementing es6 imports. Additionally, I think that in 90% of use cases, the filename is sufficient to determine how you want the files to be `translated` and `instantiated` in the browser.

These are all strong opinions, weakly held. I would love to have a debate about this with people who think otherwise.

**Comment by guybedford** [comment]
Thanks for the feedback, I definitely agree. It's just about accepting the configuration step I guess.

**Comment by aluanhaddad** [comment]
@guybedford While I'm almost a hundred percent in agreement, and I certainly use configuration over plugin syntax 99% of the time, there are occasions when it is desirable to pipe only a single file through an arbitrary plugin.
It's certainly not a problem to specify the configuration in these cases but it can be handy for testing to be able to apply the syntax to a single import without changing configuration until you know it is working.

@brainkim makes an excellent point about the high degree of loader coupling introduced by plugin syntax. Having converted a large requirejs based application to SystemJS, I know firsthand how true that is. If the project had used plugin configuration it would have been a non-issue.

Another problem with plugin syntax is that it can get out of hand. For example, the dojo loader has so many different variants of plugin syntax that are used by the pre-built esri ArcGIS API for JavaScript, where the source code is not made available, that recognition of the plugin syntax is required to load the file. This is both an argument both for and against plugin syntax as it becomes impossible to load certain bundles, although in the case of dojo, it's best not to go down the rabbit hole and even try as you all spend hours in the abyss. I never understood why something like domready had to be a plugin anyway. Maybe they were good historical reasons for it, but it's confusing.

I think there should be a happy path for developers new to SystemJS and/or to the idea of plugins where, if they are using jspm, they should be prompted on installation of a plugin to have it automatically configured for them. A reasonable automatic configuration could be too inject the config into the package containing the main file in package.json. I think this would help as some people do not seem to understand how plugin configuration works, and there are lot of examples out there showing use of the plugin syntax.

Another interesting thing is that when using `SystemJS.Import` you can construct a URL and choose an arbitrary loader plugin based on something at runtime. Of course this is a bad practice, but I have a feeling there are at least a few people relying on it although I'm not one of them and have no evidence. Perhaps the API of this function can be changed to allow specifying a specific loader without actually creating or mutating configuration or creating a new loader instance.

In the angular 2 community there are a ton of tutorials and official guidelines suggesting the use template urls which are very fragile, rely on loader specific/transpiler specific embedded module IDs, and this is simply a non-issue when using plugins. Importing the template into the component file is a far superior solution. I bring this up because I think it's important to promote the use of loader plugins in these types of scenarios but to do so we need to make it extremely easy to use by default.

Sorry for the long rambling post.

**Comment by peteruithoven** [comment]
I can think of two cases where the plugin syntax might be handy:
- When using CSS Modules the loaded styles are local by default. There are exceptions you want to apply styles globally, which can be done by specifying another loader. 
- When loading js files for usage inside a web worker. 

Both these cases could probably also be handled by a file specific meta config? But then the disconnect might be annoying. Annoying for example when moving those files.

**Comment by guybedford** [comment]
It does seem worth keeping this for now for the benefits of syntax over configuration for code portability.
