### ISSUE TITLE
Support ES6 transpile when loading CJS modules

### ISSUE THREAD

**Issue by mmoulton** [systemjs/systemjs#1420]
I'm trying to load a node module written in ES6 from NPM / Github and use it in a SystemJS/JSPM web application. The node module is published to npm as ES6 as it's designed to run in Node 5.x/6.x where it works great.

When I try to load this module into my SystemJS based app using an `import x from 'module-name-mapped-to-npm';` the module loads just fine and even works in modern browsers that support ES6. The problem comes in when I wish to bundle for production and minify. Since the loaded code is written in ES6, the imported module in the bundled file is properly wrapped to handle the `require` calls, however the file is still in ES6 format. Uglify does not like this since the main line does not yet support ES6.

Looking into SystemJS's code base, it seems the CJS format only has a `instantiate` hook, not a `translate` hook like the ESM format. My desire here is to either have the CJS plugin format support both a `instantiate` that wraps to support `require` as well as a `translate` hook so I can run the code through babel or the like. Support for some sort of pipelining/combining of the formats would also work.

If there is another way to handle this that does not require me to pre-transpile the node module before publishing to NPM, I'd be happy for some guidance.

**Comment by mmoulton** [comment]
I wanted to provided an update for anyone who might run into this issue. I was able to get CJS modules written in ES6 to be properly transpiled to ES5 by adding the following `meta` block  to the package in question under the `packages` section of your config file.

```json
"meta": {
  "*.js": {
    "format": "cjs",
    "loader": "plugin-babel",
    "babelOptions": {
      "modularRuntime": false
    }
  }
}
```

**Comment by kylecordes** [comment]
I think I have run into approximately the same question, using the shiny new Angular 2 rc.6 which has been "repackaged" so that the sole provided format is (if I'm looking at this right) otherwise generally ES5-looking code but in ES6 modules. I'm looking around for the best way to consume libraries that arrive in that format concurrently with application code in typescript. Then somehow compile both appropriately during a bundle. I suspect the answer will come from somewhere over in the angular community, but if I find it I will attempt to paste it here for the next person.
