### ISSUE TITLE
importing knex.js with ES6 syntax

### ISSUE THREAD

**Issue by n1kt0** [systemjs/systemjs#1460]
hello, i tried for several days in the last two weeks to get knex.js imported via the es6 import syntax and couldn't get that running. when i run the node script with jspm i get the 2 following errors (sometimes alternating and sometimes not):

**first error:**
```
err  (SystemJS) ENOENT: no such file or directory, open '/path/to/project/jspm_packages/npm/knex@0.12.2/lib/dialects/sqlite3.js'
  Error: ENOENT: no such file or directory, open '/path/to/project/jspm_packages/npm/knex@0.12.2/lib/dialects/sqlite3.js'
      at Error (native)
  Error loading /path/to/project/jspm_packages/npm/knex@0.12.2/lib/dialects/sqlite3.js as "../sqlite3" from /path/to/project/jspm_packages/npm/knex@0.12.2/lib/dialects/websql/index.js
```

**second error:**
```
err  (SystemJS) ENOENT: no such file or directory, open '/path/to/project/jspm_packages/npm/knex@0.12.2/lib/migrate.js'
  Error: ENOENT: no such file or directory, open '/path/to/project/jspm_packages/npm/knex@0.12.2/lib/migrate.js'
      at Error (native)
  Error loading /path/to/project/jspm_packages/npm/knex@0.12.2/lib/migrate.js as "../migrate" from /path/to/project/jspm_packages/npm/knex@0.12.2/lib/util/make-knex.js
```

i think the second error is more relevant for problem solving. systemjs tries to load a migrate.js file while at the knex.js package location is a folder named migrate with an index.js. by the way which module format is that?

thanks in advance

**Comment by guybedford** [comment]
I managed to make some progress on this in https://github.com/jspm/npm/commit/1dd23bd72775c490eb7af9d6115f19f00193629d to fix these paths issues.

Unfortunately we then hit that `sqlite3` can't load through jspm, and this is a known limitation because it relies on Node binary support which is not currently provided by jspm.

With the above patch to jspm-npm, this should work though through something like:

```
jspm install npm:knex -o "{map:{'sqlite3':'@node/sqlite3'}}"
```

Where `sqlite3` is installed through npm. Although this does rather defeat the point of using jspm in the first place. So it may just be best to give up here if this isn't a browser project - jspm is best used for browser libraries.

**Comment by guybedford** [comment]
Actually I mean not adding a map like the above but rather just editing the jspm.config.js file and adding a manual top-level map like that:

```javascript
System.config({
  map: {
    sqlite: '@node/sqlite3'
  }
});
```

**Comment by n1kt0** [comment]
this is both a browser and server side project but knex is only used on the
server with bookshelf. my goal was to keep the syntax consistent over both
environments. do you think i would again get in trouble when i want to
manage my services on the server with pm2 because it depends on node, to be
honest i read only about it but didn't dive into it deeper for now? i
already thought about giving up because of that knex issue and using
vanilla node for the server modules. some opinion would be nice on that.

**Comment by guybedford** [comment]
Yes, you will always need Node for server deps.

**Comment by guybedford** [comment]
*npm
