### ISSUE TITLE
Allow partial overrides (merges)

### ISSUE THREAD

**Issue by andreas-wagner** [systemjs/systemjs#1462]
As I need to use a lot of overrides, I find it rather troubling that I have to know the whole module@version.json config beforehand and then formulate a 'complete' override including also the stuff you do not want/need to change.

This can bite when the module has a new version. There is always a chance that it can bite, but having a merge option will significantly reduce that chance.

How about another option like `-o`, lets call it `-om` (for override and merge) which merges the module@version.json like [_.merge](https://lodash.com/docs/#merge)?

I think it would help a lot.

**Comment by guybedford** [comment]
Note this is a jspm issue not a SystemJS one.

The advised workflow here in jspm 0.17 is actually to edit the `registry:package/name@x.y.z.json` file manually and make changes that way instead of running an install override. That provides a much quicker refresh workflow to see changes. Then to save the override changes from the `.json` file into the package.json automatically, run `jspm install` once and it will persist the manual edits for you.
