### ISSUE TITLE
AMD DML fails with dynamically generated dependency token

### ISSUE THREAD

**Issue by CNSKnight** [systemjs/systemjs#1533]
Consider:
```
window.define = System.amdDefine;
...
define(['modules/path/templates/js/resource.js?v='+myObj.prop.vrsn_str], ...)
```
throws `Error: (SystemJS) define is not a function`.

Likely due to the eval of the script?
Converting to a map property would be less convenient.
I tried escaping the reference and wrapping in () but neither solved.
Any work-around?

**Comment by guybedford** [comment]
It may be trying to interpret the module file as CommonJS or as a global. Perhaps try enforcing the format with meta configuration:

```javascript
System.config({
  meta: {
    'path/to/module.js': { format: 'amd' }
  }
});
```

**Comment by Worthaboutapig** [comment]
I have a similar problem:
` define([conditional ? "/success" : "/fail"], factory);`

It looks like the parser is very naive and is expecting something exactly of the form '["/path/to/a", "/path/to/b", ... ]".  Is the `define` extracted from a regex of this form (zero or more quoted, delimited values)?

Would it be bad to match `define([ /* whatever is inside the array delimiters is assumed to be valid at the callsite */], factory);`?

It seems unreasonable that valid JS should fail to be recognised.  In my case, I also didn't receive any errors, but the injected module was an empty object, instead of the expected module.

Fortunately, the map workaround works, but it's hacky (and, looking at the code, SystemJS did believe that this was a CommonJS module).
