### ISSUE TITLE
RFC: Plugin to register modules for dynamic use in static builds

### ISSUE THREAD

**Issue by Rush** [systemjs/systemjs#1534]
```js
import {relative} from 'path';

export function fetch(load) {
  let outSource = '';
  let isLocalBuild = !!load.name.match(/^file:\/\//);
  let modName = relative(System.baseURL, load.address);    
  if(isLocalBuild) {
    outSource += `
import exportedModule from ${JSON.stringify(modName)};
SystemJS.registerDynamic(${JSON.stringify(modName)}, [], false, function (require, exports, module) {
module.exports = exportedModule;
});
`;
  }
  outSource += `export * from ${JSON.stringify(modName)};`;
  return outSource;
}
```

Usage:
```js
import 'ace/theme/textmate.js!register';
```

Now anybody can import this module without external requests and despite it being part of the static bundle:
```js
System.import('ace/theme/textmate');
```

So, purpose of the code is to allow statically built applications to bundle dynamic dependencies.

Question... it works but ... is it all good? How to properly re-register ESM modules?

**Comment by asapach** [comment]
I'd rather use [bundle arithmetic](https://github.com/systemjs/builder#bundle-arithmetic) to include the dynamic dependencies into the bundle. I think you're just abusing the `import` statement here.

**Comment by Rush** [comment]
Well, abusing or not I am also taking advantage of the rollup optimization which can be a huge gain in some cases. :)

**Comment by joeldenning** [comment]
Note that SystemJS plugins (like this one you've proposed) are independent of systemjs and do not need to be approved here in order for you to build it. That being said, I think this is probably as good of a place as any to discuss the pros/cons of such a plugin.

Does this plugin force your static builds to be loaded onto a page that already has full blown SystemJS loaded? If so, that is my main concern, since static builds are supposed to be usable independently of SystemJS.

Another concern is that the proposed plugin seems like it is trying to be more of a builder plugin than a systemjs plugin. What I mean by that is that systemjs plugins are intended to work in all of the following envs: NodeJS, browser, bundle (executed in node but targeting both node/browser), and static build (executed in node but targeting both node/browser). The proposed plugin seems to be targeting static builds (and nothing else?), which makes me wonder: would this functionality be better achieved by pull requesting systemjs/builder itself??

About rollup optimization, are you talking about being able to tree shake `ace/theme/textmate`? Or are you more concerned with being able to tree shake the rest of your static build?

I think the currently recommended flow is to `jspm bundle ace/theme/textmate bundle.js && jspm build my-app - ace/theme/textmate build.js`, followed by 
```html
<script src="system.js"></script>
<script src="bundle.js"></script>
<script>
  System.import('/build.js');
</script>
```

Does the above flow achieve similar results to what you're looking for? What are the differences you're looking for? Maybe that you want to tree shake `ace/theme/textmate`? Or that you want just one built file instead of having a `bundle.js` and a `build.js`?

**Comment by Rush** [comment]
Thanks for your comment @joeldenning

> Does this plugin force your static builds to be loaded onto a page that already has full blown SystemJS loaded? If so, that is my main concern, since static builds are supposed to be usable independently of SystemJS.

Indeed this is the assumption. While static builds are supposed to be usable independently of SystemJS, my particular use case still needs System.JS for dynamic asset loading.

> Another concern is that the proposed plugin seems like it is trying to be more of a builder plugin than a systemjs plugin. What I mean by that is that systemjs plugins are intended to work in all of the following envs: NodeJS, browser, bundle (executed in node but targeting both node/browser), and static build (executed in node but targeting both node/browser). The proposed plugin seems to be targeting static builds (and nothing else?), which makes me wonder: would this functionality be better achieved by pull requesting systemjs/builder itself??

It is a builder plugin in a sense that when building it does inject the `SystemJS.registerDynamic`, but in all the cases it simply import the module itself and does not need to register it cause it is already registered.

Not sure how systemjs/builder could be improved to address my need. This plugin seems to solve it quite fine.


> About rollup optimization, are you talking about being able to tree shake ace/theme/textmate? Or are you more concerned with being able to tree shake the rest of your static build?

Tree shaking the rest of the static build. I think bundles by nature cannot tree shake since they need to register each and every module ... unless bundle builds could be improved to explicitly specify exported modules.

> Does the above flow achieve similar results to what you're looking for?

If it could do tree shaking than possibly it would work. I primarily care about having only couple specific named modules and rest of the stuff optimized as much as possible with tree shaking and without registering needless modules.

**Comment by joeldenning** [comment]
The recommended flow I described above does tree shaking for every module except for `ace/theme/textmate`. Doing a `bundle` for shared stuff and a `build` for everything else (subtracting out the shared stuff from the build) is how I usually do things because it provides the smallest bundles and fastest load times, as far as I know.

I would recommend giving that a try -- everything that is part of the `build` will be optimized with tree shaking.

**Comment by Rush** [comment]
Actually, I'd like to tree shake everything. I just realized some of those "plugins" are gonna be pretty big so it's not only small things like ace editor themes. Another requirement I have is that plugins need to be build-able "out of tree", in a separate directory, with separate JSPM config.

With each bundle having its own set of:
```
System.registerDynamic("npm:systemjs-plugin-babel@0.0.17.json", [], false, function() {
  return {
    "main": "plugin-babel.js",
    "map": {
      "systemjs-babel-build": {
        "browser": "./systemjs-babel-browser.js",
        "default": "./systemjs-babel-browser.js"
      }
    },
    "meta": {
      "./plugin-babel.js": {
        "format": "cjs"
      }
    }
  };
});

System.register("npm:systemjs-plugin-babel@0.0.17/babel-helpers/classCallCheck.js", [], function (_export, _context) {
  "use strict";

  return {
    setters: [],
    execute: function () {
      _export("default", function (instance, Constructor) {
        if (!(instance instanceof Constructor)) {
          throw new TypeError("Cannot call a class as a function");
        }
      });
    }
  };
});
```
These modules will repeat themselves in each plugin. I want my bundle to export one module only.

Perfect solution for me would be to be able to bundle with only specific things exported.

**Comment by joeldenning** [comment]
As far as I know, the reason why `jspm bundle` does not do tree shaking is because of the synchronous nature of dynamic imports in commonjs. The issue with running commonjs modules in the browser is that `require` is synchronous and you can even use code/variables to change what is `require`d. This works in a node env because the file system can be accessed in a blocking/synchronous way. Contrast that with the browser, though, where a `System.import()` might trigger a network request which is definitely not synchronous.

Consider if the textmate theme for ace had the following code in it:

```js
// ace/theme/textmate.js

export function loadPlugin(pluginName) {
  return require('aDependency/plugins/' + pluginName);
}
```

In that case, which dependencies should systemjs-builder bundle into the runtime bundle? If you were doing a static build-time build, then it could potentially try to parse all of the code at build-time to determine which plugins need to be put into the build. But for runtime builds it is different because you don't know how the code is going to be used at runtime (in the browser). Someone could call `loadPlugin('foo')` but they could also call `loadPlugin` with anything else. It is for this reason that what `jspm bundle` does is it puts all of the dependencies into the bundle so that no matter what anybody does in the browser, the dependency can be `require`d in a synchronous fashion, and the code will execute correctly.

I'm hoping that this explanation helps. I think what I'm getting at with this is that in order to support commonjs modules, `jspm bundle` does not do tree shaking. Perhaps `jspm bundle` could do tree shaking for all non-commonjs modules, or perhaps it could try to be smart about detecting if there are dynamic `require`s, and do tree shaking in all situations where there is not a usage like the one described above. Those are all things that could be explored in the systemjs-builder repository. I don't think that the `!register` plugin for systemjs is something that would be recommended, since if it were implemented in systemjs-builder everyone would benefit without having to use the `!register` plugin.

That being said, definitely feel free to build this plugin if it's the route you want to go :). My hope is just to try to explain and guess as to best path for the systemjs ecosystem, as a whole.

**Comment by joeldenning** [comment]
Another thing to consider in this discussion is that tree shaking is only done to es6 modules, since what it's doing is looking for static import statements and removing exported values that are never imported. 

So unless the ace package is written in es6 (and doesn't compile things down to require), you can't tree shake it
