### ISSUE TITLE
Enhancement: Allow for simply named dependency resolution

### ISSUE THREAD

**Issue by josh-sachs** [systemjs/systemjs#1576]
This enhancements stems from my experience here: http://stackoverflow.com/questions/42105893/systemjs-depdencies-not-loading/42118046#42118046

IMHO it doesn't make sense that you cannot simply reference a package by name when defining dependencies.   Furthermore, it doesn't make sense that dependency declarations within package meta either don't work, or are non-trivial/obvious to setup.  

Right now, it seems I actually need a helper function to get things wired up in a homogeneous way. 

`function(packageName: string, defaultExtension: string, args = {}) { ... }`

For dependencies I need to walk backwards from the package and maping configuration i'm applying... where `deps: string[]`

```
if (args.deps) {
       cfg.depCache[name] = args.deps;
       if (args.main) cfg.meta[`${cfg.map[name]}${args.main}.${ext}`] = { deps: args.deps };
}
```

This feels broken.

**Comment by guybedford** [comment]
meta does run through map configuration, the issue is that meta applies to specific module names.

That is `map: { app: 'src/' }` with `meta: { 'app': { exports: 'x' } }` will configure a meta for the path `src/`. Instead you would want to set `meta: { 'app/x.js': { exports: 'x' } }` to specifically set a meta for the exact path of the file.

If the map configuration is used to map into an exact module name rather, then this meta approach can work.

**Comment by guybedford** [comment]
Note also `meta: { 'app/*': { exports: 'x' } }` would work too, although seems unnecessarily ambiguous.
