### ISSUE TITLE
SystemJS@0.20 incompatible with TypeScript

### ISSUE THREAD

**Issue by unional** [systemjs/systemjs#1587]
It seems like `newModule()` does not work well with CommonJS module that exports a function.

Sample code:
```ts
const lowercase = require('lower-case') // lowercase is a function

// configuration skipped for simplicity
SystemJS.set('lower-case', SystemJS.newModule(lowercase))
SystemJS.import('my-module')

// my-module/index.js
var lowercase = require('lower-case')
console.log(lowercase) // prints `{ }`
module.exports = lowercase('my-module')
```

Is there a way to solve this?
This is for the plugin system I'm working on. The config is similar to: https://github.com/unional/some-issues/blob/systemjs-jsdomify/src/createSystemJS.ts

**Comment by unional** [comment]
A more interesting case is:

```ts
SystemJS.set('systemjs', SystemJS.newModule(SystemJS))

// consuming
import * as SystemJS from 'systemjs'

/* prints: 
{ registry: [Getter],
  trace: [Getter],
  _loader: [Getter],
  scriptSrc: [Getter],
  _nodeRequire: [Getter],
  amdDefine: [Getter],
  amdRequire: [Getter] }
*/
console.log(SystemJS)

// `constructor` is undefined
const sys = new SystemJS.constructor()
```

**Comment by guybedford** [comment]
System.newModule just iterates the iterable properties of the supplied object and turns them into a module.

Use `System.newModule({ default: require('cjs-module') })` rather.

**Comment by unional** [comment]
> Use System.newModule({ default: require('cjs-module') }) rather.

Seems like `System.newModule({ default: require('systemjs') })` doesn't work. At consuming, `require('systemjs').constructor` is still undefined.

I'll setup a repro and also try to dig in. Should be possible to fix at my level. 😛

**Comment by unional** [comment]
Here is the repro:
https://github.com/unional/some-issues/tree/systemjs-newModule

**Comment by unional** [comment]
Confirmed that `SystemJS.constructor` is not in `Object.keys(SystemJS)`, thus not copied to the module.

```js
Object.keys(SystemJS);
/*
[ 'registry',
  'trace',
  '_loader',
  'scriptSrc',
  '_nodeRequire',
  'amdDefine',
  'amdRequire' ]
*/
```

**Comment by unional** [comment]
Ok, this cause a much bigger issue. The way `systemjs@0.20` handles commonjs code is not the same as how TypeScript handles commonjs code.

My understanding is that `systemjs@0.20` follows babel and nodejs to import commonjs in the `default` property.
However, TypeScript does not.
In TypeScript,
```ts
// gets the command js export.
// When loaded through `SystemJS.set('systemjs', ...)`, it becomes { default: systemjs}
const systemjs = require('systemjs')

// That's how it gets the `module.exports`
import * as CJSModule from 'cjs-module'

// while babel
import CJSModule from 'cjs-module'
```

This is related to
https://github.com/Microsoft/TypeScript/issues/7398
https://github.com/Microsoft/TypeScript/issues/8687

And it is a serious problem.
AFAIK, there is no good solution (`allowSyntheticDefaultImports` wouldn't work due to https://github.com/Microsoft/TypeScript/issues/7398).

**Comment by unional** [comment]
I think needing to do `SystemJS.newModule({ default: require('cjs-module') })` is the wrong approach.
Putting TypeScript asides, this cause CJS itself to break:

```js
const lowercase = require('lower-case'); 
lowercase => [function]

// After loading from SystmJS.set(...)
lowercase => { default: [function] }
```

**Comment by k7sleeper** [comment]
My Angular2/TypeScript project fails when using SystemJS 0.20.x. As soon as I go back to 0.19.x it's ok, again.

**Comment by unional** [comment]
For `set()`, I can get around it by using an internal flag `__useDefault`:

```ts
const lowercase = require('lower-case')
SystemJS.set('lower-case', SystemJS.newModule({ default: lowercase, __useDefault: true })
```

@guybedford what should be the direction to fix this? can we introduce `SystemJS.newCJSModule()`? Or inside `newModule()` do this wrapping when `__esModule !== true`?

**Comment by aluanhaddad** [comment]
@unional
> Ok, this is a much bigger issue. The way systemjs@0.20 handles commonjs code is not the same way as how TypeScript handles commonjs code.
> My understanding is that systemjs@0.20 follows babel and NodeJS to import commonjs in the default property.
> However, TypeScript does not.

Indeed, from what I understand, there is serious mental dissonance on the issue. While I could be mistaken about this, I believe it stems from a few TypeScript specific factors.

For one TypeScript has directly supported CommonJS modules for much longer than it has supported ES Modules.
Consider the
```ts
import foo = require('bar');
```
syntax that TypeScript has long supported. While this is just syntactic sugar to obtain both types and values from a `require`, it unsurprisingly desugars into
```js
const foo = require('bar');
```
I think that this is relevant because TypeScript seems to have a **_radically_** different conception of what CommonJS is as a module format.

From the Babel point of view, CommonJS is a legacy module format, something to which a direct transliteration (regardless of viability) is not even sought after.

On the other hand, from the TypeScript point of view, CommonJS is a first class module format.
Furthermore, TypeScript allows mixing all forms of module syntax together under `"module": "commonjs"`.
I think this is a major issue.
It does not seem to consider CommonJS a legacy format at all and rather just transliterates the ES Module syntax directly into property assignments on the `exports` object. It also does things like emit multiple `require`s, causing aliasing issues when the same module is imported circularly and or multiple times. It does both of these as a matter of course because it is not trying to perform any semantic mapping when targeting CommonJS with ES Module syntax.

Some recent TypeScript issues that I believe are relevant are
https://github.com/Microsoft/TypeScript/issues/12522
https://github.com/Microsoft/TypeScript/issues/13245

**Comment by unional** [comment]
IMO, TypeScript way provides a better mapping for CommonJS, `import * as X from 'X'` should receive an immutable namespace object and that maps more naturally to `module.exports = ...`.

Moving things and adding `{ default: ... }` seems artificial.

TypeScript team and community should be more active to discuss and work with NodeJS and WHATWG, to help driving TS/JS to unity.  😞

**Comment by aluanhaddad** [comment]
> IMO, TypeScript way provides a better mapping for CommonJS, import * as X from 'X' should receive an immutable namespace object and that maps more naturally to module.exports = ....

Perhaps, I certainly favor immutability as a coding practice, and it seems quite intuitive in the context of modules and shared dependencies, but from reading [002-es6-modules.md#57-cjs-modules-allow-mutation-of-imported-modules](https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md#57-cjs-modules-allow-mutation-of-imported-modules), I get the feeling that mutability is actually desired for backwards compatability with NodeJS.



> TypeScript team and community should be more active to discuss and work with NodeJS and WHATWG, to help driving TS/JS to unity. 😞

I really feel you on this :heart:
Unfortunately, there seems to be a massive trend toward mixing and matching the least compatible aspects of all of these tools, languages, runtimes, and environments.

So many developers seem to be absolutely driven to _writing_ using pure ES Module syntax on the one hand, but to transpiling it to the target module format they have perhaps the least in common with, CommonJS, on the other.

Even the way Babel has approached the issue, which has not been without problems and breaking changes, does not match the fidelity of the Register format.

So we end up with millions of applications written in a syntax that implies a different set of semantics than it would seem to, not because of transpilers themselves, but because of the popularity of CommonJS tools.

TypeScript and Babel should agree on what CommonJS is and what it is not.

When I am using SystemJS, I just use the synthetic default export of every node dependency, eschewing named imports from them entirely. I think it actually works quite well with `--allowSyntheticDefaultImports`, which in spite of your very legitimate concerns I do not believe to be a problem.

I actually think TypeScript should provide the transpilation for this behavior, especially given [node-eps/002-es6-modules.md](https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md).

It seems that this is where things are headed and holding back at this point is really making the problem worse.

To your point, there is indeed a definite lack of unity, but for all that, there is even more inertia and misunderstanding.

**Comment by unional** [comment]
Thanks for pointing to the link. 

Slightly off topic, regarding: https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md#571-es-will-not-honor-reassigning-moduleexports-after-evaluation

Isn't that the exact behavior of this issue? https://github.com/Microsoft/TypeScript/issues/12522

**Comment by unional** [comment]
> To your point, there is indeed a definite lack of unity, but for all that, there is even more inertia and misunderstanding.

That sounds just like the government debt and GDP issue, but that would be way way off topic. 😛

**Comment by aluanhaddad** [comment]
> Slightly off topic, regarding: https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md#571-es-will-not-honor-reassigning-moduleexports-after-evaluation
> 
> Isn't that the exact behavior of this issue? Microsoft/TypeScript#12522

Yes I believe it is the same issue, thanks for pointing that out. I think the expectation of the behavior is wrong somewhere in the chain and I'm not sure where.

And the thing is, these problems are complicated and hard to understand. I came to SystemJS via JSPM migrating from Bower and RequireJS. It took me a long time to really appreciate and develop any understanding of the Register format for what it is.

**Comment by dima-gusyatiner** [comment]
I am essentially a beginner with JSPM and System.
Is this the same issue?
http://stackoverflow.com/questions/42564743/issues-with-es6-import-systemjs-0-20-9-typescript-angular-2-jspm-0-17-0-b

**Comment by unional** [comment]
Seems like it. @guybedford sensei, is this correct? 🌷

**Comment by snarum** [comment]
In my solution (jspm 0.17 beta40, systemjs 0.20.9, typescript 2.2.1) tsconfig.json "module": "commonjs" works (with tons of warnings), but  "module": "system" causes 
````
__zone_symbol__error:
Error: core_1.Injectable is not a function Evaluating http://localhost/web
````
can this be fixed?  should I care?

**Comment by k7sleeper** [comment]
I use SystemJS 0.19.x until this issue is fixed.

**Comment by guybedford** [comment]
The reason for this is that SystemJS 0.19 includes its own configuration for the typescript transpiler.

The fix here would be to add metadata to typescript:

```javascript
System.config({
  meta: {
    'path/to/typescript.js': {
      "exports": "ts"
    }
  }
});
```

Which is exactly what SystemJS 0.19 just includes automatically.

**Comment by bfil** [comment]
@guybedford I've added the config you provided but now I'm getting this error instead: `typescript is not a valid transpiler plugin`.

**Comment by guybedford** [comment]
@bfil you must configure a plugin to load the typescript - see https://github.com/frankwallis/plugin-typescript. This was a deprecation in SystemJS 0.20 (see the release notes at https://github.com/systemjs/systemjs/releases/tag/0.20.0).

**Comment by bfil** [comment]
Yeah I've tried plugin-typescript before, will try again and see what happens.

**Comment by bfil** [comment]
Ok, this is still a no-go for me cause nothing works with `karma-systemjs` (https://github.com/rolaveric/karma-systemjs/issues/90).

I guess I could try `karma-jspm` instead, but I'll leave the misery for another time and roll back to 0.19.. :D

**Comment by snarum** [comment]
does 0.20.10 affect this?

**Comment by Yugloocamai** [comment]
I used k7sleeper's tip, downgrade to 0.19.x and it works, THANK YOU!!!! I was so stuck!
