### ISSUE TITLE
depCache preload to support buffers

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1610]
Currently we're effectively doing a script preload only. This is fine for script-loaded resources, but for resources that would are loaded as buffers (WebAssembly), we do need to have a fetch-based preloader to support depCache.

**Comment by benstevens48** [comment]
Maybe this is related. I'm trying to use depCache and http2 instead of bundling. However, looking at the network tab in chrome, anything in depCache has the status (cancelled) and I can see it's fetched later on. As far as I can tell depCache is not making any difference to the timing of the requests. Also a get a lot of warnings in the console saying 'The resource xxx was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.' But perhaps these warnings are expected.

**Comment by guybedford** [comment]
@benstevens48 it sounds like Chrome may be playing around with their preload defaults there, I hadn't seen that before. Perhaps compare with Chrome Canary to see if it still happens there?

**Comment by thomas-darling** [comment]
@guybedford I'm seeing something similar with this config in SystemJS v0.20.18:
```
depCache:
{
    "http://localhost/1.13.2/en-gb/bundle.dependencies.js":
    [
        "http://localhost/1.13.2/en-gb/bundle.app.js",
        "http://localhost/1.13.2/en-gb/bundle.shared.js"
    ]
}
```

For one thing, I can't seem to get this to do _anything_ without having the full URL's in there.
(we're starting the app with `System.import("aurelia-bootstrapper")`, which live in `bundle.dependencies.js`)

With the full URL's in there, it at least tries to load the dependencies, but ends up with cancelled requests:

![image](https://user-images.githubusercontent.com/6388663/29708979-f9a1931a-898a-11e7-85d4-125726757885.png)

Debugging this further, it looks like it is cancelled because the script tags are injected, and then immediately removed, _before_ Chrome had a chance to start the download.

![image](https://user-images.githubusercontent.com/6388663/29709124-879b1e5c-898b-11e7-8a7a-3cc01674e532.png)

I believe this matches up with this line:
https://github.com/systemjs/systemjs/blob/8afdc93275a376b99cfdd321aaffc94a7ed0b703/src/common.js#L120

If I manually comment out the line with the breakpoint, thus preventing it from removing the script tag, then the files seem to be successfully preloaded - although that doesn't stop it from loading them again later:

![image](https://user-images.githubusercontent.com/6388663/29710032-f887feac-898e-11e7-9a2a-ea5dce4b89fb.png)

I'm really not sure what's going on with those second requests for the same files, but I'm guessing that might be related to path normalization in the `depCache` - something seem to be broken there too :-)

**Comment by guybedford** [comment]
@thomas-darling thanks that seems to have been new behaviour introduced into Chrome. I've added a fix for this in https://github.com/systemjs/systemjs/commit/be6d7a6dd6d5ee99a1ebb154e38b7d23987d59a2.

**Comment by guybedford** [comment]
@michael-simon were you seeing this with 0.20.19? The other thing to check here might be the cross origin settings, as these are supposed to match for preloading to work.

**Comment by guybedford** [comment]
If you do have a look at this further, any help seeing why things might not be matching up would be appreciated, as Chrome keep adjusting their implementation!
