### ISSUE TITLE
window.define = System.amdDefine is reset to undefined

### ISSUE THREAD

**Issue by CNSKnight** [systemjs/systemjs#1633]
I realise this has been hashed over already but I am struggling to resolve.
Reference [this](https://github.com/systemjs/systemjs/issues/1152#issuecomment-194713446)
For some time I have successfully set `window.define = System.amdDefine` in my core *system.js.config.js* script - ie plain ol'JavaScript.
Currently rolled up to 0.20.10, window.define is consistently reset to undefined for modules *required* by other **AMD** modules.

**Comment by guybedford** [comment]
@CNSKnight the global define value is set to undefined purely for the duration of execution of the dependency module. This happens when loading a dependency that is a CommonJS or global module, because otherwise if they include checks for a global define they will execute differently.

The global require is carefully reverted back immediately after the dependency execution.

It may help to set a metadata format for the other AMD modules to be sure they are being detected as AMD:

```js
System.config({
  meta: {
    'path/to/modules/*.js': { format: 'amd' }
  }
});
```

If you see behaviour that isn't in line with the above though let me know too and I can look into it further.

**Comment by CNSKnight** [comment]
Thanks indeed the solution is to ensure meta format: 'amd' for each AMD module
I solved it with this custom extension to System.JS
https://gist.github.com/CNSKnight/1109e9d7514dcd23a39c31bdd8c1450e

**Comment by guybedford** [comment]
Sure, that's an interesting approach, and seems a simpler implementation than the hack in https://github.com/systemjs/systemjs/issues/1616#issuecomment-289268010.
