### ISSUE TITLE
requirejs define equivalent in systemjs?

### ISSUE THREAD

**Issue by eanders-MS** [systemjs/systemjs#1639]
Hello, I'm porting some requirejs code to systemjs, and unsure how to port this:
```javascript
                  define('jquery', [], function () {
                      return jQuery;
                  });
```
What is the SystemJS way to do this?

Thank you.

**Comment by amenadiel** [comment]
what would be the use case? From my understanding, you want to declare a wrapper for the global jQuery object, so you can use said wrapper in other modules like:

```js
define( ['jquery'], function($) {
    $(...);
});
```
Where `jquery` resolves to your wrapper.

In that case, you don't need a named define. Just use the map or paths section in `jspm.config.js` or `config.js` and declare 'jquery' as the name of your module, like:

```js
"map": {
    "jquery":"path/to/file.js"
}
```

Then every module in your project will use your jQuery wrapper whenever they list `jquery` as a dependency in `define`.

If this is your use case, there is a caveat you must consider. A lot of libraries that depend on jquery (say, for example, bootstrap) will try to install their own version of bootstrap instead of using yours, so you might have to resort to create overrides to force them to use your jquery wrapper.

**Comment by ORESoftware** [comment]
I have this in my config:

```js
let builder = new Builder(__dirname, {

  paths: {
    assert: require.resolve('assert'),
    async: require.resolve('async')
  }

});
```

any idea why that wouldn't work? The systemjs-builder cannot find them, I just get this:
```

Build error
{ Error on fetch for assert at file:///Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/assert
        Loading browser-polyfills/systemjs/all-core-and-npm.js
        Error: ENOENT: no such file or directory, open '/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/assert'
    at Error (native)
  originalErr: 
   { Error: ENOENT: no such file or directory, open '/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/assert'
       at Error (native)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/assert' } }

```
