### ISSUE TITLE
SystemJS loading library causes a bunch of deprecation warnings

### ISSUE THREAD

**Issue by JustASquid** [systemjs/systemjs#1651]
It seems that SystemJS touches the libraries it's importing in ways I don't quite understand. In this case, I'm trying to import the [Pixi.js](https://github.com/pixijs/pixi.js) library. However the act of importing the library causes a whole bunch of deprecation warnings to show up:

![Deprecation warnings](https://i.gyazo.com/fc2fce7ff321294d766d12dff9bc86fe.png)

[Here is a simple project showcasing the issue.](https://github.com/JustASquid/test-pixijs-systemjs-deprecation-warnings) It doesn't do anything apart from importing the one library.

Unfortunately I don't know enough to know if this is a SystemJS issue, a transpiler issue, or a PIXI issue. So let me know if someone else is responsible and I'll submit this issue to them instead.

**Comment by guybedford** [comment]
Interesting, the problem here seems to be that Pixi exports `__esModule` then also has has deprecation warnings as setters on named exports.

So SystemJS will read all the export names from the module.exports to populate a SystemJS es module wrapper, due to the __esModule flag being set (allowing eg `import {Stage} from 'pixi.js'`) but in the process we trigger setters which trigger these deprecation warnings.

Put another way - ES modules don't support deprecation warnings for just using an export, exports just always exist, so it's the conversion there behind this.

It may be worth taking this up further with pixi.js.

**Comment by mk-pmb** [comment]
Upstream [claims](https://github.com/pixijs/pixi.js/pull/3952) it's fixed.

**Comment by guybedford** [comment]
@mk-pmb thanks for the update.
