### ISSUE TITLE
SystemJs.import external url

### ISSUE THREAD

**Issue by daniele-zurico** [systemjs/systemjs#1734]
Hello all,
I'm trying to load an angular2 application generated with Webpack from SystemJs. It works perfectly if in webpack I define `libraryTarget: "umd"` but if I don't SystemJs complain: 
`Error: 'angularcli-external' died in status LOADING_SOURCE_CODE: (SystemJS) AMD module http://127.0.0.1:8080/polyfills.bundle.js did not define`

My configuration is quite simple.
The index.html:

```
<script>
	SystemJS.import('main.js');
</script>
```

the Main.js:
```
singleSpa.declareChildApplication('angularcli-external',
() => 
	SystemJS.import('http://127.0.0.1:8080/inline.bundle.js').then(
		()=> SystemJS.import('http://127.0.0.1:8080/polyfills.bundle.js').then(
			() => SystemJS.import('http://127.0.0.1:8080/styles.bundle.js').then(
				()=>SystemJS.import('http://127.0.0.1:8080/vendor.bundle.js').then(
					()=>SystemJS.import('http://127.0.0.1:8080/main.bundle.js')))
			)),
hashPrefix('/angularcli-external')
);
```
there's a way to load these without change the output format?

**Comment by guybedford** [comment]
Is the `polyfills.bundle.js` definitely an AMD file with a `define` statement? Perhaps try changing it to being loaded as a global:

```js
System.config({
  meta: {
    '/polyfills.bundle.js': { format: 'global' }
  }
});
```

**Comment by xino1010** [comment]
Why systemjs inside an angular application created with angular-cli is unabled to load modules from a URL?

**Comment by rivamadan** [comment]
You can't import angular 2+ app into systemJS without changing the output libraryTarget to "umd" or "amd". I'd recommend "amd" though. 

(Btw I'm also using single-spa)

For the inline bundle, I had to add.
```
System.config({
  meta: {
    '/inline.bundle.js': { format: 'global' }
  }
});
```

Currently, the vendor bundle is still in the wrong format (it's in webpack format). I'm pretty sure this is because vendor is defined with the CommonChunkPlugin. I'll update you once I figure out how to get vendor bundle into the correct format. I'm thinking I need to move it to an entry file.

**Comment by Sushil1091Jes** [comment]
I am having same problem , if I try to system.import(http://path-to-my-umd-file.js), says the module cannot be found. I used ng-packagr to create umd. it works fine when the bundle in his local machine but shows in if from server

**Comment by joeldenning** [comment]
@Sushil1091Jes This would be better as a new github issue -- the original issue was talking about systemjs@0.21 but the entire systemjs library has been rewritten in systemjs@>=2 so any previous issues are likely unrelated.

What version of systemjs are you using?

The first thing I would check is if going to `http://path-to-my-umd-file.js/` directly in a browser tab works. Then I would check if that file calls `window.define()` correctly, since that is what SystemJS expects from a UMD module. See https://github.com/systemjs/systemjs/blob/master/src/extras/amd.js#L99

Providing a stacktrace and/or github repo that reproduces the problem would also be of help for a new github issue that you create.

**Comment by Sushil1091Jes** [comment]
> @Sushil1091Jes This would be better as a new github issue -- the original issue was talking about systemjs@0.21 but the entire systemjs library has been rewritten in systemjs@>=2 so any previous issues are likely unrelated.
> 
> What version of systemjs are you using?
> 
> The first thing I would check is if going to `http://path-to-my-umd-file.js/` directly in a browser tab works. Then I would check if that file calls `window.define()` correctly, since that is what SystemJS expects from a UMD module. See https://github.com/systemjs/systemjs/blob/master/src/extras/amd.js#L99
> 
> Providing a stacktrace and/or github repo that reproduces the problem would also be of help for a new github issue that you create.

going to http://path-to-my-umd-file.js/ in browser works. when I am trying to import umd from remote server, system.import() says webpackMissingModule. but it works when i put the umd file inside the project in local machine.

**Comment by santomegonzalo** [comment]
Did anybody solved this problem with single-spa? @rivamadan ?

**Comment by ddydeveloper** [comment]
Hi all. Did anybody try to use not file path but webapi get url? Kind of: 

`SystemJS.import('api/assets/5');`

The REST resource response with the PhysicalFile: 

`	[HttpGet("api/assets/{assetId}")]
		public IActionResult GetPluginAsset(string assetId)
		{
			var path = this.service.GetAssetPath(assetId);
			return PhysicalFile(path, "application/javascript", assetName);
		}`

**Comment by joeldenning** [comment]
As I stated above, a new github issue would be helpful, since this issue is for SystemJS@0.21 which is deprecated and rather different from SystemJS@6.

Importing modules from arbitrary URLs works in SystemJS@6. Loading UMD bundles can be accomplished with either global loading or the AMD extra.
