### ISSUE TITLE
Suggestion to make 'index.js' as default setting for main for packages configs

### ISSUE THREAD

**Issue by Klin88** [systemjs/systemjs#1763]
Please change loadPackageConfigPath to

return configLoader.import(pkgConfigPath)
  .then(function (pkgConfig) {
      **if (!pkgConfig.main && !metadata.packageConfig.main && !metadata.packageConfig.defaultExtension && !metadata.packageConfig.packageConfig && !metadata.packageConfig.map)
          pkgConfig.main = 'index.js';**
    setPkgConfig(metadata.packageConfig, pkgConfig, metadata.packageKey, true, config);
    metadata.packageConfig.configured = true;
  })

**Comment by amenadiel** [comment]
What if you had a `my_app` package located on the same folder as a `my_app.js` script, and somehow you had `.js` as the default extension set somewhere.

I don't know. In node and node tools like rollup you can drop the `js` extension to import a file with a relative location as well as reference a folder as a module instead of using its entrypoint, but in the browser you can't check if file exists then do otherwise if it doesn't (actually you can, with some webserver magic, but it will prolly break something else).

**Comment by amenadiel** [comment]
So the logic would be "if main isn't defined, nor explicitly set in SystemJS.config, then assume the main to be `index.js`"?

**Comment by unional** [comment]
Same issue as https://github.com/systemjs/systemjs/issues/1603
