### ISSUE TITLE
allow official babel options within "System.config({babelOptions: {..}})"

### ISSUE THREAD

**Issue by nimo23** [systemjs/systemjs#1777]
**JSPM Version:** 0.16.53
**Transpiler Plugin(s):** babel

**Details:**

Why not allowing to use the configs from official babel within the property "babel" of system.js:
```

System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ],
    "presets": [
        [
          "env",
          {
            "loose": false,
            "modules": false
          }
        ],
        "react"
      ]
  },
```

Actually, "babelOptions" does not handle official babel options from **.babelrc** (https://babeljs.io/docs/usage/babelrc/). Please provide this.

I use system.js with jspm config file and when running above config the file, it does not work:

`ReferenceError: [BABEL] file://src/index.js: Unknown option: direct.presets`

The same goes for tsconfig by providing "tsconfig"-key.

No need to have a wrapper for a wrapper..user should be allowed to put all the settings there. 

Maybe system.js can also support the key 
`
"tsconfig: "path/to/tsconfig.js" `

`babelConfig: "path/to/.babelrc"`

**Comment by amenadiel** [comment]
The "official" Babel options? It wouldn't make sense to code support for babel parameters only to have them deprecated weeks later. 

When this issue was created the config params would have meant to mimic those passed to babel-preset-es2015 , whereas now you are supposed to use babel-preset-env, but not really because the old one still works.

I wouldn't recommend investing any effort trying to replicate the behavior of a config that in itself is contradictory and overrules itself every so often.

My two cents.
