### ISSUE TITLE
Use bundles and depCache at the same time

### ISSUE THREAD

**Issue by cumuru** [systemjs/systemjs#1790]
Hi,
as of now it doesn‘t seem to be possible to use `bundles` and `depCache` configuration at the same time. The use of the latter excludes the use of the further.
Let‘s assume you have a project (e.g. website project) with two sections with different scripts each. Both are heavy but share a common library. Now what I‘d like to do is create two bundles without the library. But if I do so the library isn‘t fetched until the bundle loads and is parsed.
That‘s where the need to run `depCache` and `bundles` at the same time comes in. Or is there another way to run such a setup?
Thanks, cheers!

**Comment by guybedford** [comment]
It should be possible to do this by having the depcache refer to the bundles themselves, not the modules in the bundles.

Closed as both have been deprecated in SystemJS 2.0, unless you have a specific replication to be fixed in the 0.21 branch.

bundles have been replaced by inline optimizations of Rollup code splitting, and depCache by the fact that those Rollup code splitting workflows automatically inline deep dependencies avoiding the need for depCache.

**Comment by cumuru** [comment]
Hey,
thanks for taking the time to explain!
