### ISSUE TITLE
Batching asset requests together

### ISSUE THREAD

**Issue by ashubham** [systemjs/systemjs#1827]
I want to achieve this:

 - Do not bundle, all modules are separate.
 - Create a dependency graph, during build time and provide it to `depCache`.
    Using `systemjs-builder` ?
 
- Now at runtime, whenever a module is requested say `A`. A batch request is created to load `A` 
    along with all dependencies of `A`.

```javascript
// A.js
import B
import C
...

// B.js
import D
```
`System.import('A')` should create a `/batch?A&B&C&D` and send the request to the static asset server.

Are there any recommendations to achieve the above ?

Now, I also would need a static asset server which understands these batch requests and returns a compressed batched response with all these modules.
Q: Are you aware of an nginx plugin which could do this ?

The above scheme would address the following shortcoming of native ES6 modules:

- Bad Compression ratios (Since server responses are now batch compressed).
- Staggered module loading (automatically populated `depCache` takes care of that).

Thoughts ?

**Comment by amenadiel** [comment]
If you had 3 modules, and all of them depend on, say, jQuery, the current workflow of the app would load and register jQuery before the first module that depends on it. Further modules that need jQuery would use the one already loaded in the registry.

In your approach, you would be dinamically bundling jQuery along each module, which is really inneficient. 

Furthermore, SystemJS wouldn't know what libraries are included in that dynamic bundle, unless that "batch" is generated using `jspm bundle` , which usually takes a few seconds... Which is why the usual approach is to generate the bundle files before or during the deploy stage, and inject the bundle map in jspm config file.

I believe that even if you used jspm to generate said bundles dinamically, you would be relying on your own deterministic method -parsing depcache- to pass required libs in the query string. Said libs might have nested deps on multiple levels.

I don't know man, it doesn't sound like a use case for systemjs / jspm

**Comment by ashubham** [comment]
@amenadiel 
```
If you had 3 modules, and all of them depend on, say, jQuery, the current workflow of the app would load and register jQuery before the first module that depends on it. Further modules that need jQuery would use the one already loaded in the registry.

In your approach, you would be dinamically bundling jQuery along each module, which is really inneficient.
```
SystemJS would only ask for bundles in the `/batch` calls which are not yet present in its cache, so `JQuery` should only be downloaded once.

```
Furthermore, SystemJS wouldn't know what libraries are included in that dynamic bundle, unless that "batch" is generated using jspm bundle , which usually takes a few seconds... Which is why the usual approach is to generate the bundle files before or during the deploy stage, and inject the bundle map in jspm config file.
```
I do not think thats the case, a single file with all the named modules should work. Thats exactly what a bundled module contains, all the modules in a flat file.

 ```
I believe that even if you used jspm to generate said bundles dinamically, you would be relying on your own deterministic method -parsing depcache- to pass required libs in the query string. Said libs might have nested deps on multiple levels.
```
We would generate the dependency graph at build time, so during runtime its basically a graph lookup for the modules, which should be quick in theory `O(D*log N), where N is the number of modules, and D is the average number of dependencies` In our fairly large project we have around 2000 modules .. with each module on an average having 10 deps .. which gives O(10 * log 2000) ~ 33 calculations.

**Comment by guybedford** [comment]
See Rollup code splitting for these workflows.
