### ISSUE TITLE
how to tell system to use a bundled modules file

### ISSUE THREAD

**Issue by alpham8** [systemjs/systemjs#1832]
I'm building an Vue app with TypeScript using SystemJS as the module loader. To do this, I am using systemjs-builder to bundle all the vendor modules together in one file:
```
var Builder = require('systemjs-builder');

var builder = new Builder('./node_modules', './systemjs.config.js');

builder.bundle(
    '[./node_modules/vue/dist/vue.js] + [./node_modules/moment/min/moment-with-locales.js] + [./node_modules/vue-class-component/dist/vue-class-component.js]',
    './dist/vendors.min.js',
    { 'minify': true }
).then(function () {
    console.log('bundling completed!');
});
```

My source TypeScript files are also bundled together in one JS file using this TypeScript Compiler options:
```
{
    "compilerOptions": {
        "allowJs": false,
        "module": "system",
        "moduleResolution": "node",
        "outFile": "dist/bundle.js",
        "target": "es5",
        "typeRoots": [
            "./node_modules/"
        ],
        "types": [
            "moment",
            "vue"
        ],
        "sourceMap": true,
        "watch": false,
        "experimentalDecorators": true
    },
    "include": [
        "src/*.ts"
    ]
}
```

My main Vue instance (App.ts):
```
import Vue from 'vue';
import AdditionalInfos from './AdditonalInfos';

let vm = new Vue({
    el: '#app',
    data: {
        test: 'Hallo World ;-)'
    },
    methods: {

    },
    components: {
        'additional-infos': AdditionalInfos
    }
});
```

My component (AdditionalInfos.ts):
```
import Vue from 'vue';
import Component from 'vue-class-component';

// The @Component decorator indicates the class is a Vue component
@Component({
    // All component options are allowed in here
    template: '<div>Additional Infos:<button @click="onClick">Click!</button></div>',
    name: 'additional-infos'
})
export default class AdditionalInfos extends Vue
{
    // Initial data can be declared as instance properties
    message: string = 'Hello!';

    // Component methods can be declared as instance methods
    onClick(): void
    {
        window.alert(this.message);
    }
}
```

My systemjs.config.js file:
```
(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        bundles: {
            "dist/vendors.min.js": [
                "vue",
                "moment",
                "vue-class-component",
            ],
            "dist/bundle.js": [
                "App",
                "AdditionalInfos"
            ]
        },
        map: {
            "vue": "dist/vendors.min.js",
            "moment": "dist/vendors.min.js",
            "vue-class-component": "dist/vendors.min.js",
            "App": "dist/bundle.js"
        }
    });
})(this);
```

And how I include it all into my HTML page (at the bottom):
```
<script type="text/javascript" src="node_modules/systemjs/dist/system.js"></script>
<script type="text/javascript" src="systemjs.config.js"></script>
<script type="text/javascript" src="dist/vendors.min.js"></script>
<script type="text/javascript" src="dist/bundle.js"></script>
<script type="text/javascript">
    SystemJS.import('App')
        .then((module)=> {
        })
        .catch((error)=> {
            console.error(error);
        });
</script>
```

In the browser console, I see no errors, but Vue doesn't get parsed. So, nothing seems to happen.

**Comment by alpham8** [comment]
@guybedford Why did you close the issue? There is no answer to that question. An answer would be really helpful for the community, not only for me.

**Comment by guybedford** [comment]
@alpham8 it seems like the underlying issue is matching up the modules names with the names in the bundle to the names that are imported. If you look at the `venders.min.js` file you will see various named `System.register('name', ...)` statements for each of the modules. The thing to verify is that the name that is registered matches the name that is being imported for the bundle. Usually the best way to get this right is to start off loading the app as separate files then add the build step second as it requires carefully ensuring the paths match - eg the `node_modules` component is likely being retained. You can also use `System.resolveSync` to ensure this works out.

This is all overly complex and confusing yes, and has tripped up many. That is why SystemJS no longer encourages this approach at all. Instead the entire concept of "named registration" in bundles has been deprecated in SystemJS 2.0 to instead use more efficient and simpler optimization approaches as provided by Rollup code splitting techniques.
