### ISSUE TITLE
Support custom credentials configuration

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1847]
It may be worth supporting a `<script type="system-module">` which can then support the necessary credentials attributes to match browser-style support.

**Comment by xwisdom** [comment]
@guybedford I think this new configuration can work but how about adding a crossOgrin property to the existing package name map configuration?

```html
<script type="systemjs-packagemap">
{
	"packages": {
		"jquery" : {
			"path": "https://cdn.doman.com/scripts",
			"main":"jquery.min.js",
			"crossOrigin": "anonymous"
		}
	}
}
</script>
```
Or you could set crossorgin for the domain:

```html
<script type="systemjs-packagemap">
{
	"crossOrigin" : {
		"https://site.com": "use-credential"
	},
	"packages": {
		...
	}
}
</script>
```

I

**Comment by guybedford** [comment]
@xwisdom as much as possible I would prefer to stick close to what is done via specs. Package name maps is explicitly not providing this kind of "out-of-band" information in it currently, so I think we should try and follow that.

If the script attribute can work, I think that would be preferable. Another option might be `System.import('x', { crossOrigin: 'use-credentials' })`.

**Comment by k-j-kim** [comment]
@guybedford has this been resolved by https://github.com/systemjs/systemjs/pull/2058 as per https://github.com/systemjs/systemjs/pull/2058#issuecomment-544291891? Seems like `crossOrigin` is still hard-coded.

We're seeing an issue in Safari due to https://bugs.webkit.org/show_bug.cgi?id=171566 and it would be nice to be able to configure `crossOrigin` so that we can work around the issue.

I've created a branch on my fork with the proposed approach of `System.import('x', { crossOrigin: 'use-credentials' })`: https://github.com/k-j-kim/systemjs/commit/e571de6f03757a177f99f5cb80b0c34f6b473602.

If you are OK with the idea, I can clean it up and put up a PR. If not, alternatives would be appreciated!

**Comment by joeldenning** [comment]
Hi @k-j-kim - this is now possible via the [createScript hook](https://github.com/systemjs/systemjs/blob/master/docs/hooks.md#createscripturl---htmlscriptelement).

`System.import('x', {crossOrigin: 'use-credentials'})` is no longer what we're planning on for this - `createScript` can do it all

**Comment by k-j-kim** [comment]
cool! thanks @joeldenning
