### ISSUE TITLE
CommonJS loading extra

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1854]
We should be able to turn the previous CommonJS support into an extra.

This is deemed legacy at this point though, so is not a development priority.

**Comment by guybedford** [comment]
The CommonJS code is available at https://github.com/systemjs/systemjs/blob/0.21/src/instantiate.js#L317, extracting into an extra would be straightforward.

**Comment by guybedford** [comment]
I'll gladly create the CommonJS extra for sponsorship (it is a day of work), but still can't prioritise this right now.

**Comment by paulkenney** [comment]
@guybedford @mpfau From what I can tell it seems that babel is the best way to handle this since it generates sourcemaps and can handle both ESM (import/export statements) and CJS in the same file to system/register format. Since babel transformation is implemented in the project https://github.com/systemjs/systemjs-transform-babel, I'm not sure that it should go in this repo since it would be a strange dependency. The workflow that this best supports is developing/debugging locally without bundling first (or in the background), and without sourcemaps this is less useful since errors will not be reported correctly. What isn't really clear is how much functionality you want in SystemJS and what you want in jspm, and some guidance there would help figure out the best way to handle this format.

**Comment by pigcan** [comment]
Any news?

@paulkenney Are you still working on this?

@guybedford I think Sytemjs support for CJS is more important. If you are not happy with this https://github.com/systemjs/systemjs/pull/1901. Could you give some advice I would like to work on it.

**Comment by kshama91** [comment]
Hi,

I am trying to use/integrate the "system.min.js" library into one of my tools.  However upon importing the library for new version i get error indicating global not defined. For older versions i get an error like ";" missing.

May I know what I am missing .?
Thanks.

**Comment by joeldenning** [comment]
> However upon importing the library for new version i get error indicating global not defined

`global` is a variable that is only defined in NodeJS, not the browser. To use it in the browser, you'll need to modify it to reference `window`, `self`, or `this` instead of `global`

**Comment by kshama91** [comment]
Thanks @joeldenning  for the quick reply.. Replaced global with "this" .. currently issue got resolved.

**Comment by jackw** [comment]
@guybedford @joeldenning is there any chance of reopening this issue? I've spent a few hours today trying to wrap my head around how a CommonJS extra could work without Babel and so far I've not had any success. If either of you could give me some pointers on how I should approach translating the old `0.21.x` code into something that works for `6.x.x` I'd really appreciate it.

**Comment by jackw** [comment]
For what it's worth I ended up creating a [systemjs-commonjs-extra](https://github.com/jackw/systemjs-extras/blob/main/packages/systemjs-cjs-extra/src/index.js) to allow the project I'm working in to upgrade to latest systemjs without breaking loading modules. It's based on the old `0.2x.x` code and appears to work fine but if anyone has any pointers for improvement please feel free to leave some feedback. 

>This is deemed legacy at this point though, so is not a development priority.

I made the assumption here that you wouldn't want this extra as part of this repo. If I'm mistaken please let me know and I'll open a PR here to move the extra here.
