### ISSUE TITLE
Node.js support

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1873]
How should 2.0 support executing in Node.js and how should package maps be applied here?

Mostly it's a question of architecture and workflows I think... would be nice to have some driving use cases as I actually don't have any use cases of my own that would need this currently.

**Comment by guybedford** [comment]
@paulkenney if you're still interested in working on this, please let me know. Otherwise I'll gladly include a link to your project in the readme here.

**Comment by paulkenney** [comment]
Thanks for getting back to me. I've continued moving ahead with this working on this feature. My prototype isn't quite ready yet, but I think I can create a PR for it (very) soon once I convert my POC to something usable. One thing that is not implemented yet is packagemaps, but don't think a node-specific implementation is very much work since all the generic logic is already in place. Additionally, I've been working on Node CommonJS support (https://github.com/systemjs/systemjs/issues/1854), and it looks rather straightforward.

**Comment by paulkenney** [comment]
@guybedford As I'm working through some of the differences between the browser platform and Node. 

- fetch()
In the browser, you can use `fetch()` to read the contents of a URL, but in Node that isn't available without a polyfill. I realize that for older browsers, one must also polyfill this functionality, but for Node should probably not use the same polyfill(s) since URLs should be limited to local "file" and not "http/https" URLs to read module files. This brings me to another problem in that the standard fetch polyfills for Node don't handle file URLs. For this reason, I used `fs.readFile`/`fs.readFileSync` to read file content. When I focus on just loading "system" formatted modules without any "extras" this is fine. However, some of the optional modules are written to use `fetch` ("transform.js" in extras, but also "wasm-load" and "import-map" in features), and will not work in a Node environment as they stand. I am concerned that to make this work for Node I will end up having to port everything except the core registry and loader logic, and that doesn't seem like the best idea.

- URL class
In all greenfield browsers (not IE) and Node, the URL class is readily available. However, to handle all URL SystemJS uses `resolveIfNotPlainOrUrl` in "common.js" for resolving import specifiers, and instead of passing around URL objects, strings are used. In the Node-specific code, I have been able to use the URL class to validate specifiers and its constructor is used to reslove relative paths against a base URL. Additionally, the `resolveIfNotPlainOrUrl` function is much more permissive in what it allows and seems to stray a bit from standard URL values. In fact, some of the values are really just regular file paths (host-relative URLs perhaps?) and less structured URIs. Also, I've had to make use of URL.href and the constructor when passing values in/out of the core logic already there. This would be less of an issue if this function (and perhaps other support functions) were exported from the distribution so that it could be used by dynamically loaded (like features/extras) modules not part of the distribution.

- baseUrl
Right now, the baseUrl value is calculated to be the URL to the hosting html file's folder (using `location`). In Node, its a little less clear what the baseUrl should be. We could simply decide that it is the file URL for `process.cwd()`, but that might not desired all the time. Since I cannot use the current `baseUrl` value exported from "common.js", I created my own that is for "cwd". Additionally, to make it easier to use a different location, the NodeLoader class accepts a "baseUrl" parameter to override the default value. I've noticed that other modules make use of this exported value, which makes it tricky to reuse it for Node.

What do we do about this? One idea is to introduce the `file-fetch` package and use it to polyfill fetch much like `isomorphic-fetch` does. Alternatively, instead of relying on a global `fetch` being available, it could be made available in a helper module that is imported where needed (like node-fetch does). Another idea is to add "fetch" to the loader class definition, and for each different environment the relevant fetch implementation is used.

As for URLs, I'm not sure how you feel about replacing `resolveIfNotPlainOrUrl` with a proper URL polyfill. One argument in favor is that it would naturally be in compliance with how specifiers are resolved since it is defined in terms of URLs. A custom implementation runs the risk of missing important edge cases, whereby it can inappropriately allow/restricting values. If it's a question of increasing the size of the distribution, I think it would add less than 10KB to the full distribution. However, this will only really affect IE, and it already requires a polyfill for `fetch`.

For baseUrls, the value could be calculated to take into account that the current environment is eitherNode or the browse. However, I think that the loader itself should probably have `baseUrl` as a property that can be accessed by subclasses or other functions that are dynamically added to its prototype (like in the extras folder).

I've created a PR to show what I have so far, and perhaps the discussion can move there as well.
https://github.com/systemjs/systemjs/pull/1897

**Comment by joeldenning** [comment]
@guybedford I like the API you've proposed and am interested in either PR'ing for this myself or seeing if someone in the single-spa core team is interested in doing it.

Implementation for this seems to mostly involve creation of a new `instantiate` implementation. Before we work on this, can you comment on the following implementation approach?

1. Hook instantiate
2. If `url` is to remote address, fetch source code
3. `vm.runInContext(code)`?
4. Resolve instantiate promise with return value of `System.getRegister()`, like normal

Is this what you're thinking it would look like?

**Comment by guybedford** [comment]
@joeldenning yes it is based primarily on an instantiate hook running System.getRegister like normal. It would be great to get some contributions to this indeed.

* Landing https://github.com/systemjs/systemjs/pull/2058, such that the implementation can use `System.fetch` and `System.shouldFetch` in Node.js to avoid fetching in instantiate. This way users can implement fetch hooks if they want.
* Supporting URL fetching in Node.js has the same problems as Node.js implementing `fetch()` - ie agent sharing, cache sharing, connection details etc. There isn't a single solution to this so I would prefer a URL fetching feature to be a separate extension which hooks the `System.fetch`.
* There is no need to create a custom `vm` context - SystemJS runs in the same isolate as the rest of the current environment. SystemJS doesn't currently support isolation at all as a feature and if we want that that should be considered from the ground up and not just tacked on here. Just `(0, eval)` is absolutely fine.

Also see https://github.com/ModuleLoader/node-es-module-loader/blob/master/src/node-es-module-loader.js#L77 for inspiration which does a lot of this.
