### ISSUE TITLE
Error shallowed by s.js

### ISSUE THREAD

**Issue by dmail** [systemjs/systemjs#1924]
When a module throw an error it is ignored.
You can reproduce in the following fiddle: https://jsfiddle.net/xkdwshay/

It seems `dist/s.js` is missing something that is present in `dist/system.js`.

See https://github.com/systemjs/systemjs/blob/7363bccee2f2515d92212cbd4fda21afe512cbd4/dist/system.js#L439-L442

https://github.com/systemjs/systemjs/blob/7363bccee2f2515d92212cbd4fda21afe512cbd4/dist/s.js#L337

**Comment by guybedford** [comment]
Thanks, yes it seems this is a bug I just introduced in the last release in https://github.com/systemjs/systemjs/blob/master/src/system-core.js#L280. I think it can just be changed to `});` entirely, leaving out the catch handler.

Ideally it needs a test though as well. If you feel like posting a PR that would be amazing, otherwise I will get to this soon.

**Comment by dmail** [comment]
The pr in itself is a one liner but it seems there is already a test for that here:
https://github.com/systemjs/systemjs/blob/7363bccee2f2515d92212cbd4fda21afe512cbd4/test/browser/core.js#L96-L105

But it does not seems to be runned by npm test ?

**Comment by guybedford** [comment]
I think the error will only show for the async execution case.

**Comment by guybedford** [comment]
Fixed and released in 3.1.2. Please let me know if you're still seeing this.
