### ISSUE TITLE
Not compatible with Angular

### ISSUE THREAD

**Issue by FrisoDenijs** [systemjs/systemjs#1940]
I've been trying to get system.js to work with Angular, but after failing to follow several examples, I found on stackoverflow that newer versions aren't compatible. See https://stackoverflow.com/a/53702437/1984657

Is there a workaround for this so I can keep using the latest versions?

Examples from my repo, that don't work with the latest version, but do work with 0.21.5:
- https://github.com/FrisoDenijs/pluggable-angular-example/blob/master/core/src/main.ts
- https://github.com/FrisoDenijs/pluggable-angular-example/blob/master/core/src/app/app.component.ts

**Comment by joeldenning** [comment]
With systemjs@>=2, there is no longer a `window.SystemJS` global variable. Instead, there is only a `window.System` variable.

To get things working with Angular, you'll need to either change your code to `window.System.import()` or to move to `System.import()` but then [modify your webpack config]() as explained in the Readme. The change to the webpack config is so that webpack does not interpret `System.import()` to mean a [webpack code split](https://webpack.js.org/guides/code-splitting/#root).

Also just as a sidenote, here's an example repo of Angular 7 with SystemJS@3: https://github.com/joeldenning/coexisting-angular-microfrontends

**Comment by FrisoDenijs** [comment]
Thank you very much. I can make it work like that, so I'll close the issue
