### ISSUE TITLE
What do you think of jsenv, my project based on systemjs?

### ISSUE THREAD

**Issue by dmail** [systemjs/systemjs#1948]
Hello,

First, thank for the work on systemjs. System register format, existence of the babel plugin and so on made my own project possible.

I would like to introduce you something I have been working on for a moment.
In summary, it's a server dynamically transforming files into code that can be executed inside a browser or node. Here are two link that are files using systemjs. I hope it may give you a great overview of what I'm doing.

[create-browser-system.js](https://github.com/jsenv/jsenv-core/blob/0b6c2b1a664d8227164629045252672a8063f8d2/src/browser-platform-service/browser-platform/create-browser-system.js#L16)
[create-node-system.js](https://github.com/jsenv/jsenv-core/blob/0b6c2b1a664d8227164629045252672a8063f8d2/src/node-platform-service/node-platform/create-node-system.js#L24)

Link to jsenv project itself: https://github.com/jsenv/jsenv-core.

You might be interested to discuss about `importMap` used to resolve node_modules inside browsers or introduction of `import.meta.require` for node. 

Please feel free to give me your feedback about this project, any comment or suggestion would be very welcome 🙂

**Comment by joeldenning** [comment]
@dmail I took a quick look at this and wasn't able to understand what jsenv-core or create-browser-system were doing in the short time that I took to read it over.

It looks like you've put a fair amount of work into jsenv-core (1,200 commits). My first piece of feedback to have documentation for your project. Or even just a simple description of what it is, how to install it, and basic usage. The following statement didn't help me understand what your project does: "jsenv-core helps to run your JavaScript in well-known scenarios." That statement is vague to me.

In your readme you say:
> jsenv provides a solution to turn any JavaScript file into an entry point.

At first reading of this, it sounds like any other bundler, which all let you configure the entry point for your bundle. I think I'm missing the whole point of your project because there isn't a description of what it is.

> In summary, it's a server dynamically transforming files into code that can be executed inside a browser or node.

That sounds like a bundler/compiler. Looks like your project uses rollup and babel, so I'm not sure what your project gives beyond what they already can do.

Taking a quick look at create-browser-system.js and create-node-system.js, looks like you're implementing your own functions for `resolve`, `instantiate`, etc. Without looking deeper into it, I don't really understand why.

**Comment by dmail** [comment]
Thanks for taking the time to write this valuable feedback. 
I agree with what you said, several points trully need to be explained.
I'll work to bring a response to the points you've raised.
Coming back to you shortly.

**Comment by dmail** [comment]
Hi @joeldenning,

> I'm missing the whole point of your project because there isn't a description of what it is.

I would describe jsenv as a developper tool providing a unified workflow to write JavaScript for the web or node.js or both at the same time. Obtaining this using babel, rollup and so on separately would be a lot of code and setup. Such setup would be harder to reuse and maintain across different repositories.

For the longer version I have updated jsenv readme with more informations.
— see [jsenv/jsenv-core#readme.md](https://github.com/jsenv/jsenv-core/blob/master/README.md)

> looks like you're implementing your own functions for resolve, instantiate, etc. Without looking deeper into it, I don't really understand why.

**Why reimplementing `resolve`**

Inside a browser, systemjs is searching for importMap thansk to

```html
<script type="systemjs-importmap" src="importMap.json"></script>
```

Inside node.js, I had no way to tell systemjs where to look for an importMap file.

**Why reimplementing `instantiate`**

1. Wanted to use `XMLHttpRequest` to load a module instead of `<script>` tag because `<script>` doesn't let you known server response status/body when it is not `200`.
   I need server response status in case module contains syntax error. In that case server cannot parse module source but client wants to know that information, to display an error message for instance.

2. Be able to import native node module

```js
import { readFile } from "fs"
```

3. Be able to import `.json` files

**Comment by joeldenning** [comment]
👍 now I'm getting it more. Looks like you've done some cool stuff here. I haven't delved as much into isomorphic javascript that does module loading, but if i need to in the future I'll check out jsenv as an option.

**Comment by guybedford** [comment]
@dmail great to see the project. I've included this in a new community projects section at https://github.com/systemjs/systemjs/pull/1994.
