### ISSUE TITLE
Handling of new non-JS module types: JSON, CSS, HTML

### ISSUE THREAD

**Issue by justinfagnani** [systemjs/systemjs#1987]
Is there a plan for handling non-JS module types? As JSON, CSS, and HTML modules become standardized and implemented, I think it'd be very useful for SystemJS to allow for `import styles from './styles.css'`, etc.

**Comment by joeldenning** [comment]
JSON modules are supported by systemjs@>=4.0.0. It's not spec compliant because it relies on the file extension to know to treat it as a json module vs js module. See https://github.com/systemjs/systemjs/pull/1950

CSS modules recently advanced to a later stage in the spec process, right? I don't think there has been discussion about implementing those. If done, would likely be via an extra instead of in systemjs core since it would likely include in-browser compiling of the css.

I've never heard of HTML modules. Are you referring to the dead HTML imports spec? Or something else?

**Comment by guybedford** [comment]
@justinfagnani thanks for bringing this up and agreed, and I'd be happy to provide a custom "extra" (SystemJS core supported plugin), for CSS modules.

I've created a tracking issue in https://github.com/systemjs/systemjs/issues/1991.

If HTML modules are ready for experimental implementations too we can also look at that.

In due course [es-module-shims](https://github.com/guybedford/es-module-shims/) would also add support for these (it already inludes JSON too), but that project aims to be more spec compatible so it would be nicer to see more stability first.

Happy to go ahead and ship a CSS modules implementation though!

Let's move this over to tracking issues - https://github.com/systemjs/systemjs/issues/1991, https://github.com/systemjs/systemjs/issues/1992.
