### ISSUE TITLE
CSS modules support

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1991]
Now that the CSS modules specification has made some good progress it would be worthwhile to provide an implementation in SystemJS through an extra.

@justinfagnani is there a polyfill approach that can work for CSS modules to get the correct stylesheet load and binding behaviour? Or would this require some trick such as creating a temporary shadow dom or iframe to get the reference from?

Would value your thoughts on the implementation approach.

**Comment by joeldenning** [comment]
Is https://github.com/w3c/webcomponents/issues/759 the best reference for the CSS modules specification? I had trouble finding an actual spec for it in my google searching. I am a long time user of Glen Maddern's CSS Modules spec, including things like `:global()` and `:local()`, but my understanding is the browser spec for css modules is fairly different. We need to see that spec to make sure we are faithful to it.

I think an implementation might start here - https://github.com/systemjs/systemjs/blob/21933c378d2750e187699c5e7be2aea8eab57833/src/features/script-load.js#L14-L22

Taking a look at the w3c issue I linked to above, the first implementation decision that comes to mind is if we have to rely on constructable stylesheets or not, which from what I can tell come with controversy. From the reading I did, Safari was against them -- specifically the `adoptedStylesheets` property in shadow roots.

Could we get away with constructing the stylesheets without relying on those? Doing so would be desirable in my opinion, since the constructable stylesheets spec is controversial and not implemented by any browsers. Here's an approach (that might not work) for working around constructable stylesheets:

```js
System.register([], function(_export) {
  return {
    execute: function() {
      const styleEl = Object.assign(document.createElement('style'), {textContent: theRawCss, title: 'systemjs-cssmodule1'})
      document.body.appendChild(styleEl)
      let styleSheet
      for (var i = 0; i < document.styleSheets.length; i++) {
        if (document.styleSheets[i].title === 'systemjs-cssmodule1') {
          styleSheet = document.styleSheets[i]
          // to try to make the css disabled/not apply
         styleSheet.disabled = true // or styleEl.parentNode.removeChild(styleEl)
          _export('default', styleSheet)
        }
      }
    }
  }
})

```

**Comment by justinfagnani** [comment]
Here's the explainer: https://github.com/w3c/webcomponents/blob/gh-pages/proposals/css-modules-v1-explainer.md

I think the best way to polyfill this will be to rely on Constructible Stylesheets and let a polyfill take over from there.

So styles.css:
```css
div { color: red; }
```

transforms to:

```js
const stylesheet = new CSSStyleSheet();
stylesheet.replaceSync(`
div { color: red; }
`);
export default stylesheet;
```

It's important to implement CSS Modules this way for interop. The "constructible" part of Constructible Stylesheets is _not_ controversial in any way. ie, `new CSSStyleSheet()` and `replaceSync()` are received well. And Constructible Stylesheets _is_ implemented in Chromium browsers. We're using it already in our libraries.

One reason to prefer relying on a polyfill is that polyfilled APIs that receive constructed CSSStyleSheet objects may need some out-of-band data not included in the standard CSSStyleSheet API (like the original CSS text). It's best to leave this up to the polyfill, since it'll implement both the production of the CSSStyleSheet and the consumption of it (`adoptedStyleSHeets` or otherwise).

**Comment by joeldenning** [comment]
👍 thanks for the clarification. If relying on constructible stylesheets as you suggest, this does not look that hard to implement. Might even be able to put together a PR for it today.
