### ISSUE TITLE
HTML modules support

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1992]
Tracking issue for support of an HTML modules extra (https://github.com/w3c/webcomponents/issues/645).

**Comment by joeldenning** [comment]
This one should be rather easy to implement I think. Implementation would be similar to the json modules implementation: https://github.com/systemjs/systemjs/blob/21933c378d2750e187699c5e7be2aea8eab57833/src/features/script-load.js#L14-L22

```js
  if (url.substr(-5) === '.html') {
    return fetch(url).then(function (resp) {
      return resp.text();
    }).then(function (source) {
      return [[], function(_export) {
        return {execute: function() {_export('default', source)}};
      }];
    });
  }
```

**Comment by guybedford** [comment]
@joeldenning not quite - the result should be an instance of an HTML, roughly like HTML imports I believe.

**Comment by joeldenning** [comment]
Hmm I just read that issue and it is not clear to me what was decided on in the two year discussion. 

Maybe the chrome implementation would be what we’d reference? https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/ewfRSdqcOd8/w_Fr6rJ3DQAJ

**Comment by joeldenning** [comment]
This appears to be the best explanation:

https://github.com/w3c/webcomponents/blob/gh-pages/proposals/html-modules-explainer.md

**Comment by joeldenning** [comment]
Here's my understanding of the changes needed to SystemJS to make this possible:

1. Add support for `import.meta.document`. In SystemJS terms, this will be `_context.meta.document` (see [here](https://github.com/systemjs/systemjs/blob/master/docs/system-register.md#format-definition)).
2. Capture all exports from all js modules inside of the HTML module. Combine them and export them as one module. Initial thoughts about an implementation are to provide a custom`_export` function for HTML modules that do that. See [here](https://github.com/systemjs/systemjs/blob/master/src/extras/named-exports.js#L29) for what I mean by "custom _export function". Also might need to override `System.register` itself

**Comment by guybedford** [comment]
@justinfagnani any chance of an update on the points you've raised here? We are hoping to release SystemJS v6 soon, so your feedback on how to implement and communicate HTML modules would help a lot to ensure we don't set any misconceptions into play.

**Comment by viT-1** [comment]
`import template from './template.html';`
is released in 6.0?

I'm not found #2002 in [changelog](https://github.com/systemjs/systemjs/blob/master/CHANGELOG.md)

**Comment by joeldenning** [comment]
HTML modules are not supported in any released version of systemjs. Perhaps your `template.html` file is actually returning a javascript or json module?

**Comment by viT-1** [comment]
@joeldenning No. My template.html is HTML only. Therefore I'm foced to use [gulp-html-to-js](https://github.com/Mitranim/gulp-html-to-js) for importing html to js/ts file as string.

**Comment by joeldenning** [comment]
Are you sure that `import template from './template.html';` is an in-browser import instead of a build-time import?

Vue's webpack config is likely bundling that down to a javascript file before it hits the browser. SystemJS only deals with in-browser modules.

**Comment by viT-1** [comment]
@joeldenning Of cause `import template from './template.html';` used only for
- jest with ```
transform: {
		'.*?\\.html$': 'html-loader-jest',
	},
```
- build time with Gulp task which added `./template.html.js` file with string template exported by 'gulp-html-to-js' package

If SystemJS can import html templates as strings it will increase attractiveness because we able to avoid overingeneering with webpack/rollup bundling and use tsc outFile bundling.

**Comment by joeldenning** [comment]
@viT-1 I don't understand your last comment very well. You didn't answer my question from my previous comment. To me it sounds like you're doing build-time modules and module mocking with jest. Neither of those are in-browser modules with SystemJS.

SystemJS does not have support for HTML modules (pending #2011). We're holding off on merging #2011 because the fate of json, css, and html modules in uncertain. At a standards body conference for browsers, they found a security problem that is currently being discussed in a separate github thread.

**Comment by guybedford** [comment]
Closing as activity on a specification here has stalled.
