### ISSUE TITLE
Comprehensive AMD named define compatibility

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#2019]
So it seems to be coming up quite a bit that people still want to follow the AMD patterns of named defines existing in a relative module name space to a baseURL.

The current extras model is based on providing the primitives in a logical way, but users are struggling to combine these primitives to get a full workflow experience that exactly matches AMD named define primitives.

For this reason it could be worth providing a third-party project that ensures full AMD compatibility including baseURL support and js extension adding.

Any volunteers to work on such a thing?

**Comment by thiscantbeserious** [comment]
We've already had a short dicussion in issue #1988 in regards to it, also see others like #1907 (specifically mentioned that one, since I do ran into similiar issues).

I've had a look how it was handled in SystemJS 0.21:

https://github.com/systemjs/systemjs/blob/0.21/src/format-helpers.js

Seems like troublesome and exactly why our team is looking to move away from it (I mean the AMD "Standard").  

The issue in doing so are more or less exactly external depedendencies (libraries), like outlined in the issue above, that many of us can't easily replace yet (either since there are no alternatives, or because the timeframe is to short, or the friction is to high to do it in one step - or all of it).

The new architecture of SystemJS 2 and above doesn't make that easier either. I tried to clean up the AMD-Extra at first, to get an idea how it works and fell over my own feet since the execution order is important and the way how scopes are handled are fragile (guess I'm spoiled by ESNext).

I'll have a look into it (in the upcoming days and weeks) if nobody else stepped up doing so - since it's a showstopper for our project and frankly speaking there's currently nothing better then SystemJS in its very specific role as a dynamic module loader.

------
By the way - did you close an issue regards to discussion of how to tackle configurations per se? 

I remember participating in discussion to one, but can't find it anymore. I do see that as an important issue as well, the might be needed to be solved before the community can/will dive in.
