### ISSUE TITLE
Still having problems with named register

### ISSUE THREAD

**Issue by khangiskhan** [systemjs/systemjs#2026]
Using latest systemjs@6.1.0, I think https://github.com/systemjs/systemjs/pull/1984/files should have fixed this, but still having broken scenario:

When loading a module, named dependencies are not loading unless they are in System.register format

```
{
   imports: {
     "one": "/one.js"
   }
}
```

```
define('one', ['preload'], function(preload) {
   console.log('hello ' + preload);
})
```

```
System.register('preload', [], function(exports) {
  return {
    execute: function() {
      exports("world", "world")
    }
  }
})
System.import('one'); // hello world
```

```
define('preload', ['exports'], function(exports){ return exports.world = "world"
define('one', ['preload'], function(preload) {
   console.log('hello' + preload); // hello undefined
})
```

Additionally I'm seeing weird behavior with `system.has()`:

```
// both formats fail System.has
System.import('one').then(function() {
   System.has('one'); // false
   System.has("preload") // false
})
```

See codepen: https://codepen.io/khangiskhan/project/editor/AzNdxp

**Comment by joeldenning** [comment]
Hi @khangiskhan,

Thanks for the Codepen and the detailed description. The problem is a bug in your preload_dep_amd.js file:

```js
define('preload', ['exports'], function(exports){
  return exports.world = 'world';  
});
```

According to the AMD spec, there are two ways to specify an AMD module's exports:
1. returning a value from the defined function.
2. Modifying the `exports` object that is passed into the function.

In your code, you are doing both, all in one line: `return exports.world = 'world'`. Which is unusual -- normally you pick either Option 1 or Option 2 for defining your exports. Because you are doing both, systemjs has to choose which export to honor, and the following two lines of code show that systemjs ends up honoring the returned value instead of the exports object. https://github.com/systemjs/systemjs/blob/c08c92dcdb0850b999b6cf4c180702e01ae8b04d/src/extras/amd.js#L56-L57

The return value of your function is the string `'world'`, since `exports.world = 'world'` is a javascript expression that evaluates to the string `'world'`. And so your entire module is exported as the string `world`, which does not have a sub property called `world`.

To fix your problem, simply delete the `return` keyword. I have verified that this fixes it:

```js
define('preload', ['exports'], function(exports){
  exports.world = 'world';  
});
```

> Additionally I'm seeing weird behavior with system.has():

You need to call `System.has(System.resolve('one'))`, and then it will return `true`. The reason for this is that `System.has(id)` checks the module registry for an `id`. The `id` is almost always a full blown url -- the one calculated when you do `System.resolve(id)`. The reason that you don't have to call `System.resolve('preload')` is because the named-register extra allows you to put whatever `id` you want into the module registry and it doesn't require it to be a full url.

**Comment by khangiskhan** [comment]
> Hi @khangiskhan,
> 
> Thanks for the Codepen and the detailed description. The problem is a bug in your preload_dep_amd.js file:
> 
> ```js
> define('preload', ['exports'], function(exports){
>   return exports.world = 'world';  
> });
> ```
> 
> According to the AMD spec, there are two ways to specify an AMD module's exports:
> 
> 1. returning a value from the defined function.
> 2. Modifying the `exports` object that is passed into the function.
> 
> In your code, you are doing both, all in one line: `return exports.world = 'world'`. Which is unusual -- normally you pick either Option 1 or Option 2 for defining your exports. Because you are doing both, systemjs has to choose which export to honor, and the following two lines of code show that systemjs ends up honoring the returned value instead of the exports object.
> 
> https://github.com/systemjs/systemjs/blob/c08c92dcdb0850b999b6cf4c180702e01ae8b04d/src/extras/amd.js#L56-L57
> 
> The return value of your function is the string `'world'`, since `exports.world = 'world'` is a javascript expression that evaluates to the string `'world'`. And so your entire module is exported as the string `world`, which does not have a sub property called `world`.
> 
> To fix your problem, simply delete the `return` keyword. I have verified that this fixes it:
> 
> ```js
> define('preload', ['exports'], function(exports){
>   exports.world = 'world';  
> });
> ```
> 
> > Additionally I'm seeing weird behavior with system.has():
> 
> You need to call `System.has(System.resolve('one'))`, and then it will return `true`. The reason for this is that `System.has(id)` checks the module registry for an `id`. The `id` is almost always a full blown url -- the one calculated when you do `System.resolve(id)`. The reason that you don't have to call `System.resolve('preload')` is because the named-register extra allows you to put whatever `id` you want into the module registry and it doesn't require it to be a full url.

Thanks @joeldenning for your expertise!  Thanks for finding the bug and clarifying `System.has`

Looks like that bug was just masking my real issue, which is that System.import() for a single named *AMD* module is not working...details here: https://github.com/systemjs/systemjs/pull/1984#issuecomment-531398651

**Comment by khangiskhan** [comment]
I wasn't able to reproduce the issue on code-pen, so it must be a bug in my local.  Will track and down and update here.

**Comment by khangiskhan** [comment]
Update:

I was able to reproduce some more weird behavior in code-pen: https://codepen.io/khangiskhan/project/editor/AzNdxp#

I tested out different AMD module types, both named and unnamed, with and without dependencies.  

A few things I noticed:

1) The order I imported unrelated modules in changed behavior
2) Preloading a module changed behavior
3) Importing 
4) System.has(System.resolve(id)) doesn't always work (expected since the registry doesn't appear to be working properly in above scenarios.

**Comment by joeldenning** [comment]
Reopening so we look at this

**Comment by joeldenning** [comment]
I created #2029 which fixes (1) and (2) above. I didn't look into (3) as much, so idk what is happening there.

**Comment by khangiskhan** [comment]
> I created #2029 which fixes (1) and (2) above. I didn't look into (3) as much, so idk what is happening there.

Thanks Joel! Confirmed it fixed (1) and (2) for me.

I debugged through the `System.has()` bug (The same bug applies for `System.get()`):

The root of the problem is that before a module is imported `System.resolve('named_module')` resolves to a URL, and after it is imported, it resolves to the ID itself.

A named module loaded through import-map will get stored in the module registry (not the registerRegistry) as a URL, so when you do `System.has("named_module")`, it won't work, you need the resolved URL.  

```javascript
{
   imports: {
      "named_module": "/named_module.js"
  }
}
```

```javascript
console.log(System.resolve('named_module')); // http://localhost/named_module.js

await System.import('named_module');

// System.resolve now returns the module from the registerRegistry
const resolved = System.resolve('named_module'); // changed to "named_module"
console.log(System.has(resolved)); // false
console.log(System.get(resolved)); // undefined
```

I see 2 potential fixes:

1. Remove this check in System.resolve:
```
    if (id in this.registerRegistry)
      return id;
```

2. Store named modules in the module registry with the name

**Comment by joeldenning** [comment]
@khangiskhan want to create a separate bug for the System.has problem?

**Comment by khangiskhan** [comment]
> @khangiskhan could you create a separate issue for the System.has problem?

Created https://github.com/systemjs/systemjs/issues/2030
