### ISSUE TITLE
Why does amd extra populate all exports of the original amd module into default?

### ISSUE THREAD

**Issue by shrinktofit** [systemjs/systemjs#2032]
https://github.com/systemjs/systemjs/blob/82a829e006298b175dfa94452e27cd099598a7c3/src/extras/amd.js#L52-L60

I cannot find related specification at [AMD Wiki](https://github.com/amdjs/amdjs-api/wiki/AMD).

**Comment by joeldenning** [comment]
Here's some background:

- The AMD specification does not have the concept of multiple exports. Only a single export.
- The single export may be any kind of value -- an object, function, number, string, etc.
- The ESM specification calls for all modules being an object with named and default exports.

Taking these things into account, the SystemJS implementation of AMD has a choice to make -- should it support AMD modules whose single export is a function. The choice made was to yes support it. And the implementation chosen was to make the exported value the ESM's "default" export.

If having to do `.default` is annoying, feel free to check out the use-default extra. Also, not that if your application is only AMD modules that you won't have to worry about doing `.default` because that is already done for AMD dependencies.

**Comment by joeldenning** [comment]
Closed this because I think I've answered the question -- feel free to reopen or comment further.
