### ISSUE TITLE
use default extra is misleading?

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#2045]
Users getting `{ default }` for their import might think the use default extra is a solution to this, when it only applies to `System.import`.

Perhaps this extra introduces more confusion than it solves? It could be worth deprecating and turning into a third-party extension.

**Comment by joeldenning** [comment]
I'd prefer to make the use-default extra apply to linked dependencies, too, instead of just to System.import()'ed dependencies. The use case it was intended for was one where AMD modules are dependencies of System.register modules. However, it doesn't even solve that use case because the System.register module is given `{default: {...}, __useDefault: true}` as its dependency even though it would prefer just being given the default value.

Here's the example use case that I think use-default should solve: https://github.com/joeldenning/systemjs-use-default-use-case/blob/master/README.md

The origin of the use case is trying to get React working as an AMD module that can be used from a webpack/rollup bundle that is compiled to System.register format. Right now it's only possible with the named-exports extra, but could be possible with just the use-default extra, I think.

**Comment by guybedford** [comment]
Having use-default apply in ES module linkage is not a behaviour I would include in core as it breaks the specified module semantics.

This is perhaps another good argument to move this out to userland entirely.

**Comment by guybedford** [comment]
Created https://github.com/systemjs/systemjs/pull/2052 to docs deprecate, feedback welcome.

**Comment by frehner** [comment]
hm, so, as someone that needed the `use-default` extra in a previous project, what would be the path forward then if it's deprecated?

**Comment by guybedford** [comment]
It can still work fine as a plugin, we could move it into its own repo or someone could choose to maintain it and we could include it in the list from the readme.

The question is only whether it should be a core extra or not.

**Comment by frehner** [comment]
For clarity sake, then, I would still need to use use-default but it wouldn’t be an official plugin?

Because I’m not sure I can get away from using AMD modules for everything for a long time - trying to get libraries like React, lodash, etc to add additional bundles is taking forever.

**Comment by guybedford** [comment]
Right, but the use-default plugin only makes `System.import` calls return the default, it's really not a big loss surely?

**Comment by frehner** [comment]
ah, jeez, ok I can't believe I already forgot about the conversation we had here https://github.com/systemjs/systemjs/issues/1977

so yeah, I think I'm actually good without the use-default extra then :D 

thanks for your patience.

**Comment by guybedford** [comment]
No problem at all, have to work through these things - I think it's just another sign that it is misleading. Will close this as resolved then, to deprecate it in due course.

**Comment by frehner** [comment]
So, as a followup - I tried removing use-default but then discovered / remembered that there are a ton of dynamic imports throughout the app, and it breaks. (We really only have one app that gets System.imported() to bootstrap everything, so I thought we would be ok at the time.)

So I'm actually kind of back on the idea that it shouldn't be removed from the official systemjs ecosystem. 🤷‍♀ 

I'll still be ok if it is removed, though. Just as long as it's still available.

**Comment by joeldenning** [comment]
See related https://github.com/systemjs/systemjs/issues/2064 where @shrinktofit encountered the specific situation where use-default helps (if I interpreted his original comment correctly 😄).

I think it might be worth trying to salvage use-default, perhaps with better docs, rather than remove it entirely.

**Comment by guybedford** [comment]
As of https://github.com/systemjs/systemjs/pull/2257 this is full deprecated for removal in the next major.
