### ISSUE TITLE
ES Modules and CommonJS?

### ISSUE THREAD

**Issue by chase-moskal** [systemjs/systemjs#2055]
hello friends, i'm a huge fan!

in the past, i think i've seen systemjs advertised as a "universal module loader" that is supposedly capable of seamlessly loading modern es modules and commonjs dependencies alike (on the clientside)

is this something that systemjs can do today?

i'm currently using es-module-shims to load my application's es module, but i'm running into CJS dependencies that are bumming me out -- i've even browserify'd auth0/jsonwebtoken and exported the bits i need in ESM -- but i'm hoping for a more sustainable workflow

what's the recommended pathway to deal with CJS dependencies these days, much preferably something that works clientside without any bundling step

cheers!

:wave: chase

**Comment by joeldenning** [comment]
Hi Chase, good questions. I'd recommend checking out the [Module Types documentation](https://github.com/systemjs/systemjs/blob/master/docs/module-types.md) to see what SystemJS supports.

Note that SystemJS@>=1 only supports ES modules only by using a [Transform Extra](https://github.com/systemjs/systemjs#extras) that does an in-browser compilation of ES modules to [System.register format](https://github.com/systemjs/systemjs/blob/master/docs/system-register.md). Note that the reason ES modules require compilation is that both SystemJS is that the browser and SystemJS maintain a module registry, and the browser's module registry isn't currently pluggable/iterable.

The CJS format is not supported by SystemJS@>=1 without creating your own extra that implements some [systemjs hooks](https://github.com/systemjs/systemjs/blob/master/docs/hooks.md) to make that possible. Note that the tricky part of CJS support is the dynamic and synchronous nature of the `require()` function. SystemJS@<=0.21 supported CJS by downloading the code as a string and running a regular expression on it to find all the `require()` calls so that it could download the dependency modules before execution. That has some obvious performance implications and is something I would consider out of scope for SystemJS@>=6.

What I'd recommend doing is using rollup or webpack to bundle your code and cjs dependencies into a System.register format. And then loading that bundle via SystemJS. Alternatively, you can call [System.set](https://github.com/systemjs/systemjs/blob/master/docs/api.md#systemsetid-module---module) manually with the CJS modules to make them available to the rest of the modules that are in the systemjs registry.

I'm closing this issue with this comment since I think I've answered your questions and given you some options about how to approach things. But feel free to comment further with more discussion or reopen.

**Comment by guybedford** [comment]
> what's the recommended pathway to deal with CJS dependencies these days, much preferably something that works clientside without any bundling step

`import m from 'https://dev.jspm.io/[pkgname]'` is actually the workflow I'd recommend for this these days. It does all the right stuff you'd expect from a bundler to support the packages, but in a way that can be imported from ES modules.

I'm working on optimizing the performance of this server further. I think it's likely the best bet for an easy backwards compat workflow with modern modules without bundling, switching to bundling where necessary.

Once the whole ecosystem of packages is ES modules we won't have these problems anymore and that CDN approach is then no longer necessary.

Note that currently jspm.org will convert CJS to ES modules on install, allowing for full unbuilt dev. That is installing and running it today will provide your workflow as well. But it does still require an import maps generation step.
