### ISSUE TITLE
Problem with relative url resolve

### ISSUE THREAD

**Issue by msmolka** [systemjs/systemjs#2056]
Hello, I have some troubles with resolving relative modules (v 6.1.4):

HTML:
```html
  <script type="systemjs-importmap" src="js/systemjs-importmap.json"></script>
  <script src="lib/system.js"></script>
  <script src="lib/extras/named-register.js"></script>
  <script src="lib/extras/amd.js"></script>

 <base href="/address/" target="_blank">
```
import-maps:
```json
{
  "imports": {
    "login": "js/login.js"
  }
}
```
The following error occur:
`
 Error: Unable to resolve specifier 'login' from https://localhost:44371/address/
`

if I change imports to
```json
{
  "imports": {
    "login": "./js/login.js"
  }
}
```
then following error occur (double `/js/js/`):
`
Error: Error loading https://localhost:44371/address/js/js/login.js
`

if I setup app with root so
HTML:
```html
 <base href="/" target="_blank">
```
and
import-maps:
```json
{
  "imports": {
    "login": "/js/login.js"
  }
}
```

all is working.

I wonder how to define import maps relative to base url

**Comment by msmolka** [comment]
I think double js is related to `systemjs-importmap.json` path. But still, it is possible to make related to base url?

**Comment by joeldenning** [comment]
>  Error: Unable to resolve specifier 'login' from https://localhost:44371/address/

I believe that SystemJS is interpreting `js/login.js` as [import map composition / cascading](https://github.com/systemjs/systemjs/blob/master/docs/import-maps.md#composition), meaning that it thinks that `js` is something that should be in the import map that is being "composed" and the `/login.js` is just added after the composed value.

My understanding is that that behavior is the currently favored approach by the import maps spec process (see https://github.com/WICG/import-maps/issues/137). Systemjs is correct in its implementation.

> I think double js is related to systemjs-importmap.json path. But still, it is possible to make related to base url?

Yes. From [the import maps readme](https://github.com/WICG/import-maps#bare-specifiers-for-javascript-modules):

> In the case of relative-URL-like addresses, they are resolved relative to the import map's base URL

Also see the following systemjs code that implements this: https://github.com/systemjs/systemjs/blob/7aa995996319dc86bf5598f952620ca6c16f0ca1/src/features/import-map.js#L34

I'm closing this because there doesn't appear to be a bug with SystemJS here. Feel free to comment further / reopen with continued discussion.

**Comment by guybedford** [comment]
@msmolka note that import maps are resolved relative to the path of the import map file itself. The only way it will use the base URL is if the import map is contained inline in the page:

```html
<script type="systemjs-importmap>
   ...
</script>
```

As @joeldenning describes the first case this is because the RHS specifiers must be URLs, and cascading may be allowed in future through this approach. I've just created an import maps issue for this at https://github.com/WICG/import-maps/issues/192 as it seems like it could be confusing to others.
