### ISSUE TITLE
All files need to be at root dir?

### ISSUE THREAD

**Issue by JohnnyFun** [systemjs/systemjs#2059]
I had the following output dir that didn't work:

```
public
  scripts
     s.min.js
     named-register.min.js
     app.js
     chunk-_commonjsHelpers.js
  index.html
```
But it worked perfectly when I moved all my js out into the same dir as my `index.html` like:
```
public
  s.min.js
  named-register.min.js
  app.js
  chunk-_commonjsHelpers.js
  index.html
```

Is that expected?

`"rollup": "^1.25.1",`
`"systemjs": "^6.1.4"`

The error happens when systemjs tries to load a dependency for the main app module. Rollup outputs something like this:
```
System.register('app', ['./chunk-_commonjsHelpers.js'], function (exports, module) ...
```
And systemjs is unable to resolve the commonjsHelpers module path. 
The error I got was: 
```
Uncaught (in promise) TypeError: registration[1] is not a function
    at s.js:223 (un-minified line number)
```

I thought maybe the `named-register.js` extra wasn't calling the original register func correctly or something. All it takes to resolve the error is to move all my js files to the same dir as my index.html (and change the script src attributes accordingly).

My index.html looked like:
```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf8">
	<meta name="viewport" content="width=device-width">
	<title>Svelte app</title>
	<link rel="icon" type="image/x-icon" href="/favicon.ico">
	<link rel="stylesheet" href="styles/app.d41d8cd98f00b204e9800998ecf8427e.css">
	<link rel="stylesheet" href="styles/fontawesome.min.css">
</head>
<body>
	<script type="text/javascript" src="scripts/s.js"></script>
        <!--rollup outputs named register like "System.register('app', [], function...)-->
	<script type="text/javascript" src="scripts/named-register.js"></script>
	<script type="text/javascript" src="scripts/app.d90d7e3c.js"></script>
	<script>
		System.import('app')
	</script>
</body>
</html>
```

Let me know if you need more info. No rush, as I'm able to work around, but boy was I confused for a looong time lol.

**Comment by JohnnyFun** [comment]
I also noticed that if my url isn't at the root, it loads it relative to that too.

e.g., I'm at `https://localhost:5000/users/johnny`, and it tries to load chunks from `https://localhost:5000/users/[chunkname.js]`, instead of `https://localhost:5000/[chunkname.js]`.

Do I need to configure a baseUrl for systemjs or something like that perhaps?

**Comment by joeldenning** [comment]
Relative urls within the import map are relative to the base URL. From the [import maps spec](https://github.com/WICG/import-maps#bare-specifiers-for-javascript-modules) (also see related https://github.com/systemjs/systemjs/issues/2056):

> In the case of relative-URL-like addresses, they are resolved relative to the import map's base URL

Relative urls loaded from within a module should be loaded relative to that module. See the following lines of code:

https://github.com/systemjs/systemjs/blob/85eb636f46dc4b4a37ffe65affa9e87cfb54d654/src/system-core.js#L77

https://github.com/systemjs/systemjs/blob/85eb636f46dc4b4a37ffe65affa9e87cfb54d654/src/system-core.js#L139

In your code, `'./chunk-_commonjsHelpers.js'` is being resolved to a full url relative to its parent module, `app`. However, your parent module `app` does not resolve to `/scripts/app.js`. You can verify this by running `System.resolve('app')` in the browser console -- you'll see that it does not resolve to a url with the scripts directory in it. The reason is that you didn't specify the url for the `app` bare specifier through an import map. The more normal workflow with systemjs would be to put an import map into the html file that maps `app` to `/scripts/app.js`. Then the relative resolution of commonjs helpers would work appropriately.

I am closing this since it does not appear to be a bug in systemjs and I believe I've explained to you what's happening with your code and what you can do to fix it. If I'm mistaken, feel free to reopen or comment further.

**Comment by JohnnyFun** [comment]
Oh, I'm a butthead. I should've noticed that. Thanks for taking the time to explain.

Fwiw, I ended up taking away my `rollup.output.name`, so that rollup doesn't generate named registers. That way, I won't need `named-register.js`. And I can still use `s.min.js` since I now don't need the import maps that you mentioned because I import with the full path like `System.import('/scripts/app.[hash].js')`.

I think I was confused because the `rollup-starter-code-splitting` project use "./" instead of "/", so I just blindly did the same, which caused the issue when I navigated to `/users/johnny` and reloaded the page. In fact, I wonder if that project should skip the "." when it does `System.import('./nomodule/main-a.js');`? I imagine if that app had routes, it'd fail to load in systemjs scripts.

They also aren't generating named registers since their rollup config doesn't specify `rollup.output.name`.

**Comment by JohnnyFun** [comment]
It also didn't help that the rollup plugin that I use to generate my `index.html` file wasn't including the slash at the beginning either lol. That probably threw me off in all the confusion too and I forgot basic relative path rules...I'll have to find/write something that generates that along with my systemjs import (since I include [hash] on my output file names).
