### ISSUE TITLE
SystemJS is not defined Angular 8

### ISSUE THREAD

**Issue by cesarcastmore** [systemjs/systemjs#2067]
I am trying to develop using SystemJS but I have the error

**SystemJS is not defined**

app.component.ts

`declare const SystemJS;
`

angular.json
` "scripts": ["./node_modules/systemjs/dist/system.js"]`

package.json
`{
  "name": "external-dynamic-components",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.11",
    "@angular/common": "~8.2.11",
    "@angular/compiler": "~8.2.11",
    "@angular/core": "~8.2.11",
    "@angular/forms": "~8.2.11",
    "@angular/platform-browser": "~8.2.11",
    "@angular/platform-browser-dynamic": "~8.2.11",
    "@angular/router": "~8.2.11",
    "rxjs": "~6.4.0",
    "systemjs": "^6.1.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.12",
    "@angular-devkit/build-ng-packagr": "~0.803.19",
    "@angular/cli": "~8.3.12",
    "@angular/compiler-cli": "~8.2.11",
    "@angular/language-service": "~8.2.11",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "ng-packagr": "^5.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tsickle": "^0.37.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}
`

Could you tell me what i am doing bad?

**Comment by joeldenning** [comment]
systemjs@6 no longer creates a global variable called `SystemJS`. Instead, it only creates a variable called `System`.

The reason is that the `System` variable was on standards track back when systemjs@0.x was being worked on. So SystemJS would create a `SystemJS` variable so that you could avoid overriding the variable that was presumably one day going to be implemented by the browser.

By the time that systemjs@2 was created, `System` was no longer on standards track and is now defunct entirely as a browser spec. The core concepts of systemjs are very much alive and well (such as import maps and dynamic in-browser import). However, the standards shifted such that the `System` global variable is no longer ever going to be implemented by browsers. As such, systemjs@2 no longer creates the `SystemJS` variable since there is no risk of collision with a browser implementation of `System`

Closing this since I think I've answered the question, but feel free to reopen or comment further.
