### ISSUE TITLE
How to avoid browser cache, HTTP status is 304。

### ISSUE THREAD

**Issue by githubSiYao** [systemjs/systemjs#2070]
I used single-spa framework with systemjs. After I registered the micro application, browser load every micro front application is ok.But,if I have a patch,so I replace one of the appliactions.SystemJS.import('./entry.js') is fetched from browser cache, HTTP status is 304 code.How can I resolve SystemJS.import() is not from browser cache,

I used SystemJS in version 0.21.6.

**Comment by joeldenning** [comment]
The best way to solve this problem is on your server, not within SystemJS or in the browser. I would recommend one of the following:

# Server solutions
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag
- Change url of `entry.js` when you patch it. For SystemJS@6 this is easiest done by modifying the import map with [import-map-deployer](https://github.com/CanopyTax/import-map-deployer) during a CI process. See [this Travis CI example](https://github.com/CanopyTax/import-map-deployer/blob/master/examples/ci-for-javascript-repo/travis-digital-ocean-spaces/.travis.yml#L29)

# Browser-only solution
- Add a query string with the current timestamp to the url. For example, download `./entry.js?1573878549105`

I'm closing this since it's not an issue with SystemJS itself.

**Comment by brandones** [comment]
@joeldenning Why isn't cache-busting using the `Cache-Control` header a good option, at least for CI/dev environments?

**Comment by joeldenning** [comment]
Using Cache-Control as a deployment mechanism has some downsides. If the Cache-Control header is too long, then users won't see the newly deployed code for a long time. If the Cache-Control header is too short, users won't benefit from the performance of caching. Also throw in the unpredictability of whether browsers choose to disobey the Cache-Control header (which they sometimes do), and you don't have a very satisfying deployment mechanism.

Using a completely different URL for newly deployed files gives best of all worlds - you can cache all files for a very very long time while also have fully predictable timing on your deployments (by updating the import map, and ensuring that any external import maps are not cached).

**Comment by brandones** [comment]
Okay, thank you!

**Comment by csomakk** [comment]
for reference, a bit better browser only solution: on the app build, make a manifest.json file that will have your bundle path, like bundle.e63c2b.js, and instead loading bundle.js load the manifest, and then the referenced version. that way you'll have a nice immutable webapp, the noncached bit will be a few chars of json, and in return .js can be cached forever, and all the bundle updates will take effect on release immediately.
