### ISSUE TITLE
SystemJS’s Expand the usage with React

### ISSUE THREAD

**Issue by yuanman0109** [systemjs/systemjs#2080]
I want to ask a question about systemjs，I found this js on single-spa，Inspired by this，I have an idea：1. container project config router；2. child project output a react component function；3. container project  use systemjs loading this component when switch router； i don't know this way Whether it is right，i've tried to make it work, So far, so normal，But I don't know if there are any safety concerns.  so， I hope to get your advice. Here's my code：
root router component：
![image](https://user-images.githubusercontent.com/22994293/69947949-b142aa00-1529-11ea-99f5-10e40d5a2c24.png)
child input：
![image](https://user-images.githubusercontent.com/22994293/69948156-14ccd780-152a-11ea-99a0-dbc0f3ca40b8.png)

**Comment by joeldenning** [comment]
> But I don't know if there are any safety concerns

There are no security problems with what you're doing.

> I hope to get your advice

There's nothing wrong with your overall approach. A couple small things - I'd recommend using [`React.lazy()`](https://reactjs.org/docs/code-splitting.html#reactlazy) and [function components with hooks](https://reactjs.org/docs/hooks-intro.html). At the very least, do not use componentWillMount since [it is deprecated](https://reactjs.org/docs/react-component.html#unsafe_componentwillmount). Instead, use componentDidMount.

Closing this because there's no issue with systemjs here. Feel free to comment with further discussion.

**Comment by yuanman0109** [comment]
> > 但我不知道是否有安全隐患
> 
> 您所做的工作没有任何安全问题。
> 
> > 我希望得到您的建议
> 
> 您的整体方法没有错。一对夫妇的小东西-我推荐使用[`React.lazy()`](https://reactjs.org/docs/code-splitting.html#reactlazy)和[功能部件用钩子](https://reactjs.org/docs/hooks-intro.html)。至少不要使用componentWillMount，因为[它已被弃用](https://reactjs.org/docs/react-component.html#unsafe_componentwillmount)。而是使用componentDidMount。
> 
> 由于这里的systemjs没有问题，因此请关闭它。随时发表评论并进行进一步讨论。

thank you for your reply. but my child component isn't in root project，so i'm must use systemjs instead of dynamic import function;

**Comment by joeldenning** [comment]
`React.lazy()` works with any function that returns a promise. Both webpack `import()` and `System.import()` work

**Comment by yuanman0109** [comment]
> `React.lazy()` works with any function that returns a promise. Both webpack `import()` and `System.import()` work
I see. I'll try，thank you
