### ISSUE TITLE
More helpful error message when trying to import CommonJS modules

### ISSUE THREAD

**Issue by brandones** [systemjs/systemjs#2082]
Right now, if I attempt to import a CommonJS module, I get the rather cryptic

```
Uncaught my-importing-module: Application 'my-importing-module' died in status LOADING_SOURCE_CODE: exports is not defined
    at http://localhost:7070/openmrs/frontend/react-i18next@11.2.5/dist/commonjs/index.js:3:23
i18next.js:5 Uncaught ReferenceError: require is not defined
    at i18next.js:5
```

It took me a while to figure out that this is because they are CommonJS modules and that [SystemJS no longer supports CommonJS](https://github.com/systemjs/systemjs/issues/1853#issuecomment-426268222).

I (and I expect a lot of developers) would have saved a lot of time with an error message like

```
Uncaught ...: Module 'foo' is a CommonJS module, which SystemJS does not support importing. See https://github.com/systemjs/systemjs/blob/master/docs/module-types.md for the supported types.
```

**Comment by joeldenning** [comment]
Generally speaking, the systemjs error messages are not great. I think the primary driver for this has been a concern about bundle size. @guybedford has very much pushed to keep the bundle size for systemjs very low. I do not think that he would be amenable to increasing the bundle size for the sake of this error message.

One idea for getting better error messages without sacrificing bundle size is to do what react and single-spa@5 do -- use numbered error messages in production build and full string messages in dev build.

Proposal:

Create a function similar to the one below:
https://github.com/CanopyTax/single-spa/blob/7a05d7f2bbb5346e8e320ecf3a3c2954425fde04/src/applications/app-errors.js#L50

Migrate all errors to use that function. This saves bytes in the production build because all string error messages are removed:
https://github.com/CanopyTax/single-spa/blob/7a05d7f2bbb5346e8e320ecf3a3c2954425fde04/src/applications/app-errors.js#L35

For dev build, keep string messages. For prod build, use only numbered messages:
https://github.com/CanopyTax/single-spa/blob/7a05d7f2bbb5346e8e320ecf3a3c2954425fde04/rollup.config.js#L12

Use rollup-plugin-replace + terser to ensure the dev messages are removed from the production bundle.
https://github.com/CanopyTax/single-spa/blob/7a05d7f2bbb5346e8e320ecf3a3c2954425fde04/rollup.config.js#L43

I think this is a way of improving DX while decreasing byte size of the production systemjs. @guybedford what are your thoughts on that?
