### ISSUE TITLE
Cannot add property React, object is not extensible

### ISSUE THREAD

**Issue by ameerthehacker** [systemjs/systemjs#2088]
Not sure what is this wierd error

**Comment by joeldenning** [comment]
Would need a lot more information to diagnose this. Most ideal would be a github repo that demonstrates the problem.

**Comment by zsirfs** [comment]
```js
System.import('react').then(function (ns) {
        return Object.setPrototypeOf(ns, Object.prototype)
      })

```

**Comment by joeldenning** [comment]
[This codepen](https://codesandbox.io/s/stoic-cache-r8vhc?file=/index.html:650-679) demonstrates that the code you shared does not result in an error.

Note that it is intentional that React's prototype is `null` instead of the Object prototype, as ES modules have a null prototype per the ES module spec.

This error only would occur if `Object.preventExtensions()`, `Object.seal`, or `Object.freeze` is called on the namespace (ns) object. However, SystemJS does not do so, and my guess is that there is other code on the page that is doing so in your scenario.
