### ISSUE TITLE
Reconsider multiple import maps support?

### ISSUE THREAD

**Issue by joeldenning** [systemjs/systemjs#2095]
As of August 2019, the import maps spec no longer supports multiple import maps or merging import maps together. Instead, multiple import maps are listed as future work.

See https://github.com/WICG/import-maps/commit/6f99d474e401e5c5b55b476301d984efbbb7b79c#diff-04c6e90faac2675aa89e2176d2eec7d8 and https://github.com/WICG/import-maps/#multiple-import-map-support.

The question for SystemJS is whether to drop support for multiple import maps or not. My vote is no, but think it's worth having a discussion around.

@guybedford what are your thoughts?

**Comment by guybedford** [comment]
When we landed multiple import maps support it was under the impression that import maps were soon going to be implemented with this feature in Chrome, informed from my discussions with Domenic at the time.

The current status seems to be that the way multiple import maps will be implemented may well differ from our expectations.

Given this, I think we should either:

1. Clearly indicate that multiple import maps are experimental and will change.
2. Revert them and support them via an extra or otherwise.

Open to suggestions too here.

**Comment by joeldenning** [comment]
Other dead features are cascading, virtualization, and fallback support (https://github.com/WICG/import-maps/#fallback-support). I think only cascading is supported in SystemJS@6? Can't remember if fallbacks are supported.

My preference is towards keeping multiple import maps but indicating that they are experimental.  Not sure about cascading or fallbacks.

**Comment by LarsDenBakker** [comment]
I would place it in an extra, otherwise it is easy to make a mistake if your intention is to upgrade to esm later on.

**Comment by frehner** [comment]
From the single spa community perspective, nearly everyone relies on multiple import maps. 

Due to that, I like the idea of keeping it in, but I don’t think it would be a big issue to make it an extra. Would just need to be clear about the upgrade path.
