### ISSUE TITLE
Importmap scopes resolution for relative imports

### ISSUE THREAD

**Issue by joeljeske** [systemjs/systemjs#2102]
(disclosure: I'm not sure if Systemjs has the proper behavior according to the spec or not; this could be a false bug report)

### GIVEN

**myModule.js**

```js
const importSubresource = () => import('./subresource')
```

**import-map.json**

```js
{
  "imports": {
    "myModule": "/myModule/myModule.abc123.js"
  },
  "scopes": {
    "/myModule/": { 
       "subresource": "/myModule/subresource.def456.js", 
       "./subresource": "/myModule/subresource.def456.js" 
        // ^ Attempted both of these options, but likely should only need to specify one of them
    }  
  }
}
```

### Expected 

I would expect to be able to load the subresource leveraging the scopes resolution of the importmap

### Actual

Fails with a 404 trying to load 

`/myModule/subresource.js`

**Comment by joeldenning** [comment]
Is myModule.js being compiled with webpack? With rollup? Is it being compiled to System.register format? What is happening to the dynamic `import()` during compilation?

**Comment by joeljeske** [comment]
Sorry, that was unclear; my bad.

It is being compiled with rollup to System.register format. The dynamic import gets transpiled to 
`module.import()`

**Comment by joeldenning** [comment]
I just reviewed the import map spec - I think these are the relevant sections: [parsing import maps](https://wicg.github.io/import-maps/#parsing), [sort and normalize scopes](https://wicg.github.io/import-maps/#sort-and-normalize-scopes) [resolving](https://wicg.github.io/import-maps/#resolving), [parsing a url-like specifier](https://wicg.github.io/import-maps/#parse-a-url-like-import-specifier).

Applying the resolving algorithm to your example (while asumming it's running on localhost 8080 with baseURL for the page as `/`), my understanding is that the variables values are the following:

- `baseURL` is http://localhost:8080/myModule/ (because that's the base url of the referring script)
- `asURL` is http://localhost:8080/myModule/subresource.js
- `normalizedSpecifier` is http://localhost:8080/myModule/subresource.js
- `scopePrefix` is http://localhost:8080/myModule/
- `scopeImports` is the following:
```json
{
  "subresource": "http://localhost:8080/myModule/subresource.def456.js",
  "http://localhost:8080/subresource.js": "http://localhost:8080/myModule/subresource.def456.js"
}
```

The conditions for whether a scope applies to an import are explained in the "resolving" section. In subsection 8.1, it says "If scopePrefix is baseURLString", which sends us into the if statement at 8.1.1. Notice that the none of the normalized keys in `scopeImports` match the normalizedSpecifier.

It is for that reason that the scopeImports are not being applied. I do not think this is a bug in SystemJS.

I'm closing this issue, but If you come to different conclusions about the values of the variables I listed above, let's discuss this further / reopen.

**Comment by joeldenning** [comment]
[This code sandbox](https://codesandbox.io/s/admiring-lake-ycq21) shows how you can get the desired behavior. TLDR is to change your import map to the following:

```json
      {
        "imports": {
          "myModule": "/myModule/myModule.abc123.js"
        },
        "scopes": {
          "/myModule/": {
            "/myModule/subresource.js": "/myModule/subresource.def456.js"
          }
        }
      }
```

**Comment by joeljeske** [comment]
Perfect! Thank you for the example! I was sure there must be a simple way to express my desired behavior, but there’s not a ton of good resources for import maps that I’ve found. 

I appreciate the help.
