### ISSUE TITLE
6.2.1 is error with highcharts

### ISSUE THREAD

**Issue by FreezeSoul** [systemjs/systemjs#2118]
As the title shows, new release 6.2.1 is error with highcharts,but 6.1.9 is fine.

You can find the demo here: https://codesandbox.io/s/kind-hodgkin-785wv

Simple import but get the error:

> system.min.js:4 Uncaught (in promise) TypeError: t.indexOf is not a function
    at i (system.min.js:4)
    at y.g.resolve (system.min.js:4)
    at y.r.resolve (named-register.min.js:1)
    at system.min.js:4
    at Array.map (<anonymous>)
    at system.min.js:4

Looking forward to your attention， Thk...

**Comment by joeldenning** [comment]
This is because highcharts calls define like so:

```js
define('highcharts/highcharts', function () {
  return factory(root);
});
```

But the AMD extra expects all named modules to provide a dependencies array - `define('highcharts/highcharts', [], function () {})`.

For anonymous AMD modules, systemjs properly handles the omission of the dependencies array, but for named modules it does not. I will submit a PR to fix this.

**Comment by joeldenning** [comment]
Fix at https://github.com/systemjs/systemjs/pull/2119

**Comment by joeldenning** [comment]
Released in https://github.com/systemjs/systemjs/releases/tag/6.2.2
