### ISSUE TITLE
How to use SystemJS.import('./some.js') like version: 0.21.0?

### ISSUE THREAD

**Issue by vortesnail** [systemjs/systemjs#2122]
In the `0.21.0` version, I can use 
```javascript
let config = await SystemJS.import ('/ config.js')
```
but after upgrading to `6.2.3` version, error happened: 
`main.js: 1 Uncaught' (in promise) ReferenceError: SystemJS is not defined`.

QUESTION:
1. How do i use `SystemJS.import('/config.js')` through `npm i systemjs --save`, what i have tried `import SystemJS from 'systemjs'` and `import 'node_modules/systemjs/dist/system.js'`.

2.if i use  `<script src="https://cdn.bootcss.com/systemjs/6.2.3/system.js"></script>` instead of `npm i systemjs --save`, How can I use it normally?

**Comment by joeldenning** [comment]
In systemjs@>6, there is no longer a `SystemJS` global variable, but only a `System` global variable. Also if you're using webpack, check out [these docs](https://github.com/systemjs/systemjs#compatibility-with-webpack) that explain how to ensure that `System.import()` is not interpreted as a webpack code split.

> How do I use System.import('/config.js') through `npm i systemjs --save`

systemjs@6 does not currently work in NodeJS ([tracking issue](https://github.com/systemjs/systemjs/issues/1873)). It is encouraged to load it via `<script>` and to not bundle it into webpack/rollup

CDN Usage: `<script src="https://cdn.jsdelivr.net/npm/systemjs/dist/system.js"></script>`

Closing because there's no issue here with systemjs, but feel free to comment further with more questions.
