### ISSUE TITLE
Error: Cannot find module 'vm' when using SystemJS v0.21.0 Dev with webpack

### ISSUE THREAD

**Issue by OZ79** [systemjs/systemjs#2128]
Hi,
I have encountered an issue similar to [1817](https://github.com/systemjs/systemjs/issues/1817) but with SystemJS **v0.21.0** Dev

Using webpack to package systemjs,  I get the following warning during compiling:
```
WARNING in ./node_modules/systemjs/dist/system.src.js 3860:22-33
Critical dependency: require function is used in a way in which dependencies 
cannot be statically extracted
 ...
Compiled with warnings.
```

Call fallowing: 
```
System.import("//chartjs.org/dist/master/Chart.js").then((module: any) => {
     console.log(module);
});  
```
results in:
```
Error: Cannot find module 'vm'
    at SystemJSLoader$1.webpackEmptyContext [as _nodeRequire] (dist_sync:2)
    at evaluate (system.src.js:2799)
    at eval (system.src.js:3518)
```
What is wrong, how to resolve this?

**Comment by joeldenning** [comment]
Generally speaking you should not bundle SystemJS with webpack. What I believe is happening here is that webpack is fooling SystemJS into thinking that it is running in NodeJS when it's actually running in the browser.

When SystemJS runs inside of NodeJS, it uses [vm](https://nodejs.org/api/vm.html) as a way of dynamically executing code. (See https://github.com/systemjs/systemjs/blob/0.21/dist/system.src.js#L2854-L2855)

The following code shows how webpack fools SystemJS:

- https://github.com/systemjs/systemjs/blob/0.21/dist/system.src.js#L3918
- https://github.com/systemjs/systemjs/blob/0.21/dist/system.src.js#L3283-L3284

Since webpack implements a version of `require` into browser bundles, SystemJS thinks it's running in Node.

The solution is to load SystemJS via script tag instead of bundled into webpack
