### ISSUE TITLE
unexpected behavior of amd import 

### ISSUE THREAD

**Issue by FreezeSoul** [systemjs/systemjs#2139]
In my project , the amd import some time has unexpected behavior.

I import serval amd modules in the same times, i found a case, the amd import get the wrong module.

I refresh the page serval times, it can get the error some times , it has very small chance.
I found it may appear larger on mobile chrome or switch tab unactived.

The issue seems to come from the order of modules loaded. 

The reason may caused by the use of 'setTimeout' in amd.js. 'setTimeout' not suitable for dense call sequences.

The demo is here : [https://codesandbox.io/s/bold-leaf-wti2z](https://codesandbox.io/s/bold-leaf-wti2z)
There is a screen record gif in the demo, you can find the issue.

The last release also has the issue.

Looking forward to your attention.

**Comment by joeldenning** [comment]
We've gone back and forth on the setTimeout - without it there are issues as well. We have had several commits that add it and then remove it and re-add it. Most recently it was added in https://github.com/systemjs/systemjs/pull/2121 which explains the case for it.

Thank you for providing a code sandbox for this. The sandbox appears to be rather complicated and I don't have the time/energy to look deeply into it right now. Perhaps later I'd be able to.

One thing to note is that race conditions with the setTimeout are related to named modules, not to anonymous modules. I'd encourage against the use of named modules, especially named AMD modules, since named modules are not part of any browser spec and have been rather hard to support (I've spent the better part of a year doing bug fixes for them within systemjs).

I think that to properly fix the issue we'd have to refactor the amd extra substantially such that it no longer returns the first named amd module from each file, but instead returns the last amd module in each file. If we change that behavior and do a significant refactor of the AMD module, I think it might solve the issue. If you have other ideas on how to fix it, I'm open to it. But I honestly don't have the energy / desire to debug your complex example right now.

**Comment by joeldenning** [comment]
I've created https://github.com/systemjs/systemjs/pull/2140 as a work-in-progress pull request to see if that might solve the problem.

**Comment by FreezeSoul** [comment]
You are right, i try  #2140 in my proj, it  solve the problem.

**Comment by joeldenning** [comment]
Fix released in https://github.com/systemjs/systemjs/releases/tag/6.2.6. Let us know if you still run into issues and we can revive #2140 as an alternative implementation/fix.
