### ISSUE TITLE
[help] external dependency loaded but not available

### ISSUE THREAD

**Issue by rkyoku** [systemjs/systemjs#2154]
Hi!

I am just about to quit ES modules and code my app manually using IIFEs like I did until now, because I am so frustrated... Have been at it for many hours, testing different configurations... 😥

If this is not the right place for asking for help, please do forgive me. 🙏

I am trying to generate bundles for IE11. I am using Rollup with two outputs : one using ES modules for normal browsers, another using SystemJS for IE11.

(I'm still having issues with the ES-bundle, but if I can fix the SystemJS bundle, I'll use only this one)

The problem is, my dependencies are loaded using a CDN (jsdelivr), and SystemJS can load them just fine, but then the classes/functions "exported" by these libs are not available inside SystemJS (but they are inside the console)

My config:

```
<script type="systemjs-importmap">
	{
		"imports": {
			"./app-webapp-2d8fd676.js": "{{ package('js', 'nomodule/app-webapp-2d8fd676') }}",
			"js-cookie": "https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js",
			"lightbox2": "https://cdn.jsdelivr.net/npm/lightbox2@2.11.1/dist/js/lightbox.min.js",
			"lazyload": "https://cdn.jsdelivr.net/npm/lazyload@2.0.0-rc.2/lazyload.min.js",
			"dropzone": "https://cdn.jsdelivr.net/npm/dropzone@5.7.0/dist/dropzone.min.js",
			"cropperjs": "https://cdn.jsdelivr.net/npm/cropperjs@1.5.6/dist/cropper.min.js"
		}
	}
</script>

// It seems I can't use the minimal s.js version because of the needed import map
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/systemjs@6.2.6/dist/system.min.js"></script>

<script src="{{ package('js', 'nomodule/' ~ app.fullAction) }}"></script>

// Why this extra step? Isn't the System.register() call enough when combined with the import map?
<script type="text/javascript">
	System.import('./app-webapp-2d8fd676.js');
</script>
```

Here is my `main.register.js` file (generated by Rollup):

```
System.register(['./app-webapp-2d8fd676.js', 'js-cookie', 'lightbox2', 'lazyload', 'dropzone', 'cropperjs'], function () {
	'use strict';
	var init, devlog;
	return {
		setters: [function (module) {
			init = module.i;
			devlog = module.d;
		}, function () {}, function () {}, function () {}, function () {}, function () {}],
		execute: function () {

			init(() => {
				devlog('TEST TEST TEST');
			});

		}
	};
});
//# sourceMappingURL=main.register.js.map
```

All the scripts load fine. But Here is the error I got:

```
Uncaught (in promise) TypeError: Cookies.get is not a function
    at get (cookies.js:241)
    at _getAuthtokenFromCookie (cookies.js:40)
    at Object.execute (cookies.js:55)
    at i (system.min.js:4)
    at t (system.min.js:4)
    at system.min.js:4
```

(the `cookies.js` is my own source file because all my code is split into so many files, not to mix with 
`js-cookie` which is a lib)

However, if I try directly in the console, I get:

```
> Cookies.get
ƒ (e){return c(e,!1)}
```

What did I do wrong? Why can't I seem to be able to find tutorials all around the Internet for such a classic scenario? (or maybe my search-fu is broken, because I have been at it for so many hours...)

I found [this tutorial](https://single-spa.js.org/docs/recommended-setup/#sharing-with-import-maps) where they explain:

> Not all libraries publish their code in **a suitable format for SystemJS consumption**. In those cases, check https://github.com/esm-bundle for a SystemJS version of those libraries. Alternatively, you may use SystemJS extras to support UMD bundles, which are often available.

But I couldn't find anything useful in the two links.

Thank you for any help you could provide me with!

I don't want to spend more days on this. If I can't find a suitable workflow, I'll get back to IIFEs and "old school JS"... Things that I know a tad better than Rollup+SystemJS.

But I would really like so much to keep using ES modules in my source code and still keep multi-entry points (one for each page) and Tree Shaking and IE11 compatibility...

Cheers,

**Comment by joeldenning** [comment]
Hi rkyoku,

> I am just about to quit ES modules and code my app manually using IIFEs like I did until now, because I am so frustrated... Have been at it for many hours, testing different configurations

Sorry to hear about the pain you've felt debugging this. The hardest part of SystemJS is often the module formats, and it sounds like the issues you've been seeing might be related to this. I personally have spent many many hours debugging systemjs problems and they can be particularly gnarly. We are putting together an error code system and documentation for the error codes (#2151) to try to alleviate some of the pain of this, but not even that would address this issue where the module formats aren't interop'ing with each other well.

Here are some responses to your comments above:

> // It seems I can't use the minimal s.js version because of the needed import map

Correct - if you want import maps you must use systemjs instead of s.js.

> // Why this extra step? Isn't the System.register() call enough when combined with the import map?

SystemJS modules must be loaded via `System.import()`. The System.register() api should be called as a result of a System.import(). Registering a module outside of an import() does not execute the code.

You can read more about that at https://github.com/systemjs/systemjs/issues/2148

**Here's what is happening:**

I created [this code sandbox](https://codesandbox.io/s/bold-satoshi-y20bd), which shows what is going on.

You are using SystemJS' [global loading](https://github.com/systemjs/systemjs#extras) feature, which is built into system.js. The way that global loading with SystemJS works is that it converts global variables into ES module objects. Since global variables may be any type (string, object, function, etc), SystemJS has to choose how to represent it as an ES module object. The way it does so is by marking whatever the global variable is as the ES "default" export.

In your cookies.js code, you likely are doing `import Cookies from 'js-cookie'`. I think the question is whether rollup's compilation to System.register format is interpreting js-cookie as an ES module correctly or not.

You pasted some of your main.register.js file, but I think you omitted some relevant parts. Could you paste the whole thing, or at least the full `setters` and compiled code that calls `Cookies.get`? That part will be important.

Here's a workaround you can try in the meantime, but I think the rollup output will provide a more satisfying answer:

```js
import * as CookiesModule from 'js-cookie'

const Cookies = CookiesModule.default
Cookies.get()
```

**Comment by rkyoku** [comment]
Hi Joel,

Sorry, I forgot to sign my first message, my actual name is Renaud :)

Thank you so much for accepting this help request and for taking the time to answer me!

I used your valuable sandbox to start from scratch, and I could see what was happening: I was still loading external dependencies as a bundle from jsDelivr (old code), in addition to the import map, and somehow it was messing with the import map because when it complained not being able to find the module, and I checked that, it sent me to the bundle from jsDelivr.

I removed the bundle from jsDelivr, made a few modifications thanks to your comments, tried again with a minimal example, and it seems to work now!! 🥳 (still a few issues with Rollup that I'll have to investigate)

```
<script type="systemjs-importmap">
	{
		"imports": {
			"jquery": "https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js",
			"js-cookie": "https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"
		}
	}
</script>

<script src="https://unpkg.com/systemjs/dist/system.js"></script>
// I am not using the extras/use-default, and it seems to work with or without it (tried both)

<script type="text/javascript">
	// I am now "import-ing" the entry point rather than the dependency... It was one of my mistakes
	System.import('{{ static('js/nomodule/main.register.js') }}');
</script>
```

It works (for now ^^) like this, thank you **so much** 🙏

I am still struggling to understand why I couldn't use a "big bundle" from jsDelivr, and use my dependencies as global variables rather than imported modules, but I think that's something I have to investigate on the Rollup part (because Rollup doesn't use the `globals` option alongside code splitting).

Maybe just an ESlint comment `/* global Cookies */` and not doing any `import Cookies from 'js-cookie'` would fix that and give me a more lean output and easier dependencies management (on the other hand, I would lose code-completion). I'll try that, IMHO it's easier that way, and I can bundle my dependencies as I wish.

Thank you again so much Joel, I was losing hope (really), and you saved me a refactoring here!

![bitmoji](https://sdk.bitmoji.com/render/panel/6e3eb687-79c8-443e-b053-fc574f6a5be9-a852fe6f-e5f2-4854-9677-7b9b58600685-v1.png?transparent=1&palette=1&width=246)

I'm closing this as not to pollute the issue tracker, thank you again, really!

Best,

Renaud

PS: regarding issue #2148  I thought that it was deprecated to use the "name" parameter now? Though your comment on this issue is merely a week old... I must have misunderstood something else 😅

**Comment by joeldenning** [comment]
> it seems to work now!!

I'm glad to hear you got it working!

> I am still struggling to understand why I couldn't use a "big bundle" from jsDelivr, and use my dependencies as global variables rather than imported modules, but I think that's something I have to investigate on the Rollup part (because Rollup doesn't use the globals option alongside code splitting).

This should be possible. Do `window.Cookies` instead of `import Cookies from 'js-cookie'` and it should work. I'm not sure what could cause that to fail.

> PS: regarding issue #2148 I thought that it was deprecated to use the "name" parameter now? Though your comment on this issue is merely a week old... I must have misunderstood something else 😅

Named registers aren't encouraged, and I believe Guy Bedford have used the term "deprecated" a few times in github issues related to them. We haven't removed the feature, though. In #2148, I listed three options and recommended a different option that didn't use named register. But I listed named-register for completeness - some people may already be using the extra or not mind using it even though it's discouraged.

**Comment by rkyoku** [comment]
I like your third option, using `type="systemjs-module"`. I think it leads to cleaner code as we are removing one script tag (yeah it may be epsilon, but it does still matter :) )

I think `window.Cookies` would be identical to `/* global Cookies */` and then using just `Cookies` inside the code, right? In both cases, it will be a global variable and the IDE would know about it. The only limitation would be the loss of IntelliSense/completion.

It may be what I am going to do, because as I made my example of this morning a bit more realistic, I stumbled upon issues, like `$ is not defined` in some external dependenies... (yeah still using jQuery here).

Going the `global` route may fix that, and also allow for a "package" using jsDelivr, rather than one call for each dependency (even though I am trying to limit them even more, and http2 does alleviate that anyway).

Thank you again Joel! I really appreciate your help.

Take care,
