### ISSUE TITLE
How to use npm installation in the browser?

### ISSUE THREAD

**Issue by kukuyu** [systemjs/systemjs#2175]
Not really an issue, more of a question:

I am introducing it in the html now: 
`<script src="./system.js"></script>`

What should I do if I want to use it as an installation package? (On the browser side)
I try like this:  
npm install systemjs
`import Systemjs frome 'systemjs'`

it`s fail!  what should i do ?   thanks.

**Comment by joeldenning** [comment]
It is recommended to do use SystemJS via script tag instead of bundling it. However, you may bundle it with the following:

```js
import 'systemjs/dist/system.min.js';

console.log(window.System)
```

If you do bundle it, you need to ensure the following:

1. SystemJS is executed before you run System.import(). You do this by making it the first import in your bundler's entry file.
2. You must execute your bundle via `<script src="/bundle-with-systemjs"></script>` - you cannot `System.import('/bundle-with-systemjs')`.

**Comment by kukuyu** [comment]
thank you!
