### ISSUE TITLE
System.import cannot be used indirectly

### ISSUE THREAD

**Issue by EveChee** [systemjs/systemjs#2189]
- SystemJS Version: 
- Which library are you using?
  - [ √] SystemJS
  - [ ] SJS
- Which extras are you using?
  - [ ] AMD extra
  - [√ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
- Are you using any [custom hooks](/docs/hooks.md)?

### Question
Why System.import cannot be used indirectly ????
my typescript code:
`
function configurableLoad({ el, name }: any, out?: any) {
  const life = System.import(name)
  console.log(System.import)
  return life
    .then(({ vueLifeCycles }: any) => vueLifeCycles({ el, namespace: name }))
    .catch(e => console.log(e))
}
`
An error System.import cannot be used indirectly 

Please help me. I've had a headache for a few days

**Comment by joeldenning** [comment]
Hi @EveChee - this sounds like you're using webpack but have not configured webpack to ignore `System.import`.

In webpack@2, `System.import()` was processed by webpack at build-time as a webpack code split, instead of a runtime module with System.import. This behavior was deprecated in webpack@3 in favor of just `import()` for code splits. However, `System.import()` is still enabled by default as a webpack code split.

When using SystemJS, you should turn the behavior off so that `System.import()` is run unchanged in the browser.

To do so, follow [these instructions](https://github.com/systemjs/systemjs#compatibility-with-webpack). 

```js
// webpack.config.js
{ module: { rules: [ { parser: { System: false } } ] } }
```

**Comment by EveChee** [comment]
Thank you very much. I'm very glad to receive your reply. I tried it and it worked.
