### ISSUE TITLE
can't import localforage

### ISSUE THREAD

**Issue by mariusnita** [systemjs/systemjs#219]
``` js
import localforage from "../bower_components/localforage/dist/localforage.nopromises";
console.log(localforage);
// --> undefined
```

This is where localforage registers itself: https://github.com/mozilla/localForage/blob/master/src/localforage.js#L308-L316

Any ideas why? It seems `define` and `define.amd` is defined, I assume by `systemjs`.

**Comment by dsebastien** [comment]
Hey there. I know this is an old issue, but I'm facing it right now and am a bit lost. I don't really understand the outcome of this issue; what was the solution?

I see that when you were discussing this, there was a named define: https://github.com/mozilla/localForage/blob/664667c43557d230dd1a9304e50e75d74b34313d/src/localforage.js#L309

But in the current version I don't find that anymore.
SystemJS does load the module (I could confirm that by placing a console.log statement atop the main file.. :p), but I don't know how to debug what happens any further..

**Comment by dsebastien** [comment]
Going through the debugger, I see that the module does get loaded correctly! My excuses for wrongly accusing SystemJS :)

The issue seems to be with the way I was importing it: `import {localForage} from "localforage";` that TS does not seem to support for commonjs modules :(

While both my IDE and tsc were happy (I did get auto completion and tsc transpiled without error), the output of tsc was surprising for me:

```
var localforage_1 = require("localforage");
localforage_1.localForage.setItem("key", "cool");
...
```

What a modular nightmare ;-)
