### ISSUE TITLE
Post-redirect relative paths incorrectly resolving

### ISSUE THREAD

**Issue by privatenumber** [systemjs/systemjs#2191]
### Demonstration

Code Sandbox: 
https://codesandbox.io/s/floral-rgb-lbqwh?file=/index.html

### Expected Behavior
For relative imports to be resolved successfully despite redirect.

### Actual Behavior
The relative path is resolved from the requested URL rather than the resolved URL.

The reproduction is using AMD, but I speculate it might be happening for non-AMD as well.

**Comment by guybedford** [comment]
This is a duplicate of the closed issue https://github.com/systemjs/systemjs/issues/1754.

Unfortunately `<script>` tag injection, the primary loading method in SystemJS, can not support redirect resolution.

Note though that module redirects are strongly discouraged because they break instance uniqueness. Rather module CDNs should not use redirects but use modular redirects.

See https://codesandbox.io/s/serverless-forest-oph48?file=/index.html for an example of how jspm.io manages this.

**Comment by privatenumber** [comment]
That's a great solution, thank you!
