### ISSUE TITLE
Best approach to self executing SystemJS entrypoint

### ISSUE THREAD

**Issue by balloob** [systemjs/systemjs#2194]
- SystemJS Version: 
- Which library are you using?
  - [ ] SystemJS
  - [x] SJS 6.3.2
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [x] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
- Are you using any [custom hooks](/docs/hooks.md)? No

### Question

I'm working on migrating the [Home Assistant frontend](https://github.com/home-assistant/frontend) from Webpack to using Rollup. We ship two builds, a build targetting last 2 versions of major browsers and an ES5 build. We rely on code splitting and so for our ES5 build we have settled upon using SystemJS.

To use SystemJS we now have code like this:

```js
const scriptEl = createScriptEl("/static/s.min.js")
scriptEl.onload = function() {
  System.import("/frontend_es5/core.js").then(function() {
    // App should always load after core because core contains polyfills.
    System.import("/frontend_es5/app.js");
  })
}
document.head.append(scriptEl);
```

This is working, but doesn't load as fast as I would like. The problem here is that the browser doesn't know it has to preload the scripts and so we get a waterfall loading pattern. 

To speed it up, I would want to create 1 file that loads SystemJS, the first entrypoint and instantiates it. It would look like:
 - content of `s.min.js`
 - named register extra
 - `core.js` but register rewritten to be a named register
 - `System.import('core')` to load `core.js`

Is this the right approach or am I missing something and could this be done even easier?

(I am aware of the limitation of named extra to only have 1 register per file (#2185), but that should not happen here.)

**Comment by joeldenning** [comment]
Hi @balloob - the very most important thing you can do is switch from dynamically created scripts to static scripts in the HTML.  That will help the browser start downloading everything in parallel even though things will be executed in order.

The performance difference between a single static script in the HTML versus 2-4 static scripts is negligible if they're all on the same server, due to HTTP2 multiplexing. As such, combining s.js, named register extra, and your other files into a single file does not yield much performance benefit. Much more important is that you tell the browser to statically [preload](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content) the files that you know you're going to need.

Additionally, making core.js a dependency of app.js makes a bit more sense to me than loading them in order via System.import().then()

Here is what I'd recommend:

```html
<script src="/s.min.js"></script>
<script src="/named-register.js"></script>
<link rel="preload" href="/frontend_es5/core.js" as="script">
<link rel="preload" href="/frontend_es5/app.js" as="script">
<script>System.import('/frontend_es5/app.js')</script>
```

```js
// app.js

// make the core lib a dependency of app.js, so systemjs will ensure core is instantiated first
System.register(['core'], function(_export) {
})
```

**Comment by balloob** [comment]
Hey, thanks for the response. 

The ES5 build is only going to be served to older browsers. Once we switch to Rollup, any browser that doesn't support dynamic import will get the ES5 version. Only Chrome supported `preload` before dynamic import, but that is an evergreen browser so not a problem. 

I wish we could use HTTP 2, but Home Assistant runs all local and uses aiohttp for serving the website, which only supports HTTP 1.1. 

The reason that core.js is not a dependency of app.js is that in the latest build we download and execute our 5kb of core.js first, which start the websocket connection to the backend while app.js is downloaded and parsed. We noticed a significant boost in speed when we did that.

In the ES5 build `core.js` contains the polyfills, so it needs to be loaded prior to `app.js`, so you're right that it would make sense to make it a dependency of `app.js`. I don't want the two builds to diverge too much, but I could make that change if I update the build outputs to be a named register anyway.

I just realize that SystemJS doesn't execute the JS until it is actually imported. So I should be able to load all scripts with defer + named register and when `app.js` is loaded, I know that `core.js` has been loaded because `defer` maintains the import order, and then call `System.import`, which will be instant as it's already registered. 

```js
_deferLoad("s.min.js");
_deferLoad("/frontend_es5/core.js");
_deferLoad("/frontend_es5/app.js").onload = function() {
  // deferLoad returns the script element it has created
  System.import("/frontend_es5/core.js")
};
```

**Comment by balloob** [comment]
btw the reason I can't just do things in HTML is that we're using feature detection to switch between latest and ES5 build, and so as part of [the feature detection](https://github.com/home-assistant/frontend/blob/dev/src/html/index.html.template#L55-L80) we create the tags for loading the right build.

**Comment by joeldenning** [comment]
> btw the reason I can't just do things in HTML is that we're using feature detection to switch between latest and ES5 build, and so as part of the feature detection we create the tags for loading the right build.

If you're serious about performance, dynamically injecting the script for s.js is simply is too much of a compromise. I would guess that dynamic injection of scripts makes a much bigger performance difference than the difference between 1 script elements versus 4 script elements.

Here are some alternatives to consider:

1. Always load s.js and named-register, even in browsers that won't use them. This is slightly worse performance for newer browers, but significantly better performance for older browsers.
2. Use `<script nomodule>` to load s.js and the named-register extra. This is easiest solution but only works if the browser support for nomodule exactly matches what you need with dynamic import support.
3. Have the server check User-Agent and serve a different HTML file for older browsers that has static scripts in it for s.js. This definitely will work and gives you full control over your performance.
4. Use alternative preloading approaches for older browsers, including `new Image().src ='/foo.js'`, which can work
5. Use `document.write()` to inject static scripts into the HTML after doing a feature check, so that you can get the perf benefits of the browser's initial HTML parsing/loading optimizations.

Another thing to consider is how combining all four of the scripts together makes that file much less cacheable. When you change app.js, it's nice to not bust the browser cache for s.js, named-register, and core.js.

> I wish we could use HTTP 2, but Home Assistant runs all local and uses aiohttp for serving the website, which only supports HTTP 1.1.

My overall impression is that your performance optimization is focusing on the wrong things - you're trying to optimize the things that don't impact performance very much while missing the things that definitely impact performance a lot more. HTTP 1.1 -> HTTP 2 is likely the most important perf improvement here. I would guess it has much more of an impact than combining two network requests (s.js and named-register.js which only ~4kb total) into a single network request. Additionally, you should focus on static scripts in your HTML file as much as possible, since it's impossible to beat the performance of the browser's HTML parsing that results in parallel script loading. Also, you should definitely gzip these files if that's not happening. Focusing on those performance aspects should be top priority.

**Comment by balloob** [comment]
Thanks for the alternatives. I'll take a look.

We're also looking at other optimizations, but since we're introducing SystemJS right now as part of Rollup, that had my attention. I wanted to make sure I wasn't missing anything obvious that SystemJS can do. 

Thanks for the insights!

**Comment by seivan** [comment]
@joeldenning 

> Use <script nomodule> to load s.js and the named-register extra. This is easiest solution but only works if the browser support for nomodule exactly matches what you need with dynamic import support.

I just want to point out, this isn't a perfect target.
We do the same thing as @balloob mentioned but our "cutoff"
is environments that support Dynamic Import  (`import("")`)  or not.

So we also have the "adding-scripts-at-runtime" where we check if `import()` is available in which they get `ES modules with ES2015 code` otherwise `SystemJS with ES5 code`. 

But we need to do it without altering our code too much. 
I don't want the code to actually depend on `SystemJS` import calls, vs just using `<script>` tags in the html or `import {x} from "y"` in code.

**Comment by guybedford** [comment]
The two-phase load is very much a necessity in the SystemJS case. As @joeldenning has pointed out, loading SystemJS even when not needed is a good approach.

Another optimization to make is that polyfills can be included in the main RollupJS build fine - just not the polyfills needed by SystemJS.

The best load profile would look something like this:

1. Initial HTML Payload includes inlined SystemJS. If needing to support IE11, those polyfills should be loaded dynamically or by default depending on the needs of the support matrix.
2. Feature detection of import then either uses SystemJS or `import()` to load main application.
3. Main application includes bundled polyfills 

So (1) and (2) can be just one round trip after the initial page load if inlining SystemJS script into the HTML, or two round trips if separated, in which case preloading hint headers for SystemJS itself can help.

To build polyfills into the main bundle you can rely on the fact that:

```js
import 'polyfill';
import app from 'app';
app();
```

will always respect execution order of imports - `polyfill` is guaranteed to execute before anything else. This is respected by build tools like RollupJS.

I agree it would be nice though to have a single idomatic way to do this in SystemJS, one could imagine a special `esmsrc` attribute on `systemjs-module` like say:

```html
<script type="systemjs-module" src="app.js" esmsrc="app-esm.js"></script>
```

The thing is though as you mention @seivan there are many different modules baselines - dynamic import / import.meta / import maps / etc. So a custom feature detection is likely best to ensure you're getting exactly what you want for now.

My main concern would just be making it too idiomatic that the fine-grained feature-detection work gets lost in translation - what seems like a useful benefit then becomes a constraining pattern.

**Comment by balloob** [comment]
For Rollup I have put on my to do list to explore a new plugin to allow registering entrypoints with a name, triggering self imports and injecting dependencies. So take the case where we have 2 entrypoints, "core" and "app", we could configure the plugin like:

```js
SystemJSRegisterNamed({
  // Entry per entrypoint name.
  // Each entry will get named after their public path.
  // Value is true or extra options
  core: true,
  app: {
    // If script needs to import itself as last call.
    // System.register("frontend_es5/app.js", …); System.import("frontend_es5/app.js");
    importSelf: true,
    // Inject dependencies on other entrypoints
    addEntrypointDependencies: ["core"]
  }
})
```

**Comment by seivan** [comment]
Thanks for getting back so quick @guybedford  and I appreciate the extra eyes on this. 

> The two-phase load is very much a necessity in the SystemJS case. As @joeldenning has pointed out, loading SystemJS even when not needed is a good approach.

I don't think it's a good idea to load it for modern browsers that would natively supports ES modules, as I said earlier, we make the "cut" at browsers that support Dynamic Import (`import()` syntax)  and **not** browsers that support `<script type="module">` because there is a lot of discrepancies.


> Another optimization to make is that polyfills can be included in the main RollupJS build fine - just not the polyfills needed by SystemJS.
> 
> The best load profile would look something like this:
> 
> 1. Initial HTML Payload includes inlined SystemJS. If needing to support IE11, those polyfills should be loaded dynamically or by default depending on the needs of the support matrix.

Here's the thing, in browsers/environments where `SystemJS` is actually needed would always needs polyfills. Since we use `core-js` for polyfills, we would need to make a bootstrap script as `IIFE` to include them.

It's almost similar to your suggestion.  

```js
import "necessary-polyfills-from-core-js"
import "systemjs"
```

And have your application and code split chunks to have their outputs as  `SystemJS`

```html
<script src="our-system-js-bootstrap.js">
<script src="app.js">
```


Slightly off topic, but Rollup doesn't let you do everything in a single build step 

 As `Rollup` doesn't let you write your build script in such way (assume pseudo config/code): 

Entry: `BootstrapSystemJS`, `MyApp`, `MyCodeSplitDashboard`,
Output: 
1) `BootstrapSystemJS` as  `IIFE` //And ONLY this file. 
2) `legacy_MyApp`, `legacy_MyCodeSplitDashboard` as `SystemJS`
3) `modern_MyApp`, `modern_MyCodeSplitDashboard` as `EsModules`

Instead you're forced to use their API to do multiple builds, because it doesn't give you a single entry and exit point. 
Meaning, any plugins that output hashes for CSP/sub-resource integrity, visualize dependencies or even just give you sizes of the various ouputs will not be clear.
It doesn't give you a single "here, here's all your stuff" since it's multiple builds, but this is off topic and for the most part Rollup works great. 



> 2. Feature detection of import then either uses SystemJS or `import()` to load main application.
> 3. Main application includes bundled polyfills
> 
> So (1) and (2) can be just one round trip after the initial page load if inlining SystemJS script into the HTML, or two round trips if separated, in which case preloading hint headers for SystemJS itself can help.



Now here's how a bootstrap actually looks like in a perfect setting with pseudocode generated at build time. 

Assume CSP hash is set in meta tags for scripts set as tags, as dynamic imports will inherit the permission. 



```html
//index.html
<script>
    var environmentSupportsDynamicImport = false;
    try {

    // Other approaches would fail CSP eval checks. 
    import("foo").catch(() => {});
    environmentSupportsDynamicImport = true
    } catch (e) {}
    
    if(environmentSupportsDynamicImport()) {
        //Dynamically add script tag for `modern_bootstrap.js` with type="module" 
    }

    else {
        // The reason they are split is because of cache busting. 
        // Dynamically add script tags for legacy: 
        // "systemjs_es5_polyfill_chunk.js"
        // "systemjs_vendor_chunk.js"
        // "systemjs_react_chunk.js"
        // "systemjs_app_entry.js" 
    }
</script>
```



```js
//"modern_bootstrap.js"
// This could have been a inlined script for type="module"
// But not all browsers support dynamic imports even with  type="module"
/ /Using `dynamicImport` as cutoff because imperfect support (Safari 10.1, etc)

// Check if this is a modern browser supporting ES Modules natively
// We technically are, so adding this for clarity in this sample.
if(environmentSupportsDynamicImport()) {

    // Controversial method of checking if this is a modern handpicked browser
    // The reason is to give per-browser polyfill, 
    // as latest Safari (13.0) still lacks a lot  compared to say latest Chrome.
    // So this makes evergreen modern browsers, smoothest performance. 
    const handpickedBrowserPolyfill = polyFillForBrowserAgent(navigator.agent)


   
    var polyfill  = undefined 

    // If this is not one of our handpicked browsers
    if (handPickedBrowserPolyfill === undefined) {
        polyfill = import("fat_es6_polyfill_chunk.js")
    }
    else {
        polyfill = import(handpickedBrowserPolyfill)
    }

    // Since code executes on fetch
    // we should make sure the polyfill is setup before parsing the rest. 
    polyfill.then( p => {

         // I am not sure this part is necessary,
        // They could technically be loaded on demand. 
        // But I am not sure how it works with dependencies that are not ESM.
        // or if there will be a heavier waterfall penalty. 
        Promise.all(["vendor_chunk.js", "react_chunk.js"].map(import)).then(deps => {
           import("app.js").then(x => x.run())
        })
    })
}

```

Now we're almost there, but there are some issues and questions and alterantives.
One is that the inline script checking `environmentSupportsDynamicImport` could also handle `modern_bootstrap` within its `try/catch` - though I am not sure how that would parse in legacy browsers that don't understand Promises even though it's a condition wrapped in `try/catch`.
Obviously arrow functions and such would not be there. 


The `legacy` portions is just a giant IIFE blob, because we need to load it in legacy browsers and I haven't found a way to make SystemJS work. 
That would be nice to tackle, but I am OK since this generally targets really old (or poor) browsers so I can live with it, but it would be neat not to without any intrusive changes.
Two downsides is that 
Older browsers don't get cache support for stuff that are often not updated. 
Older browsers don't get any code splitting. 

It's basically as you suggested (for `legacy`) 
```js
import 'polyfill';
import app from 'app';
app();
```


Now the reason `modern_bootstrap.js` doesn't do that is because, well I am not 100% sure but I am expecting caching to work better. 
If only `react_chunk.js` is updated,  then `app.js` shouldn't get cache busted and vice versa.

**Comment by seivan** [comment]
@guybedford Sorry to bother you again but I have some questions that the docs don't really answer.

First off, why is  `entry_legacy_bootstrap.js` downloaded twice when doing this: 
```html
    <script src="entry_legacy_bootstrap.js"></script>
    <script>
        System.import("./entry_legacy_bootstrap.js")
    </script>
```
Also, is there a way to make `systemjs` modules like `entry_legacy_bootstrap.js` be executable  when adding them as `scripts` tags,
`    <script src="entry_legacy_bootstrap.js"></script>`

Right now that loads a file that looks like 
```js
System.register([], function (exports, module) {
    'use strict';
    return {
        execute: function () {

            module.import('./chunk_application.js').then(function (n) { return n.a; }).then(function (app) {
                app.default();
            });

        }
    };
});
```

But adding it as a script doesn't trigger `execute`, I literally have to use `System.import`
In fact, I tried using `System.import` in a module Rollup bundled into `System.register` but it still didn't work. 

That being said, what is your recommendation on this, is it better to inline `System.import` into the html, or add a script tag instead that runs the whole thing?

**Comment by balloob** [comment]
@seivan look up the named register extra for SystemJS, it's what I talk about in the original post
