### ISSUE TITLE
Import map and gzip

### ISSUE THREAD

**Issue by bartoszgolebiowski** [systemjs/systemjs#2196]
- SystemJS Version: 
- Which library are you using?
  - [+] SystemJS
  - [ ] SJS
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
- Are you using any [custom hooks](/docs/hooks.md)?

Can I use inside import map gzip file instead of js file

```js
{
    "imports": {
      "single-spa": "https://cdn.jsdelivr.net/npm/single-spa@5.5.0/lib/system/single-spa.min.js",
      "react": "https://unpkg.com/react@16/umd/react.development.js",
      "react-dom": "https://unpkg.com/react-dom@16/umd/react-dom.development.js",
      "@bartek/root-config": "s3-url/bartek-root-config.gzip",
      "@bartek/portfolio": "s3-url/bartek-portfolio.gzip",
      "@bartek/navbar": "s3-url/bartek-navbar.gzip"
    }
  }
```

For production purposes.
### Question

**Comment by joeldenning** [comment]
Hi @bartoszgolebiowski - yes, you can gzip files. SystemJS loads modules via script tag, so normal rules apply.

Note that gzipping a file does not require changing the file extension - you can continue using `.js` files. The key is to configure your server to send the [`Content-Encoding: gzip` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding).

Closing this since I've answered the question - feel free to comment further or reopen.
