### ISSUE TITLE
Execution order of dependencies

### ISSUE THREAD

**Issue by TicoDePano** [systemjs/systemjs#2199]
### Description of Proposed Feature

As reported in issue #2099, the execution order of modules are not honored like in browsers. The download phase should download all files in parallel, but execution should respect the order defined in imports traversing the tree of dependencies. These seems to be the specification used in browsers, or at least how they work today (correct me if I am wrong).

### In what way would you use it?

I am using RequireJS in my projects today because it respects the execution order of dependencies, and I have a lot of them in many different formats. SystemJS is a lot better as a loader in my testes, but it is not dealing correctly with the dependencies when some of them were defined to run globally and depend on variables defined previously.

**Comment by joeldenning** [comment]
> As reported in issue #2099, the execution order of modules are not honored like in browsers.

The issue described in #2099 was related to order of execution of multiple top level imports via `<script type="systemjs-module"></script>`, not to the dependency tree of each module. We recommend using `System.import()` instead of `<script type="systemjs-module"></script>`, since it allows for full control over execution order of top level module imports.

> execution should respect the order defined in imports traversing the tree of dependencies

I agree! SystemJS already does, and even supports correct order of execution for circular dependencies. Here's some code below that shows this:

https://github.com/systemjs/systemjs/blob/d37f7cade33bb965ccfbd8e1a065e7c5db80a800/src/system-core.js#L218-L222

https://github.com/systemjs/systemjs/blob/d37f7cade33bb965ccfbd8e1a065e7c5db80a800/src/system-core.js#L233

Note that "post order" is the correct order of execution as defined by the ESM semantics.

**Comment by TicoDePano** [comment]
Thank you for your quick reply, I appreciate.
In my tests, I used both strategies, `System.import()` and `<script type="systemjs-module"></script>`. The first was a little more stable when used in a page with multiple imports, but I ended using only one script per page and `System.Register()` handling all my dependencies.

I had some problems when referencing an IIFE script that has a dependency on jquery, for example, where it executes with an argument of jQuery, and even waiting the import Promisse, it fails because sometimes jquery delayed to set that variable. Seems that the instantiation of the scripts do not obey the order, wich was what I understand in #2099.

I will try to create a simple project at the weekend causing the error deterministically, but it happens with SystemJS and not with RequireJs.

Thank you again for your support.
