### ISSUE TITLE
[Question] Minimal or Simple Example SystemJS with Angular 9 Ivy 

### ISSUE THREAD

**Issue by aelbore** [systemjs/systemjs#2205]
- SystemJS Version: latest
- Which library are you using?
  - [X] SystemJS
  - [ ] SJS
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
- Are you using any [custom hooks](/docs/hooks.md)?
No

### Question
Is Possible or have Minimal example code for Angular 9 Ivy for SystemJS?

**Comment by joeldenning** [comment]
**Short answer**:

No. Ivy Compiler forbids in-browser sharing of core angular dependencies.

**Longer explanation**:

Breaking changes to the Ivy Compiler's in-browser API are not considered breaking changes in Angular's semantic versioning. It is technically possible, although deeply discouraged by the Angular team, to share the Ivy runtime between disparate projects so long as you're on exactly the same version of Angular in each project. To do so, you'd need to create and publish a POST_R3 version of the core angular repos, which is strongly discouraged by the Angular team. I also would not recommend it, having tried it myself.

**Even longer explanation:**

https://twitter.com/Joelbdenning/status/1253781652486017024.

**Side note / alternative**:

If you're using View Engine, you can use the official UMD bundles or you can use the SystemJS versions that I have created and maintain at https://github.com/esm-bundle/

I am closing this, since I've answered the question. But feel free to comment further / reopen.
