### ISSUE TITLE
How to express entry point for systemjs ?

### ISSUE THREAD

**Issue by wenerme** [systemjs/systemjs#2218]
### Question
I want to express the entrypoint for systemjs in package.json, is there any existing spec for this ?

I found the conditional exports in package.json https://nodejs.org/api/esm.html#esm_conditional_exports
This might be a good candidate

```json
{
  "main": "./main-require.cjs",
  "exports": {
    "import": "./main-module.js",
    "require": "./main-require.cjs",
    "system": "./main-system.js"
  }
}
```

**Comment by guybedford** [comment]
This is a good question and a syntax like you are suggesting would be the way to do this.

But - this is not an encouraged pattern! Rather publish ES modules and then use System modules as a production step rather than publishing System modules.

The reason for this is that ES modules are far better to optimize than System modules and also more portable. So System modules should always be a final production step performed by the end user to avoid these problems.

We should probably try to include this guidance somewhere as it is not obvious certainly.

**Comment by wenerme** [comment]
Thanks your opinion, trying to auto  [bundle some packages](https://github.com/wenerme/rollups/tree/master/packages)(like esm bundles but simpler for me), want to express the system entry in package.json.

System for production, but like `react.production.min.js`,maybe some external dependencies don't need to bundle, just one line of import map will do most work, easier to upgrade and leverage cdn. ems is easier for bundle when using in project, but systemjs can not import it unless setup some transpile(or maybe I am wrong ?).

Why I want to bundle system, is make a library like web-component, just import and then works, like [this](https://wenerme.gitlab.io/apis/lite.html#/lab/modules)

Or maybe just build umd is enough ? Is there any different between umd bundle and system bundle ? except for the requirement of some `extras` systemjs dependency.
