### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by crfrolik** [systemjs/systemjs#2219]
- SystemJS Version: 6.4.0
- Which library are you using?
  - [x] SystemJS
  - [ ] SJS
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
- Are you using any [custom hooks](/docs/hooks.md)?

### Question

I am trying to use SystemJs to support dynamically loading a module at runtime. Most of my app is compiled via webpack but I want to support runtime plugins.

So, basically (simplified for brevity):

```
// compiled by webpack

import * as lodash from 'lodash';
window.define('lodash', [], () => lodash);

const SystemJs = window.System;

SystemJs.import('/plugin.js');
```

`plugin.js`:
```
import * as _ from 'lodash';

const thingy = 1234;

export {thingy};
```

I get an Uncaught `SyntaxError: Cannot use import statement outside a module` from this.

I am probably missing something obvious but after searching StackOverflow I'm still not sure what it is.

**Comment by joeldenning** [comment]
Hi @crfrolik, good question. ESM modules are not currently supported in SystemJS ([docs](https://github.com/systemjs/systemjs/blob/master/docs/module-types.md) [explanation video](https://www.youtube.com/watch?v=AmdKF2UhFzw)). The reason is that SystemJS cannot implement import maps in ES modules, since ES specifier resolution is not modifiable in browsers. Additionally, allowing ESM means that there are two separate module registries - the SystemJS registry and the browser registry.

Limited support for ESM has been worked on in https://github.com/systemjs/systemjs/pull/2187, however there is currently an issue described in that PR that is delaying it being merged.

I'm closing this issue since I believe to have answered the question, but feel free to comment further or reopen.
