### ISSUE TITLE
Function is unexpectedly transformed into Object

### ISSUE THREAD

**Issue by fxxjdedd** [systemjs/systemjs#2241]
### Demonstration
```
typeof System.get('https://cdn.jsdelivr.net/npm/vue@2.6.11/dist/vue.min.js')
```
Enter this line directly in the console, will get a `object` type. But in fact, Vue should be a function.

This caused me to get a `Super expression must either be null or a function` error when using `vue-class-component`:

```
import Vue from 'vue'
export default MyComponent extends Vue {}
```

### Expected Behavior
typeof Vue is `function`
### Actual Behavior
typeof Vue is `object`

**Comment by joeldenning** [comment]
Hi @fxxjdedd, good question. This is expected behavior - let me explain.

SystemJS maintains a module registry, where each module is an ES module. ES modules are always objects (often referred to as "the namespace") that do not have any methods on their prototype. The ES module spec does not allow for a module to be a function.

SystemJS supports [a variety of module formats](https://github.com/systemjs/systemjs/blob/master/docs/module-types.md) and converts each of them into an ES module. In the case of global variables and AMD modules (which is the format that Vue 2 is published in), SystemJS will convert the `Vue` function into an ES module by making `Vue` a default export.

This behavior matches the Vue docs - see https://vuejs.org/v2/guide/installation.html#CDN. Notice how the Vue function is imported via `import Vue from 'https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.esm.browser.js'`, where `Vue` is the default export from the ES module.

One thing to note is that if you're using webpack to compile to System.register format, have code that does `import Vue from 'vue'` where `'vue'` is marked as a webpack external, that there was a bug in webpack 4 that caused problems. That bug was fixed in https://github.com/webpack/webpack/pull/10503 and released in https://github.com/webpack/webpack/releases/tag/v5.0.0-beta.15. If upgrading to webpack 5 is difficult or undesireable for your case, [this __esModule extra](https://github.com/react-microfrontends/api/issues/1#issuecomment-594289086) works around the webpack bug with a custom SystemJS extra.

**Comment by fxxjdedd** [comment]
@joeldenning Great explanation
I fixed the problem this way, but I am not sure why? Is it because I exported `Vue` as a partial export to avoid the webpack4 problem?

@spa/root
```
{
  imports: {
    vue: 'https://cdn.jsdelivr.net/npm/vue@2.6.11/dist/vue.js',
    @spa/shared-libs: '...',
  }
}
```
@spa/shared-libs
```
export { default as Vue } from 'vue'
```
@spa/page
```
import { Vue } from '@spa/shared-libs'

// works!
export default class Page extends Vue {}
```

**Comment by joeldenning** [comment]
This depends on how you've configured webpack's output.libraryTarget option. Your `@spa/shared-libs` is able to import Vue as default, so my guess is that the module format is not `system`.

Either way, it sounds like you've got things working so I am going to close this issue.
