### ISSUE TITLE
Allow script type to use importmap media type for future spec compatibility

### ISSUE THREAD

**Issue by felipeplets** [systemjs/systemjs#2252]
- SystemJS Version: 
- Which library are you using?
  - [X] system.js
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?
No

### Question
I wonder why `<script type="importmap">` is not supported as this is the proposed spec. I understand for historical reasons we may use the type `systemjs-importmap` but as Import Maps gets more used, I understand it will become more like a Polyfill library providing the Import Map functionality and API for browsers that does not support it natively. In this case I would assume that SystemJS goal should be to easily transition on a more spec related language and thus supportung importmap media type.

**Comment by joeldenning** [comment]
Hi @felipeplets, good question. I don't view `systemjs-importmap` as existing for historical reasons, but rather for compatibility reasons. Since SystemJS does not support ES module syntax, but native browsers only support ES module syntax. So an import map with ES modules won't work with SystemJS and an import map with System.register modules won't work with browsers. If we used `type="importmap"`, the code would likely break as browsers add support for import maps.

**Comment by felipeplets** [comment]
@joeldenning thanks for the explanation, I wasn't aware of this fact.
