### ISSUE TITLE
Systemjs / Global loading broken with defer

### ISSUE THREAD

**Issue by tristanlins** [systemjs/systemjs#2298]
### Demonstration

Code Sandbox: https://codesandbox.io/s/angry-shannon-o3ncs?file=/index.html:546-558

### Expected Behavior

Systemjs and global loading works fine.

### Actual Behavior

When include `<script src="system.js" defer></script>` with `defer`, the loader goes crazy.
In chrome sometimes nothing happens (especially in incognito tabs) or instead of the module, `window` is returned.
In firefox you get an empty module object.

The strange think is that the amd extra fixes the error.
(just try to comment in the script tag)

**Comment by joeldenning** [comment]
The cause of this is https://github.com/systemjs/systemjs/issues/2040. We don't generally recommend using `systemjs-module` because of the race condition described there. It's also worth noting that `import:` urls have been removed from the official import maps spec, which is another reason not to use them.

The bug is that the `systemjs-importmap` script is being processed before the systemjs global extra is executed, since import-maps.js is executed before the global extra. By marking the systemjs script as deferred, the `systemjs-module` element will be present on the page before system.js executes.

**Comment by tristanlins** [comment]
Okay, I solved this by using `<script>System.import(..)</script>`
