### ISSUE TITLE
SystemJS Load errors while loading the JS Assets (vendor.js)

### ISSUE THREAD

**Issue by saak23** [systemjs/systemjs#2311]
@guybedford  and team,
I have an angular app which uses systemjs. It has multiple assets - e.g. vendor, main, runtime, polyfills & polyfills-es5.
I wanted to download these assets before main.js and below is the sample code snippet,

Promise.all([ System.import('runtime'), System.import('polyfills'), System.import('polyfills-es5'), System.import('vendor'), System.import('main') ]) .then(function(modules) { ... })

With above approach, sometimes (intermittently) seeing load errors like below in production, 
Then I changed the implementation and Now I am using **depcache** to load all these assets.
To my surprise after we deployed into production with **depcache** , the Load error count on vendor.js file is drastically increased and users unable to load the application in production and this issue is intermittent 

Error:
Error loading https://my.cosmos.com/A/d/vendor.js (SystemJS Error#3 https://git.io/JvFET#3) Stack:https://my.cosmos.com/Lib/system.min.js:1:5914

SystemJS line : u.addEventListener("error",function(){o(Error(e(3,"Error loading "+t+(n?" from "+n:""))))})

Current production code is having "depcache" implementation. But still seeing these errors.

Is there an alternative or recommended solution that I can use? I feel like I'm missing something obvious.

**Comment by joeldenning** [comment]
webpack bundles often require being loaded in a specific order, but `Promise.all()` does not guarantee order. When loaded in the wrong order, it can cause problems.

With webpack projects, I generally use webpack dynamic `import()` to cause code splits rather than the `optimization` config which results in code splits that are not loadable through a single entry point. Here's some documentation for some changes to the webpack config you can make to get your webpack project loadable by systemjs: https://single-spa.js.org/docs/recommended-setup#build-tools-webpack--rollup

**Comment by saak23** [comment]
Hello @joeldenning : 
My angular application application is very big and we cannot convert all assets into on single JS asset.
Instead, our production code is like below as recommended alternative solution to Promise.all().
**Code snippet:**
`var importData = fs.readJsonSync(importMap);
            importData.imports["@cosmos/myApp-load"] = "/App/dist/" + file;
            importData.depcache = {
                "@cosmos/myApp-runtime": ["@cosmos/myApp-polyfills-es5", "@cosmos/myApp-polyfills", "@cosmos/myApp-vendor", "@cosmos/myApp-main"]
            } `

With the above solution below exception related to vendor.js has been increased a lot and blocking the customer to load the application intermittently. (200 users per day)
**Error details:**
Error loading https://my.cosmos.com/A/d/vendor.js (SystemJS Error#3 https://git.io/JvFET#3) Stack:https://my.cosmos.com/Lib/system.min.js:1:5914

SystemJS line : u.addEventListener("error",function(){o(Error(e(3,"Error loading "+t+(n?" from "+n:""))))})

Can you please help us? Thanks

**Comment by joeldenning** [comment]
> Error loading https://my.cosmos.com/A/d/vendor.js (SystemJS Error#3 https://git.io/JvFET#3)

SystemJS Error 3 is documented in the URL shown in the stacktrace (https://git.io/JvFET#3). The error could be caused by https://my.cosmos.com/A/d/vendor.js throwing an error during its initial execution. A potential cause for why it would intermittently throw an error during its initial execution is a network race condition. The `vendor.js` file may require that other parts of the webpack bundle execute first, but your code does not ensure order of execution. The depcache code you shared above does not ensure order of execution.

To force order of execution, you can chain system imports:

```js
// force one chunk to be loaded first
System.import('webpack-chunk1.js')
.then(() => System.import('webpack-chunk2.js'))
// if some can be loaded concurrently, do that with promise all
.then(() => Promise.all([System.import('webpack-chunk3.js'), System.import('webpack-chunk4.js'))
```

Like I mentioned above, webpack's `optimization` config is entirely tied to html-webpack-plugin and/or webpack-manifest-plugin. Wanting `optimization` without using either of those plugins is just not how webpack is designed, and is why you're running into issues. You'll have to forcibly load the files in order as shown in the code above, to simulate what html-webpack-plugin does when it enforces order of execution.

**Comment by saak23** [comment]
Thanks a lot @joeldenning
