### ISSUE TITLE
[BUG] Import race condition on Safari and iOS

### ISSUE THREAD

**Issue by ardeois** [systemjs/systemjs#2323]
First, thanks for this SystemJS library, it really useful for us 🙏 
Unfortunately, I found a bug on Safari which seems pretty bad ?

### Demonstration
We have at my company a strange bug where SystemJS is not providing the correct content on **Safari** and **iOS** only

Here is the scenario:
- the app entry point calls `System.import('angular')`
- Meanwhile, the entry point is also inserting bing snippet in scripts (`bat.js`)
- Bing snippet is resolved
- SystemJS provides `angular` module with the content of `bat.js` 🤯 

Repo to reproduce:  https://github.com/ardeois/systemjs-import-race-condition-bug
Note you need to refresh the browser once in order to reproduce. It seems like the race condition happens when the scripts are loaded from cache

### Expected Behaviour

`angular` module provided by SystemJS should correspond to what the import map has defined

![systemjs-expected](https://user-images.githubusercontent.com/1867939/116279222-45339800-a755-11eb-81a9-59183123f686.png)

### Actual Behaviour

`angular` module provided by SystemJS corresponds to `bat.js` content

![systemjs-actual](https://user-images.githubusercontent.com/1867939/116279233-482e8880-a755-11eb-87f3-64025aebf6ae.png)

This is a pretty bad problem, but I'm not sure how to fix it as I'm not familiar to SystemJS source code
But don't hesitate to give me pointers if you want me to help.

### Environments
SystemJS: 6.8.3
Safari: 14.0.3
MacOS: 10.15.7

**Comment by guybedford** [comment]
I just had a quick look at this and it's actually not a bug - this is the way the global detection works.

In the example, `bat.js` is defining the global `UET` and `angular.js` is defining the global `angular`.

Because SystemJS is unaware of the loading cycle of `bat.js` it can't guarantee that it will correctly detect the angular import if the other global is loaded at the same time.

The reason for this is that SystemJS global detection uses a snapshot created at the time of **import**. This is not racy if SystemJS is loading all global scripts as it can update its snapshot synchronously with each script load fine.

But it **is a race** if you are loading another global at the same time that SystemJS does not know about.

To fix this you have a couple of options:

1. Load a UMD / AMD or SystemJS module format for Angular. Angular provides UMD distributions for these use cases which you can use. These formats can never be racy with other loads unknown to SystemJS.
2. Load the `bat.js` script with SystemJS itself by adapting the loader to get `UEF` via a `System.import('https://bat.bing.com/bat.js')` in the first place.

**Comment by ardeois** [comment]
Thanks for the explanation @guybedford that's pretty clear.

I will probably use option #1 as option #2 is not possible for my use case.

But if I understand well:
- SystemJS imports `angular.js` module from CDN
- it detects it's NOT an UMD/AMD module format, so it does global detection, is that it?

To solve it, if I use an UMD/AMD module, would SystemJS still do global variable detection?
From what I've seen, even if I use an UMD module for angular.js, it will still set `window.angular` global variable, would that be fine with SystemJS?

I've done a test, and it does fix the issue indeed but I want to make sure I understand how it works internally.

Thanks a lot for taking the time and the explanation !

**Comment by guybedford** [comment]
(2) seems possible to me looking at the script but may require rewriting the Bing wrapper there.

But yes (1) is fine too. That's exactly how it works - the global detection is the fallback only when no System or AMD modules are triggered.

**Comment by ardeois** [comment]
perfect thanks !

yes in my case (2) is not possible because we use Segment.io to load bing, so I don't have control on the Bing wrapper
Thanks again,

Closing the bug then
