### ISSUE TITLE
Node loader might eval script in wrong scope

### ISSUE THREAD

**Issue by loynoir** [systemjs/systemjs#2345]
### Demonstration
Modified version of 

https://github.com/systemjs/systemjs-examples/blob/bf70097688e4c062683d31c9f58399aee6747a49/systemjs-features/nodejs-loader/index.js#L11

```js
const url = require('url');
const { System, applyImportMap, setBaseUrl } = require('systemjs');

// Setting base URL is optional - the default is to use process.cwd()
// so the code here is redundant
const basePath = url.pathToFileURL(process.cwd()).href;
setBaseUrl(System, basePath);

applyImportMap(System, {
  imports: {
    'systemjs-babel': 'https://cdn.jsdelivr.net/npm/systemjs-babel'
  }
});

(async () => {
  const systemjsBabel = await System.import('systemjs-babel')
  console.log(systemjsBabel)
})();
```

### Expected Behavior
no error

### Actual Behavior
```txt
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'System' of undefined
```

### Related
https://github.com/systemjs/systemjs/issues/2344

**Comment by joeldenning** [comment]
This isn't a problem with systemjs nor how it evals things. It is not related to #2344.

Instead, it's that systemjs-babel doesn't currently work in NodeJS. Additionally, systemjs-babel sets up systemjs extras and therefore should not be installed via `System.import()` (since all extras should be installed before the first System.import.

To verify this, I added `require('systemjs-babel')` to the systemjs-examples/systemjs-features/nodejs-loader/index.js file and it throws the same error as if you `System.import('systemjs-babel');`. The problem seems related to how the systemjs-babel code detects the current global variable - it seems to be undefined in nodejs but `window` in browsers.

I suggest opening an issue on systemjs-babel rather than here - I'm not sure if systemjs-babel was ever intended to work in NodeJS or how difficult it would be to make it work in Node, but a github issue on that repo would be the best place to discuss.
