### ISSUE TITLE
Adding Option to Retry when Downloading Module Fails

### ISSUE THREAD

**Issue by kykwak** [systemjs/systemjs#2348]
Hi @joeldenning and @guybedford, I wanted to suggest 2 things:
1. Adding an option to set a timeout or having a default timeout before trying to resolve the import map. There are times when we get the [unable to resolve bare specifier error](https://github.com/systemjs/systemjs/blob/main/docs/errors.md#8) when the server takes longer to return our import map. Maybe it would help if we were able to wait for some time until the import map response is available?

2.  A feature where developers can have the option to pass a custom error handling function (like a retry) when faced with [an error downloading a module](https://github.com/systemjs/systemjs/blob/main/docs/errors.md#3).

 * There is a somewhat similar feature for passing an [error handling function for import maps] (https://github.com/systemjs/systemjs/blob/main/docs/import-maps.md#handling-import-map-errors). 

* It would be nice if we could use this feature to invoke a retry for users who may have failed to download a module due to some network issue.
* If any error event was passed to the error event listener, we would be able to log additional information -- which could help with debugging underlying issues

Could you provide any thoughts or suggestions for the 2 points above? Thanks.

**Comment by joeldenning** [comment]
I think everything you want is already possible with the existing SystemJS api. For that reason, I'm closing this issue, but feel free to comment further or reopen.

> Adding an option to set a timeout or having a default timeout before trying to resolve the import map. There are times when we get the unable to resolve bare specifier error when the server takes longer to return our import map. Maybe it would help if we were able to wait for some time until the import map response is available?

SystemJS does not attempt to resolve specifiers until all import maps on the page have fully loaded. This is in accordance with the import maps spec. It does this via the `prepareImport()` function, which returns a promise that doesn't resolve until all import maps are loaded. If you are injecting import maps into the DOM dynamically, be advised that this only works before the first `System.import()` (or System.prepareImport()) is called. We do this because it's part of the import maps spec. If you need to deviate from that behavior, you can call `System.prepareImport(true)` or use the dynamic-import-maps extra which allows injection of import maps after the first module load has started. Calling `System.resolve()` before `System.prepareImport()` fulfills is not supported for bare specifiers .

> A feature where developers can have the option to pass a custom error handling function (like a retry) when faced with an error downloading a module.

You can call `System.import('name').catch(err => {})` to handle errors for any specific import. To handle at a general level, you can hook the `error` event on the `<script>` elements created by systemjs by hooking the `createScript` function. See https://github.com/systemjs/systemjs/blob/main/docs/hooks.md#createscripturl---htmlscriptelement and https://developer.mozilla.org/en-US/docs/Web/API/Element/error_event.

For retrying, call `System.delete(url); System.import(url)`

**Comment by kykwak** [comment]
Hi @joeldenning,

I have a question regarding the first point on not resolving specifiers until the import maps finished loading. In the processScripts() function, I see that in the handling of systemjs-importmap scripts we could either get this [W4 error](https://github.com/systemjs/systemjs/blob/main/docs/errors.md#W4) or get this [invalid status code error](https://github.com/systemjs/systemjs/blob/47c3afb0c748b263ee4c28e9eea547e3313a40e1/src/features/import-maps.js#L51). 

However we don't seem to be getting either of these error messages in our logs and instead see network fetch errors while calling the import-map (mostly on mobile browsers which do support fetch) and subsequently the [bare specifier error](https://github.com/systemjs/systemjs/blob/main/docs/errors.md#8). 

Would you have any pointers on why this could be happening?

**Comment by kykwak** [comment]
Hi @joeldenning,

I have a question regarding the first point on not resolving specifiers until the import maps finished loading. In the processScripts() function, I see that in the handling of systemjs-importmap scripts we could either get this [W4 error](https://github.com/systemjs/systemjs/blob/main/docs/errors.md#W4) or get this [invalid status code error](https://github.com/systemjs/systemjs/blob/47c3afb0c748b263ee4c28e9eea547e3313a40e1/src/features/import-maps.js#L51).

However we don't seem to be getting either of these error messages in our logs and instead see network fetch errors while calling the import-map (mostly on mobile browsers which do support fetch) and subsequently the[ bare specifier error](https://git.io/JvFET#8).

Would you have any pointers on why this could be happening?

**Comment by joeldenning** [comment]
I don't know of any reason why `throw Error()` would behave differently on phones vs desktop.

**Comment by kykwak** [comment]
Hi @joeldenning, 

The behavior is the same on both phones & desktops -- where we get a network error instead of the "invalid status code" or W4 errors. We observed that behavior was just happening more frequently on phones than on desktops. 

We haven't been able to reproduce/invoke a network fetch error on the import map in our testing environments. Just wanted to ask if you have ever came across or read about a similar network fetch issue when handling the systemjs-importmaps. Thanks for the quick response

**Comment by joeldenning** [comment]
No I haven't heard of this issue before. SystemJS listens to the `error` event for `<script>` elements, or to `fetch().catch()` if it's transforming the code before executing it. It sounds like that error event is possibly not firing for you? Not sure what it would be
