### ISSUE TITLE
how to skip importmap.json fetch error 

### ISSUE THREAD

**Issue by wei294597950** [systemjs/systemjs#2351]
![image](https://user-images.githubusercontent.com/26248332/126589915-ba561578-61ee-4725-a84c-9398e6cb3777.png)
when the script.src  can not fetch and fetch return 503. my program break ,how can i skip  the error  so that my page can still work

**Comment by joeldenning** [comment]
If your app relies on the import map to work, then there is nothing that can be done to make it continue working when the import map fails to load. However, I've put together a few notes below about things that might be helpful for you.

### SystemJS behavior for failed import maps

When an import map fails to load, SystemJS just ignores it and continues processing the other import maps on the page. So if you have multiple import maps on the page, you can continue using importing the modules from the import maps that loaded even though one of the import maps failed to load.

### Retrying

If you want to retry downloading the import map, you can use `onerror` and `System.prepareImport(true)`.

```js
<script>
  (function () {
    let numRetries = 0;
    window.handleImportMapError = function () {
      if (++numRetries > 2) {
        // avoid inf loop of retries
        return;
      }
      
      var script = document.getElementById('my-importmap')
      // delete the marker placed by systemjs that prevents refetching import maps
      delete script.sp
      // Tell systemjs to reprocess all import maps
      System.prepareImport(true).then(() => {
        System.import('app');
      })
    }
  })()
</script>
<script id="my-importmap" type="systemjs-importmap" src="/my-importmap.json" onerrorr="handleImportMapError()"></script>
<script>
  System.import('app')
</script>
```

### Inlining

Rather than having the browser fetch the import map, you can inline it into the HTML file. This is often best for performance. If the import map changes dynamically, a popular option is to have a nodejs server fetch the import map on an interval and then inline it into the HTML file for each incoming HTML request. See https://single-spa.js.org/docs/create-single-spa#single-spa-web-server-utils for a package that can help with this.

I'm closing this issue as I think I've answered the question and there's no bug or missing feature within systemjs for this.
