### ISSUE TITLE
system.min.js:4 Uncaught (in promise) Error: Unknown module type "text/html" (SystemJS Error#4 https://git.io/JvFET#4)     at system.min.js:4

### ISSUE THREAD

**Issue by race616** [systemjs/systemjs#2367]
- SystemJS Version: 
- Which library are you using?
  - [ 6.8.3] system.js
  - [ ] s.js
  - [ 8.12] system-node.cjs
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [√ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?

### Question
Throw an error **### **### “system.min.js:4 Uncaught (in promise) Error: Unknown module type "text/html" (SystemJS Error#4 https://git.io/JvFET#4)at system.min.js:4”****

**Comment by joeldenning** [comment]
Please see https://github.com/systemjs/systemjs/blob/main/docs/errors.md#4 which explains the error. It means that the URL being loaded as a javascript module actually returned html rather than javascript. SystemJS looks at the `content-type` http response header and throws Error 4 when the `content-type` isn't correct. A common reason why this happens is that the URL is incorrect and the server is configured to return a default HTML file for any files that don't exist.
