### ISSUE TITLE
Synchronous import with SystemJs

### ISSUE THREAD

**Issue by jbe456** [systemjs/systemjs#261]
I know there is already a ticket with the same title (https://github.com/systemjs/systemjs/issues/191) but it looks like there is no solution provided for the initial requirement.

I have an ES6 library that I transpile in ES5 using Traceur. In the end, I would like anybody to be able to use my library either with CommonJS, AMD or directly as a root variable. All the code is downloaded once and available at the time I do get the module.

I tried this but it doesn't work because modules are loaded asynchronously 

```
(function (root, name, definition) {
    if (typeof module != 'undefined') {
        module.exports = definition();
    } else if (typeof define == 'function' && typeof define.amd == 'object'){
        define(name, definition);
    } else {
        root[name] = definition();
    }
}(this, 'ApplicationName', function() {
    var MyApplication = System.get('MyApplicationBootstrap').default;
    return new MyApplication();
}));
```

So for now I ended up doing a jQuery like syntax with an `onReady` method. But it's ugly to have an asynchronous call once the library is loaded in the AMD. It should come ready to use.

Am I misusing the System.js library ? is it impossible ?

**Comment by trusktr** [comment]
@guybedford [HTML Imports](http://www.html5rocks.com/en/tutorials/webcomponents/imports/) load HTML/CSS/JS synchronously. It would be great to do the same with System.import to be able to provide the same use cases as HTML imports, because mixing the two just seems like a dumb thing to do.

Basically, if it were possible to have a synchronous System.import (or alternative) then we could do with that everything that HTML imports let's us do (without using HTML imports).

Is it possible to write a synchronous import method in JavaScript?

Will System.js APIs be part of browsers some day?

**Comment by pkozlowski-opensource** [comment]
@trusktr wouldn't it mean "freezing" the whole browser in the middle of a user flow (I would assume that people might want to use System.import in the middle of they app to lazy-load code for example)?

> Will System.js APIs be part of browsers some day?

Loader spec is being worked on here:  https://whatwg.github.io/loader/,

**Comment by trusktr** [comment]
@pkozlowski-opensource Of course. What I mean is that we should be able to choose. In HTML Imports, those things are synchronous, so by using that, it similar to plopping `<script>` tags into a page. But, I'd rather be able to use `System.import` (with module handling) rather than plop `<script>` tags into a page and rather than use HTML imports. Maybe having something like `System.import(..., true)` could mean it is synchronous.

See what I mean?

**Comment by 0xorial** [comment]
Does anyone have workaround meanwhile?

**Comment by jamesj2** [comment]
I haven't found a good solution to the synchronize import issue for my legacy apps.  So I ended up using the promise from System.import.  Yes you'll still have a bunch more refactoring but it's for the better right?

```
System.ready = System.import('/bootstrap').then(function () { ... }
System.ready.then(function() { ... });
```

vs

`$(document).ready(function () { ... });`

**Comment by trusktr** [comment]
I take back what I said earlier about having an option to load synchronously.

Instead, we can use async functions (or generators in browsers that don't support async functions yet or if we don't want to transpile async functions) to load scripts "synchronously":

```js
async function loadScripts() {
  await System.import(...)
  await System.import(...)
  await System.import(...)
  await System.import(...)
  await System.import(...)
}

async function main() {
  await loadScripts()
  console.log('Done loading scripts in order')
}

main()
```

**Comment by Ciantic** [comment]
It would be beneficial if this was doable without a build step. Preferably just monkey patching System.Js for certain modules.

For instance I want to develop my WordPress blocks as a modules, and use modern way to import but they have painted themselves in the corner (by not using System.js or something similar in the first place https://github.com/WordPress/gutenberg/issues/2768 )

**Comment by joeldenning** [comment]
Hi @Ciantic, this is a really old issue that applies to a really old version of systemjs.

With the newer versions of systemjs, including systemjs@6, the following works:

```js
// not synchronous, but the code looks synchronous
const foo = await System.import('foo')

// fully synchronous, but only works if the module is already downloaded
const foo = System.get(System.resolve('foo'))
```

Downloading javascript files is inherently asynchronous and the dynamic import browser spec calls for asynchronous loading of files. So it is not possible nor desireable to deviate from that spec. The [`System.get()` api](https://github.com/systemjs/systemjs/blob/master/docs/api.md#systemgetid---module) is as far of a deviation from the spec as we'd be willing to go.

Normal `import foo from 'foo'` imports can still be written in a synchronous way, so long as they are compiled to System.register, amd, or global format. See [docs](https://github.com/systemjs/systemjs/blob/master/docs/module-types.md).

> It would be beneficial if this was doable without a build step
There is no build step required for any of the options I've described above. If I am misunderstanding what you're trying to accomplish, let me know. I tried to give an overview of relevant information, but might have missed something specific to what you're trying to accomplish.

**Comment by Ciantic** [comment]
@joeldenning thanks a lot! I didn't know it was possible, maybe it's such a odd case that it's not documented, or I couldn't find it.

**Comment by dgreene1** [comment]
If anyone wants to see an example of @joeldenning's first solution, it looks like this:
```ts
import type * as SingleSpaNamespace from 'single-spa';

const singleSpaInstance = await System.import<typeof SingleSpaNamespace>('single-spa');
```

But I would like to caution people to make sure that the version that lives in their script tag or in their import map is the same version as your @types that you've defined in package.json. Otherwise, the type will not match the runtime shape.
