### ISSUE TITLE
Plugin proposal

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#287]
The proposal is to allow plugins to be specified via meta syntax thereby removing the need for syntax in import statements.

We will still support plugin syntax through `!` as well though.

Previously I would write:

app.js
```javascript
import 'style.css!';
```

Now this could be done with:
```javascript
System.config({
  modules: {
    '*.css': { plugin: 'css' }
  }
});
```
app.js
```javascript
import 'style.css';
```

**Comment by nevir** [comment]
If two wildcards match, IMO it should be the most specific one (longest char length), or first if equally specific

**Comment by trentgrover-wf** [comment]
+100

I've just come up with a use case that this would apply well to.  I'd like to be able to use System loader plugins to get reasonably quick refresh in browser when operating in 'dev' mode (JSX / TS loading), but then would like to easily switch to a non-plugin based version for actual production output (transpile the JSX / TS down to JS for bundling / deployment).

Currently, if I import a JSX file using the JSX plugin:
```
System.import('src/shell.jsx!').then(...);
```
but that JSX file references other JSX files, the JSX loader doesn't automatically apply to the child JSX file being referenced like this:
```
var RightPane = require('./components/RightPane');
```

Of course, it works correctly if I change the child require to this:
```
var RightPane = require('./components/RightPane.jsx!');
```

When switching between dev mode and prod mode, it wouldn't be reasonable to search out and replace all those requires, but it would be reasonable to change all requires to include the file extension:
```
var RightPane = require('./components/RightPane.jsx');
```
Then switch between the 2 modes by swapping the global system config between these 2 options:
```
'*.jsx': { plugin: 'jsx' }
OR
'*.jsx': '*.js'
```

**Comment by guybedford** [comment]
@trentgrover-wf great to hear that. Have been working on clearing the decks to get to this loader work for a while, goal is to get it done in Feb. You may not even need this switch as well, as plugins support building so this comes for free when bundling. The new systemjs compile server work would automate this separate file plugin precompilation as well.

**Comment by Thecontrarian** [comment]
it seems like this wouldnt really be an issue if we just exposed the normalize step of the es6-module-loader as defined here https://github.com/ModuleLoader/es6-module-loader/wiki/Extending-the-ES6-Loader to plugins. am i wrong?

**Comment by ocombe** [comment]
I think that it would be nice if the plugins could be chained, if two regex match then both should be used, because sometimes you might want to use two plugins on the same file.
It's up to you to make sure that if you want to exclude some files from your regex, you should do that in your regex.

**Comment by guybedford** [comment]
@ocombe can you give an example of where two plugins would be needed? I can't think of a single example myself to justify the use case.

**Comment by ocombe** [comment]
I'm not entirely familiar with the full extend of the plugin possibilities, so this might be a false example, but let's say that you have a plugin that handles the cache breaker, and another one that handles the transformation of the file (coffee to js).
Or maybe you have a plugin that will import the css file, and another one that will parse this file and check for font import and import them.

**Comment by guybedford** [comment]
@ocombe with the loader we have two ways of adding functionality - through the loader hooks and through loader plugins. Things like cache breakers can be done through a loader hook extension of the loader itself.

Loader plugins for combined operations like multi-stage transpilation are best implemented, in my opinion, through creating a plugin that consists of the composition of those steps. But if there are examples that show this is inadequate that would be great to hear.

**Comment by Thecontrarian** [comment]
I know this is sort of the question you're never supposed to ask but what
are we thinking for a possible timeline to releasing this sort of
functionality? I ask because I have a react project that I'm sort of
chomping at the bit to convert from using browserify to jspm, but I have a
dependency that uses jsx very liberally and requires the files by name
using a require('component.jsx') convention internally and jspm breaks when
it tries to build my project cus it can't find 'component.jsx.js'.

If there is no clear timeline for release, or if the timeline is sort of
far off, is there something that I can do in the meantime to make it work,
besides forking the dependency and rewriting all of the require calls to
end in '!' ?

**Comment by guybedford** [comment]
If you really want to hack in the functionality you can add the following
hook to SystemJS:

var systemNormalize = System.normalize;
System.normalize = function(name, parentName) {
  if (name.match(/\.jsx$/))
    name = name + '!';
  return systemNormalize.call(this, name, parentName);
}

**Comment by OClement** [comment]
+1 for this; it is currently impossible to use (for instance) Material-Ui Library

@guybedford 
Thanks for that snippet - However, it seems to hang something somewhere; When adding this snippet after loading System.js, the page will hang and it is impossible to debug (cannot inspect source). Or am I doing this wrong?

Thanks

**Comment by guybedford** [comment]
@OClement yes you're right the hack mentioned forms a circular loop with the plugin system as it tries to normalize the name and then thinks it is a chained plugin. As mentioned I think the better solution for your situation will be the issue https://github.com/jspm/npm/issues/10. This is not being highly prioritised at the moment, my apologies I can't get it to you sooner. A better hack here is certainly possible if you feel like doing some loader forking.

**Comment by OClement** [comment]
@guybedford  Thanks for the reply; I have to say I appreciate the efforts put into this project as it does solve a big issue for us Devs when trying to deal with all that mess that is the JS opensource stacks :p

That said, I think this kind of issue should be considered relatively important; as I mentioned earlier, this limitation of SystemJs does prevent the use of some third-party libraries, making the whole JSPM thing moot/unpractical at the moment. I would love to be able to tell my colleagues "let's jump on the JSPM boat" right now but I just can't recommend it as a production-ready (even Dev) tool at the moment because of this :/

Mind you, I understand the whole SystemJs/JSPM is not a small thing to tackle and represent a lot of work and research into finding the best solution to a relatively big problem, and I am sure there are others issues just as important. 

In the end, you guys are the one who knows best about what's of most importance. I just wanted to highlight those points in hopes of having this issue rise a bit in priority :)

Again, thanks for your work; Our life would be totally different in a bad way if it weren't of projects like these!

**Comment by matthewp** [comment]
^^ You shouldn't think about SystemJS as a loader that solves every problem. It's meant to solve the most common problems and should do so carefully. Adding a simple extension like shown above is not a hack... it's how things should work. Think of SystemJS as a starting point for creating your own loader that includes your local business needs. 

@guybedford This makes me think there should be a tool that builds a custom loader through some type of cli interface. Simply check the extensions you need (including your own local ones) and it spits out a loader file for you. I might create a project for that.

**Comment by OClement** [comment]
> Adding a simple extension like shown above is not a hack... it's how things should work.

Not sure I see what you mean by this?
My thoughts is that when using a tool such as JSPM, one shouldn't have to rely on relatively obscure patterns to dictate intention or alter behaviour, such as adding a `!` to a string to say: "use a plugin by the name of whatever is in between a `.` and the `!`. It just doesn't make that much sense to me.

---

I'm just dumping my mind without considering every corner cases here:
Ideally, from a user's perspective, by doing `import Module from 'module';` (without extension), the loading should be smart enough to able to load the file with that name, regardless of its extension, and apply whatever transform is needed based on some config (as proposed by Guy in the first post here). 

The same should apply if the extension is supplied in the `import/require` statement.
If it were to work that way, one could load any combination of syntaxes used in different modules.

To reiterate, the specific problem I experienced is where I would `import MUI from 'mui'`;
- `mui` is aliased to `npm:material-ui@0.6.1`
- Which in turns `require("npm:material-ui@0.6.1/src/index");` <- index is in reality `index.js`
Everything is fine until now

- That index.js file does it's own bunch of  `require(./js/app-bar.jsx")` <- whoops, extension present, no `!`
The loader fails

So you say ok, let's manually import those modules ourselves:
`import TopBar from '../jspm_packages/npm/material-ui@0.6.1/src/js/Topbar.jsx!';`

Well, in `Topbar.jsx`, it  does `var Classable = require('./mixins/classable.js');` <- .js extension, the loader will try to dumbly load `classable.js.js`

---

Now I don't want to sound like I'm *asking* anything, just putting some thoughts out
I have to say I am not super familiar with that whole 'loaders' idea so maybe I am missing a point too

**Comment by matthewp** [comment]
Yeah, so there's going to be a change so that `.js` isn't added by default any more. This is also the reason the `!` was necessary, because otherwise the loader doesn't know if something is a plugin. The presence of a period is not enough. A period is a valid character in file names, it doesn't indicate an extension. `foo.bar.js` is a valid file name, so if I do `require('./foo.bar')` and it thought it was a `bar` plugin then it would break.  So this new plugin proposal fixes that by mapping specific extensions to plugins.

All I meant by comment is that if you run into a bug or some feature that is not yet implemented in SystemJS, don't be afraid to add a hook like the one described a bit above. It is not a hack, it's how all of SystemJS works in fact. And you'd be learning a (soon to be) standard API.

**Comment by OClement** [comment]
Ah yes ok, I see what you mean now and makes sense to me yes

Also, thank you for the clarification, it's greatly appreciated

**Comment by glen-84** [comment]
@guybedford,

Is "plugin" the name of a module? f.e., could you do this:

```
System.config({
  modules: {
    '*.css': { plugin: 'github:systemjs/plugin-css@0.1.9' }
  }
});
```

... so that you don't have to have a mapping from that module name to "css" (as is currently required [and prevents you from having your own "css" folder]).

**Comment by glen-84** [comment]
@guybedford,

If you had (within a *package*, not your *app*):

```
import 'style.css';
```

I assume the package would have a dependency on a CSS plug-in/loader itself, in case the outer application did not define a "handler"? Also, the package may use a different version of the CSS plug-in, or a completely different plug-in altogether. Will it be possible to use the plug-in specific to the package? It could be overridden with shim config.

I kinda hate the exclamation syntax. What is the reason for keeping it, other than for BC?

**Comment by guybedford** [comment]
Plugins should always be versioned to their packages. There are still use cases for dynamic plugin calls, so I want to keep the syntax (say for example loading dynamic external resources from a third-party CDN, where you don't have direct control via package configuration), but I certainly want to make it a much rarer case.

**Comment by timbur** [comment]
Any idea if/when this will be in SystemJS?

**Comment by guybedford** [comment]
Merged into master.

**Comment by timbur** [comment]
Alright so I've been trying for the past hour to make this work.  Is the SystemJS that JSPM automatically installs an older SystemJS?  I ran into some issues "upgrading" and I'm about to fall asleep now lol so... How do I make this work?  I really want to be able to `import 'style.css';` instead of `import 'style.css!';`.

**Comment by OrKoN** [comment]
@timbur I believe this has not been released yet. You need to install from the master branch, not just via npm.

**Comment by timbur** [comment]
@OrKoN thanks!  @guybedford Is there anything I can do to help out?  If you could maybe assign me to some tasks for either SystemJS or JSPM, I'd be glad to see what I can do.

**Comment by timbur** [comment]
I just removed all references to JSPM and SystemJS and reinstalled everything via `npm install jspm --edge`, and the SystemJS version appears to be 0.16.11 which matches the current master version, but I still can't get this to work.  I've tried the following:

```js
System.config({
  "modules": {
    "*.css": { "plugin": "css" },
    "*.json": { "plugin": "json" },
    "*.jsx": { "plugin": "jsx" }
  }
});
```

```js
System.config({
  "modules": {
    "*.css": { "loader": "css" },
    "*.json": { "loader": "json" },
    "*.jsx": { "loader": "jsx" }
  }
});
```

```js
System.config({
  "meta": {
    "*.css": { "plugin": "css" },
    "*.json": { "plugin": "json" },
    "*.jsx": { "plugin": "jsx" }
  }
});
```

```js
System.config({
  "meta": {
    "*.css": { "loader": "css" },
    "*.json": { "loader": "json" },
    "*.jsx": { "loader": "jsx" }
  }
});
```

**Comment by timbur** [comment]
Figured out the hard way that `--edge` wasn't actually pulling from the master branch.  It was using the official 0.16.11 release.  So I manually extracted the relevant `dist` files from master and tried it, and it still doesn't work due to some "unexpected end of input" error when it tries to load the plugin(s).

However, I did put together this monkey-patch for the official 0.16.11 release's `System.locate`, which seems to work:
```js
var systemLocate = System.locate;
var pluginExtensions = ['css', 'json', 'jsx'];

System.locate = function(load) {
  var System = this;
  var name = load.name;
  var match = name.match(new RegExp('\\.('+pluginExtensions.join('|')+')$'));
  var plugin = match && match[1];

  if (!plugin) {
    return systemLocate.call(System, load);
  }

  return System.import(plugin).then(function(pluginModule) {
    load.metadata.plugin = pluginModule;
    load.metadata.pluginArgument = name;
    
    return systemLocate.call(System, load).then(function(address) {
      load.address = address.slice(0, -3);  // remove .js

      return pluginModule.locate
        ? pluginModule.locate.call(System, load)
        : load.address;
    });
  });
}
```
