### ISSUE TITLE
Import a specific object prop

### ISSUE THREAD

**Issue by reggi** [systemjs/systemjs#302]
When importing a javascript file that doesn't use any module definition and globals only. I'm getting an object with every function in it. 

es6.js

```
export function andrew(){
  return "my name is andrew";
}

export function thomas(){
  return "my name is thomas";
}

```

when I use export syntax I can do this

`import { andrew } from "./commonjs"`

---

`raw.js`

```
function andrew(){
  return "my name is andrew";
}

function thomas(){
  return "my name is thomas";
}
```

This exports as an object. and I can't do this:

`import { andrew } from "./raw"`

I'd have to do:

```
import everything from "./raw"
var andrew = everything.anderew
```

I guess what I'm asking is, is there a way to import a specific object prop within the import line, like commonJs I'd be able to do `var andrew = require("./raw").andrew`.

**Comment by guybedford** [comment]
This is a little bit of a controversial topic.

It also features when wondering if I should allow `import { readFile } from 'fs'` where `fs.js` is a CommonJS module.

6to5 have worked out a way to support this that we could endorse, but for now I'm trying to avoid it because I don't want to push ES6 interop too far too hastily. It may well be something we can do though.

**Comment by reggi** [comment]
@guybedford Had no clue it was controversial. I've been playing around with ES6 / System.js / JSPM for a couple of hours and thought I was just doing n00bish things. Thanks for your comment and feel free to close. :rainbow: :open_hands: :100: :package: :shipit:

**Comment by guybedford** [comment]
@reggi sure thanks! Ok I will close this for now, but if there is pressure in future we can reconsider.
