### ISSUE TITLE
require is not defined in ES6 modules

### ISSUE THREAD

**Issue by cdetrio** [systemjs/systemjs#308]
This works in app/app.js:

````
var $ = require('jquery');
module.exports = {};
````

But this throws require is not defined:
````
var $ = require('jquery');
export default {}
````

Curiously, this also throws require is not defined:
````
var $ = require('jquery');
/*
export default {}
*/
module.exports = {};
````
Though it works fine if the comment is on one line (`/* export default {} */`)

**Comment by guybedford** [comment]
Yes this is behaviour by design.

* A module is only interpreted as a single module format - either as ES6, CommonJS, AMD or global. `require` is undefined in all environments except CommonJS, just like `define` is undefined in all environments except AMD.
* Mixing module syntax is a bad idea - this is creating a two-phase linking process for no good reason.
* Automatic module format detection starts with ES6 first (without comment removal), then CommonJS (with full comment removal), then AMD, then global. This makes ES6 the fastest most default path.

**Comment by amcdnl** [comment]
Interesting; I'm converting require to system but I use 6to5 instead of tracuer like:

  gulp.task('es6', function () {
    return gulp.src(path.source)
      .pipe(plumber())
      .pipe(changed(path.output, {extension: '.js'}))
      .pipe(to5(assign({}, compilerOptions, {modules:'system'})))
      .pipe(gulp.dest(path.output))
  });

Note the module configuration defined to system.  Now my code wraps the AMD in system :S

**Comment by guybedford** [comment]
@amcdnl are you saying your code is AMD with ES6 features, that you want to convert with 6to5? If so, use normal transpilation, not System. Only use the `system` output if you're writing with ES6 modules.

**Comment by amcdnl** [comment]
Yup, thats correct.  Ya I had a feeling that I would have to do some sort of exclude for that.  I was getting this: http://www.screencast.com/t/RusUrxbN ... i was assuming it would have converted them to system when i first looked at it.
