### ISSUE TITLE
windows file baseURL fix

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#309]
Currently for local windows file paths, a baseURL set to `c:\...` is not being normalized to `file:\...` because it is detected as an already-normalized protocol URI.

We need to add an exception to https://github.com/systemjs/systemjs/blob/master/lib/extension-core.js#L89 that converts a windows path into a file URI here, most likely doing this when detecting them from the presence of `/^[a-z]:\\/`. Ultimately we should cater for all the rules in http://blogs.msdn.com/b/ie/archive/2006/12/06/file-uris-in-windows.aspx.

**Comment by guybedford** [comment]
This seems too much like a special case - I actually don't think there's anything consistent we can do here. Rather I've amended the docs in https://github.com/systemjs/systemjs#nodejs-usage.

**Comment by tschoening** [comment]
Please reconsider your solution, because this is not a Windows bug. Windows doesn't use slashes in paths by default, so the problem here can only be introduced because the C:\ is changed to C:/ by someone else, resulting in the misinterpretion as a scheme. Indirectly the problem seems to not be limited to Windows at all:

I'm currently testing to switch from JavaScriptMVC to using CanJS and StealJS directly by following your tutorials and the problem was raised when implementing stealconfig.js. It didn't work without baseURL because of the "file:"-error and currently baseURL needs to be a hard coded Windows path with the "file:"-prefix. But we have devs using Windows and Linux as well, such a hard coded path would make maintenance unnecessarily hard.

Recognizing C:/ as not a valid scheme with your proposed regexp above seems easy and save to me, you can or can not deal with all the other aspects of valid URI encoding later. Most implementations don't care about all aspects of valid URIs anyways and provide workarounds. In fact, seeing "file:C:/..." work already indicates that this is the case later in node or whatever, because this is not a valid file URI at all. Instead, using "file:///C:/" or "file://C:/" breaks the build as well, even if the former of those two would be the proper syntax:

> ; FILE
> fileurl        = "file://" [ host | "localhost" ] "/" fpath

http://tools.ietf.org/html/rfc1738#section-3.10

So please, with a little change you could at least make the build work under Windows by default. Thanks!

**Comment by tschoening** [comment]
Using steal-tools directly on the shell doesn't work as well:

steal-tools build --baseURL "file:%cd%" --config "stealconfig.js" --main main

This errors out with the "file:"-error and the following errors out because it can't find "file". I guess in that case the parse logic for the shell introduces an error, because ":" is sometimes used as path delimiter.

steal-tools build --config "file:stealconfig.js" --main main

**Comment by guybedford** [comment]
Sorry I can't be more abiding, but a `file:` protocol is not going to change as all normalization has to be protocol relative and `c:\path` in Windows v `/path` in linux means that one is treated as a protocol for normalization and the other not - effectively giving us different behaviour. I would suggest following up better treatment of the `file:` protocol handling with Steal.
