### ISSUE TITLE
usage example for TypeScript plugin?

### ISSUE THREAD

**Issue by trentgrover-wf** [systemjs/systemjs#338]
Can anyone provide a simple usage example? When using this similarly to other SystemJS plugins, I only get an error.

https://github.com/frankwallis/plugin-typescript/issues/1

![screen shot 2015-01-30 at 4 17 50 pm](https://cloud.githubusercontent.com/assets/3778206/5984406/9bb81fbc-a89b-11e4-8c22-e57acfc48a9d.png)

**Comment by guybedford** [comment]
I just tested this out with `jspm install ts=npm:typescript-plugin` and it doesn't seem to be working quite properly.

It would be great to see a TypeScript plugin as this is a really great use case for plugins and TypeScript works incredibly well with this style single-file compilation.

**Comment by frankwallis** [comment]
The TypeScript plugin is still under development - I have made some more progress and will publish a new version soon.

There are some complications because in order to transpile a .ts file you also need to fetch any files which it is dependent on and any declaration files which it uses. There are also some resolution/mapping issues around the fact that TypeScript uses ```require("./myfile")``` to access 'myfile.ts'. I am also still finding my way with systemjs and jspm (which is very impressive btw.)

 I have a test project which I am converting to systemjs, I am aiming to get that completed this week and will publish more info then.

**Comment by guybedford** [comment]
@frankwallis thanks for the update. you don't need to handle fetching if you can translate the source into CommonJS or AMD. I'm not entirely sure how TypeScript requires work - are they similar to CommonJS? If so just set `metadata.format` to `cjs` in the translate hook and return CommonJS code. Perhaps with plugin calls to the end of the requires - `require('./myfile')` -> `require('./myfile!ts')`. You can get the full normalized name of the TypeScript plugin itself in the plugin by accessing `module.id` if the plugin module is CommonJS or AMD. Just let me know if I can help further with this at all.

**Comment by frankwallis** [comment]
Thanks for the info - the problem is that in order to output the code in commonjs format TypeScript requires more than just the source file, it also needs the 'declaration' files (a bit like header files in c) and any import files so that it can type-check the code and produce the js output. Using System.fetch to get these outside of the normal flow seems to be working fine though.

As you already saw I have produced a new version which works and there is an example project with the plugin. I also have a test application which I am working on [here](https://github.com/frankwallis/tower/tree/systemjs)

There are still a few issues which I am working through and I need to add some more tests and documentation. I'll get back to you about the pull request on the other thread. Thanks.

**Comment by guybedford** [comment]
Great to hear, will follow up issues on that repo. Also just let me know if I can help with anything.
