### ISSUE TITLE
Unable to import packages with jsx files in them

### ISSUE THREAD

**Issue by ccapndave** [systemjs/systemjs#346]
First of all apologies if I am merely doing this wrong and its not a real bug :)

I am trying to use https://github.com/callemall/material-ui with `jspm`.  The problem is that most of the files in the package are suffixed with `jsx` and to comply with ES6 guidelines `systemjs/jspm` sticks a `.js` extension on the end.

This means that it ends up trying to load `app-bar.jsx.js` instead of `app-bar.jsx`.  Strangely if I add a rule to `System.config` mapping `*.jsx` to `*.jsx`, it then ends up trying to load `app-bar.js.js` instead of `app-bar.jsx`.

In fact the only way I can get a jsx file to load is with something like `import App from 'components/App.js!jsx'`, which obviously isn't practical for a third party package.

**Comment by lalitkapoor** [comment]
maybe this helps? https://github.com/lalitkapoor/systemjs-es6-react-boilerplate

**Comment by guybedford** [comment]
In jspm this issue is actually solved in general by supporting Browserify transforms (https://github.com/callemall/material-ui/blob/master/package.json#L31). This is being tracked in https://github.com/jspm/npm/issues/10.

As for loading jsx files through plugins with relative loading paths, this is not currently supported in SystemJS but there are plans to support things like this in future.
