### ISSUE TITLE
modules over websocket?

### ISSUE THREAD

**Issue by mc007** [systemjs/systemjs#365]
Hi,
i am currently looking for a solution to load modules(mostly AMD) via websocket rather than script tags. Might it be possible to implement this with your lib? 
thank you.

**Comment by guybedford** [comment]
@mc007 yes this is certainly possible - any form of source code transport can be supported.

The way to do this is by overriding the `fetch` hook implementation:

```javascript
System.fetch = function(load) {
  return new Promise(function(resolve, reject) {
    doWebsocketsFetch(load.address, resolve, reject);
  });
}
```

Note that the bundles, register and plugins system also use the fetch hook, so that if you just override like that after loading SystemJS this will disable some functionality.

Rather include the scripts in this order (most likely in a custom concat):

```html
<script src="es6-module-loader.js"></script>
<script>
  System.fetch = ...customFetch as above...
</script>
<script src="system.js"></script>
```

That way you won't lose any functionality.

**Comment by mc007** [comment]
that's just awesome! I tried to hack dojo and requirejs for that but that is way more better.

Do you know by chance whether a native ES6 (if out) implementation actually would support a different transport? I did read quite some stuff but never got an answer from it.

thank you!

**Comment by guybedford** [comment]
Native ES6 doesn't have a loader and can't load other module formats only ES6. The loader is being defined as a WhatWG spec at https://github.com/whatwg/loader and provides exactly these hooks.

**Comment by mc007** [comment]
allright, thank you for this!
