### ISSUE TITLE
Wrong "require()" context

### ISSUE THREAD

**Issue by arcanis** [systemjs/systemjs#394]
Hi,

I experience an issue where the `require()` function isn't able to load the modules from the right directory. It's something like this:

  - A/
      - node_modules/
          - systemjs/
              - ...
          - module/
              - index.js (`module.exports = 1`)
      - foo.js
  - B/
      - node_modules/
          - module/
              - index.js (`module.exports = 2`)
      - bar.js

foo.js is somewhat like this :

```
System.import( '../B/bar' )
```

And bar.js is like this :

```
console.log( require( 'module' ) );
```

The result is `1` instead of the expected `2`. Why is that ? Is it possible to fix it ? Maybe by reimplementing the require function ? I don't understand how to require npm modules without using jspm, which seems a bad choice for a full-node application, which won't ever be run in a browser :(

**Comment by arcanis** [comment]
My workaround for now:

```
for ( var top = module; top.parent; top = top.parent ) ;
var topRequire = top.require;

require( 'module' ).prototype.require = function ( what ) {
    return topRequire( what );
};
```

But it's terribly ugly and breaks a lot of other things ...

**Comment by guybedford** [comment]
@arcanis modules are loaded relative to a baseURL and don't follow backtracking through node_modules folders.

Because `foo.js` is using `System.import('../B/bar')` this implies your baseURL is actually `A/`. So when you do `System.import('module')` you get `A/module` which is then also the result of running `require('module')`.

Perhaps look at this project - https://github.com/stealjs/system-npm.

**Comment by arcanis** [comment]
Thanks @guybedford. For what it worth, I end up using the full path in my require. Not the best thing ever, but it avoids relying on yet another third-party dependency, and is good enough for my use case.

Thanks !
