### ISSUE TITLE
SystemCSP cannot handle text plugin

### ISSUE THREAD

**Issue by szepeviktor** [systemjs/systemjs#429]
When switching from `system.src.js` to `system-csp.src.js` text plugin stops working.
```
TypeError: exports is undefined
```
Is it by design?

**Comment by szepeviktor** [comment]
On the other hand SystemCSP cannot handle global scripts.
Is it by design?

**Comment by szepeviktor** [comment]
After I've read https://github.com/systemjs/systemjs/issues/407#issuecomment-94046367 my question is: Can non-script resources be loaded with `type="text/cache"` and then get their `.text`?

**Comment by MajorBreakfast** [comment]
@szepeviktor [In this issue](https://github.com/systemjs/systemjs/issues/420) @guybedford explains that script tag injection and automatic global detection don't play along. Plugins [are included](https://github.com/systemjs/systemjs/blob/0950bd9bd7bb87e39b7bd919111bcc585310b209/Makefile#L7) in the CSP version however the text plugin probably doesn't work because it uses the [translate hook](https://github.com/systemjs/plugin-text/blob/3f05122b725d091a193b679946efbac23effebf4/text.js#L4) which then necessitates runtime evaluation. However, technically this should be feasible to implement without this need. Something similar to the way how the  [alias format in the upcoming 0.17 release](https://github.com/systemjs/systemjs/blob/5cea1bc5811114025413a1cdcac392f743fa6d50/lib/alias.js#L16-L27) is implemented could probably be done. For now I think it's easier to stick with normal SystemJS for development and then bundle using JSPM and use the CSP version.

**Comment by szepeviktor** [comment]
Thank you for answer.
I appriciate that you are developing an universal resource loader.
Do I understand it correctly that the current CSP version *cannot* use the text plugin? I gladly wait for the next release as it is imminent. So my current project will use [curl](https://github.com/cujojs/curl).

**Comment by MajorBreakfast** [comment]
I'm just a user myself. But sure you can: Just bundle or build it using jspm. I just tested it in my app and I'm using the text plugin.

**Comment by szepeviktor** [comment]
Thank you.

`import text from "js2/some.txt!text";` is build into a `System.register()` that literally contains the contents of  `js2/some.txt`.

What is the way to compile text plugin so that it loads resources in runtime (not at compile time).
Thakn you once again.

**Comment by MajorBreakfast** [comment]
Don't build or bundle it using jspm and it will load it directly.

**Comment by guybedford** [comment]
@szepeviktor you can exclude items from the build with `jspm build app - js/some.txt!text` or you can add a meta configuration - `System.meta['js/some.txt!text'] = { build: false }`.
