### ISSUE TITLE
Tutorial / Working Example / Reference?

### ISSUE THREAD

**Issue by bucaran** [systemjs/systemjs#435]
I don't know if I am still missing something ( you know a nice working example / tutorial to learn would have been useful) but here is my situation.

Using `Babel` I am trying to use `System.import` to load some modules conditionally, kind of like:
```
System.import(argv.logger || "./lib/logger").then(...)
```

But I am getting all kind of _path not found errors_. After I install `systemjs` and including it on my source:

```js
import System from "systemjs"
```

I know `System` is correctly referring to the polyfill, but the path above `"./lib/logger"` can't be resolved unless I manually type in `node_modules/<MY PKG>/lib/logger` which is crazy.

Even after successfully loading it the that way, I still get the following error:

```
[Error: Error loading "babel-runtime/helpers/interop-require-wildcard" at file:
$HOME/<PROJECT>/babel-runtime/helpers/interop-require-wildcard.js

Error loading "babel-runtime/helpers/interop-require-wildcard" from "node_modules/<MY PACKAGE>/lib/logger" at file: 
$HOME/<PROJECT>/node_modules/<MY PACKAGE>/lib/logger.js

ENOENT, open '$HOME/<PROJECT>/babel-runtime/helpers/interop-require-wildcard.js']

  errno: -2,
  code: 'ENOENT',
  path: '/Users/b/.d/<PROJECT>/babel-runtime/helpers/interop-require-wildcard.js' }
```

**Comment by MajorBreakfast** [comment]
Don't import system, it cannot load itself ;)

**Comment by MajorBreakfast** [comment]
http://youtu.be/lc9nQJR6RX4 I held this talk last fall

**Comment by bucaran** [comment]
Thanks. 

If I don't import / require System it throws up at me with System not defined.

**Comment by MajorBreakfast** [comment]
You need to load it via script tag

**Comment by bucaran** [comment]
This is a node project. I am also using Babel.

**Comment by MajorBreakfast** [comment]
You should have mentioned that ;) I can't really help you then because although I'm following the project for more than half a year now, I am not using it in node. I'd say `require()` it and then use `System.import()` to load further stuff is the way to go, though.

**Comment by bucaran** [comment]
@MajorBreakfast 
Yes, I should have! My bad. 

That's why I was using 

```js
import System from "systemjs"
```

which gets transpiled to `require` anyway, so I am definitely getting a valid reference to `System`. The problem is it doesn't resolve paths correctly, no matter what.

Where is the step by step (or just any steps) Node guide of how to use this?

**Comment by MajorBreakfast** [comment]
SystemJS has it's own babel integration. Any ES6 file will get transpiled by SystemJS with circular reference support. There is no need to transpile your code beforehand to CommonJS, e.g. with `babel-node`.

**Comment by bucaran** [comment]
`System.import` is using the current directory, but I want it to use the directory where the script is running instead, ie.. `__dirname`. Is there anyway to achieve this without something crazy like:

```js
path.join(__dirname, "lib/logger").replace(process.cwd(), ".")
```

I am sure there is probably a better way to do this, but while my code works using `require` it does not work with this.

**Comment by MajorBreakfast** [comment]
The global System is supposed to always function the same way. Another API relative to the current module is in the works (spec discussions at https://github.com/whatwg/loader) but that's not fleshed out yet.

Short term solution:
```JS
System.import(__dirname + '/other-module')
```

However, it's quite rare that you dynamically import your modules (Usually only once in your main js file). You should use the static import syntax, which allows you to use relative paths, wherever possible.

**Comment by bucaran** [comment]
I think we are not understanding each other well.

I am building a library, that will live (usually) inside the current directory `node_modules/LIB_NAME`.

I also have a global `/usr/local/bin` symlink pointing to that `node_modules/LIB_NAME/index.js` executable.

But `System.import("stuff")` thinks I want to load `$PWD/stuff`, but that does not make sense!

It should load `${__dirname}/stuff`

**Comment by MajorBreakfast** [comment]
- If you build a library for consumption in other projects, then you likely shouldn't use SystemJS for compatibility reasons.
- If you're writing an application, then you could use it if you want to be on the bleeding edge. You should evaluate whether it is worth it, e.g. you want to use SystemJS's plugins or you absolutely need circular references (which CommonJS doesn't offer)

The reason why your modules aren't found is because SystemJS doesn't look at the `node_modules` folder. Node's own module loader can look for files at multiple places, e.g. for `require('something')` node can look for `./something.js`, `./something/index.js`, `node_modules/something/<main-defined-in-package-json>.js`. SystemJS can't do that because in the browser those networks requests cause a lot of useless round-trips. Instead, all packages are registered in advance in a `config.js` using the map feature.

To load the infos from package.json you can use https://github.com/stealjs/system-npm. Note that this is still not as smart as a node loader which has instant access to the file system can be. AFAIK such a node loader that builds on the es6-module-loader hasn't been built, yet. If I had to guess we'll see the new loader native first in browser and only later in node.

**Comment by bucaran** [comment]
> If you build a library for consumption in other projects, then you likely shouldn't use SystemJS for compatibility reasons.

...no one told me! :smile: 

Thanks for the detailed response :+1:

**Comment by MajorBreakfast** [comment]
@bucaran You'd most definitely run into issues. If you load something via SystemJS it's asynchronous (as it should). But that means that you can't use it internally in a node library because you're library is then forced to export something not initialized synchronously.

**Comment by bucaran** [comment]
I am not loading anything conditionally anymore. Instead I will produce a JSON output and implement the logger / reporter as a separate binary that can read that JSON! :smile:
