### ISSUE TITLE
Rename `plugin` to `loader`

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#436]
I hate to copy Webpack terminology, but it just makes so much more sense.

**Comment by matthewp** [comment]
I find it to be confusing with Loader.

**Comment by MajorBreakfast** [comment]
That is just confusing.

A good alternate name would be "modifier". But "loader" is bad.

**Comment by guybedford** [comment]
Thanks for the feedback. The goal is to make it clear that plugins are the fundamental mechnism for loading new resources in new ways. Plugins get associated to specific resource requests, which is the key thing the user needs to be thinking about.

Consider:

```javascript
System.config({
  meta: {
    'some/module': { plugin: 'sweetjs', sweetjsOptions: { someCompiler: 'option' } }
  }
});
```

v

```javascript
System.config({
  meta: {
    'some/module': { loader: 'sweetjs', sweetjsOptions: { someCompiler: 'option' } }
  }
});
```

Consider seeing this for the first time without prior knowledge. `loader` makes it immediately clear that this is passing full loading responsibility on. `plugin` just doesn't sound like it is as important.

**Comment by MajorBreakfast** [comment]
Maybe `Loader` should be called `ModuleLoader`. Then we have the name available again :)

**Comment by matthewp** [comment]
It's not passing full loading responsibility though, it's only passing responsibility for methods the plugin implements. And I'd wager that half of plugins are built around `translate`.

Are WebPack "loaders" explicitly tied to modules, like SystemJS plugins, or are they more like extensions?

**Comment by matthewp** [comment]
Plugins aren't particularly great because you can't pipe them into each other. If you want to inherit behavior you have to explicitly inherit the parent plugin.  Which is not bad just less expressive.  Extensions are more interesting in that you can do whatever you want (within the bounds of the spec).

Not having the ability to call `super` within a plugin also makes them a little limiting.

I only say this because if WebPack loaders are more powerful than SystemJS plugins (I don't know enough about WebPack to answer that) then I wouldn't want to promote plugins too hard.

**Comment by MajorBreakfast** [comment]
@matthewp Good point.

What is the conceptual, not technical, difference between plugins and extensions?

Text, CSS, LESS & JSON loading could just as well be implemented as extensions that activate automatically by file extension or explicitly via `{ format: 'css' }` etc.

`{ plugin: 'css' }` <-> `{ format: 'css' }`

**Comment by guybedford** [comment]
Merged into master.

**Comment by timbur** [comment]
Any docs for this yet?  I would assume https://github.com/systemjs/systemjs/wiki/Meta-Configuration is the place to look, but I don't see anything about a `loader`.  And what's the status/consensus on associating say, the `css` loader with every `*.css` file?  For instance, it would be nice to be able to `import './css/style.css'`.  I know an added exclamation mark really isn't a huge deal at all but it seems like one of those things that might make things more elegant in the long-run while also being a bit more intuitive for newcomers (if maybe certain loaders are included by default with some setups, of course).

**Comment by guybedford** [comment]
@timbur see https://github.com/systemjs/systemjs/blob/master/docs/overview.md#plugin-loaders.

**Comment by timbur** [comment]
WOW.  I feel like I'm blind sometimes.  I had actually tried this before but it wasn't working because `defaultJSExtensions` is `true`.  I suppose I can try going through and fixing every dependency so that I compatibility mode isn't required.  And I don't suppose somehow configuring `paths` (or using a `js` loader in a similar fashion?) would allow that either since it's part of the same algorithm?

**Comment by guybedford** [comment]
Setting defaultExtension at the package level will allow packages to selectively use the feature. I've been meaning to document that.

**Comment by timbur** [comment]
Does `"defaultExtension": "js"` work directly within `System.config({...})` or does it have to be under `System.packages` (or `System.config({packages: ...})`)?

**Comment by timbur** [comment]
From [the source](https://github.com/systemjs/systemjs/blob/bcce2969e890c0a91b3733d47487af01aba93eef/lib/package.js#L127-L138) it appears it's only under `packages`?

**Comment by timbur** [comment]
Surely there's a way to make this backwards compatible for *all* modules such that it appends the `defaultExtension` to every package if there's no extension (which I already see you've basically written).  I had been using a [monkey-patch for `System.locate`](https://gist.github.com/timbur/a446ee36818cc0cc293a) to do this.
