### ISSUE TITLE
System.js fails to load es6-module-loader automatically in some situations

### ISSUE THREAD

**Issue by wesleycho** [systemjs/systemjs#478]
I have noticed that System.js fails to load es6-module-loader.js, even when the file is in the same directory, in certain situations. Namely, I have noticed it in the testing situation when using karma, and on Android via Cordova (or in my case, [cca](https://github.com/MobileChromeApps/mobile-chrome-apps)).

The current workaround is to load es6-module-loader.js beforehand manually.

**Comment by guybedford** [comment]
Yes it doesn't work in all scenarios as it relies on the document write order. In these cases the manual inclusion is advised as you are doing.

**Comment by msegado** [comment]
I assume the same is true of system-polyfills? Just had a user on the Android 4.4 browser (which doesn't have native Promises) experience a non-loading app and am wondering if this was the issue. Will include it manually and see if that fixes it!

**Comment by guybedford** [comment]
Yes exactly. This sounds like a bug though. If you're able to check, can you see if the polyfill branch at https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L3869 is running by inserting a simple `console.log`? That would really help to know if the polyfill detection is broken here, and if we can add a fix.

**Comment by msegado** [comment]
It looks like polyfill detection was working just fine - the user sent some more details and it seems at least one module of the app was loading, which wouldn't be possible without it. Plus, the bug persisted after I added it manually, so it's definitely not caused by this issue (...which leaves scratching my head about what the actual problem is with my app on that browser, but that's likely unrelated to SystemJS...)

On the plus side, no fix needed! =)
