### ISSUE TITLE
glob mapping to apply plugins

### ISSUE THREAD

**Issue by MajorBreakfast** [systemjs/systemjs#481]
A quick idea I had for configuring plugins:

```JS
System.config({
  map: {
    '*.css': '*.css!css'
  }
})
```

This enables plugin chaining:

```JS
System.config({
  map: {
    '*.less': '*.less!less!css'
  }
})
```

What's your take on this?

**Comment by guybedford** [comment]
Unfortunately mapping into plugins is something that is no longer supported in the latest release as it results in circular normalization.

Plugin chaining is very much a circular normalization feature, and I'm hesitant to consider it not for that reason but mainly because I find it very ugly and unnecessary.

Also syntax trees can't be shared either.

So the focus is actually on plugins that extend from each other, which is a more powerful model anyway.

**Comment by teohhanhui** [comment]
> Unfortunately mapping into plugins is something that is no longer supported in the latest release as it results in circular normalization.

But it still works when doing something like this:

```js
System.config({
  map: {
    "google-maps": "https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places!systemjs-googlemaps/googlemaps",
    "systemjs-googlemaps": "github:HeinrichFilter/systemjs-plugin-googlemaps@master"
  }
});
```

Is that intended?

If using only `!systemjs-googlemaps` then it looks under the `baseURL` which is of course wrong.

**Comment by guybedford** [comment]
@teohhanhui it's not encourage to hard-code the plugin path. The plugin could return a custom `locate` or `fetch` that ignores the input address entirely to do its own resolution if you wanted `!google-maps` style import support.

**Comment by teohhanhui** [comment]
@guybedford I'm just curious why that should work despite your comment that it is not supported.

If you look at HeinrichFilter/systemjs-plugin-googlemaps#1 I've switched to use `meta.<pkg>.loader` instead :)

**Comment by guybedford** [comment]
Nice! That looks like the best way to do it certainly.
