### ISSUE TITLE
A bug of module comment

### ISSUE THREAD

**Issue by gordonpro** [systemjs/systemjs#492]
A module `main/test.js` with the specify comments :
```js
var $ = require("jquery");
    /*
 if ( typeof define == 'function' && define.amd )
        define( 'picker', ['jquery'], factory )
        */
```

or
```js
var $ = require("jquery");
 //if ( typeof define == 'function' && define.amd )
 //       define( 'picker', ['jquery'], factory )
```

then a html inline code import module:
```js
System.import("main/testsystemjs");
```

It will cause an exception you can inspect in  Chrome console:
```
test.js:1  Uncaught ReferenceError: require is not defined
```

if I remove that comment.
It works fine.

**Comment by guybedford** [comment]
@gordonpro yes this is by design actually - automatic format detection is by no means guaranteed to be exact, as performance is also a concern. That is, we don't do comment removal when running module format regular expressions. The detection happens in the order: System.register, ES6, AMD, CommonJS. It could be worth giving higher priority to CommonJS though as it is certainly the more popular format over AMD.

The format can be set via metadata in the loader. That is either:

```javascript
System.config({
  meta: {
    'my/module': { format: 'cjs' }
  }
});
```

Or wildcard meta in the new SystemJS:

```javascript
System.config({
  meta: {
    'js/*': { format: 'cjs' }
  }
});
```

Or syntax in the file itself, although this is not usually recommended:

```javascript
"format cjs";
var $ = require("jquery");
// ...
```

**Comment by guybedford** [comment]
Just let me know if you need any further clarification here.
