### ISSUE TITLE
Pathing rules for TypeScript

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#506]
/cc @frankwallis @vladima

Currently the paths rules in the latest SystemJS require that with `defaultJSExtensions` enabled, paths are written:

```javascript
paths: {
  'file.js': 'file.ts'
}
```

For example to add ts extensions. This also stops things like:

```javascript
paths: {
  'typescript/*': 'typescript/*.ts'
}
```

For extension adding.

With https://github.com/systemjs/systemjs/commit/b00b8a5d36b8fe8f661af20c219393144a607ea5, which has since been reverted, we can enable these use cases.

My question is, is this useful to you both, and worth posting out a "correction" SystemJS 0.18 release for?

**Comment by frankwallis** [comment]
I think this is necessary because in TypeScript doing ```import {a} from "file"``` is an ambient import and is treated differently by the compiler than ```import {a} from "./file"```. Most code within a package will be using ```import {a} from "./file"``` but I don't believe this currently works.

Also /cc @robwormald

**Comment by guybedford** [comment]
See https://github.com/systemjs/systemjs/pull/510 for an implementation.

**Comment by vladima** [comment]
:+1: to this change, this definitely will be useful

**Comment by maryo** [comment]
Does it solve also imports using relative paths like metioned above `import {a} from "./file"`? Let's 
say I have something like 
```js
  "paths": {
    "app/*": "app/*.ts"
  }
```

I've downloaded the new dist.
Now i can do something like `import a from 'app/a';` and it translates to "app/a.ts", that's great.
But if i want to `import b from './b';` inside `app/a.ts` then it translates to "app/b.js".

Is there a way how to achieve it?

**Comment by guybedford** [comment]
Ahh. @maryo thanks so much, ok I completely forgot the reason I needed `defaultJSExtensions` instead of just `paths['*'] = '*.js'` was exactly this issue, you lose the pathing information in relative loads.

This is why we have packages as the unit of `defaultExtension`, which is really the way to do this.

So that ruins this idea unfortunately.

I think finding a way to support `defaultExtension` alongside `defaultJSExtensions` will be the way forward then.

The way to do this will be to basically have `defaultExtension` take preference over `defaultJSExtensions` when in a package. 

Will work on this tomorrow again then.

**Comment by guybedford** [comment]
In short, the new suggestion would effectively be:

```javascript
System.config({
  defaultJSExtensions: true,
  packages: {
    'js/typescript': {
      defaultExtension: 'ts'
    }
  }
});
```

**Comment by robwormald** [comment]
Yeah, this would be ideal!

**Comment by frankwallis** [comment]
Originally in https://github.com/systemjs/systemjs/issues/319 there was going to be a rule that when inside a '.ts' file importing another file without an extension would normalize to '.ts' and in a '.js. file it would normalize to '.js'. Has this approach been completely dropped?

Is it possible to specify packages configuration inside a package (ie in the jspm section of package.json) as I think that is where this information belongs. Otherwise whenever you consume a typescript package you would need to add this configuration in the consumer.

I do see some crossover between the new packages configuration and the overrides/shim configuration - both are configuring **entry-points** into packages.

**Comment by guybedford** [comment]
@frankwallis yes the idea of the rule of deriving the extension from the parent extension has been dropped, mainly because it just creates more edge cases to determine when coming up against other extension mechanisms, and isn't enough on its own to be a comprehensive system. The goal is to just have one mechanism here - `defaultExtension`, with `defaultJSExtensions` being the only other interaction to work out with it now.

The goal is exactly for the SystemJS package configuration to be identical to the package.json configuration, which is why getting this config right is so important, as we only get one shot here.

Yes, for example the paths become entry points:

```json
{
  "paths": {
    "*": "lib/*.ts",
    "styles/*": "css/*.css"
  },
  "meta": {
    "*.css": {
      "loader": "css"
    }
  },
  "map": {
    "css": "global_packages/css-loader.js"
  }
}
```

Allowing:

```javascript
System.import('package/entryPoint'); // -> package/lib/entryPoint.ts
System.import('package/styles/themeA'); // -> package/css/themeA.css
```

I'm wondering if we should instead call `paths` rather `subpaths` here to better distinguish it from global paths. Also subpaths can actually do extension alterations, while global paths can't which may also be a confusion (since because subpaths are package-relative we don't get information loss in URL space).

**Comment by frankwallis** [comment]
ok, this sounds good to me, thanks for the clarification.

**Comment by guybedford** [comment]
As always, these changes are harder and more intricate than they seem... Lots of edge cases to investigate before I can release anything.

**Comment by guybedford** [comment]
Ok had to revert the suggestion from https://github.com/systemjs/systemjs/issues/506#issuecomment-111451773, but I think I've finally got something workable. With some luck will post a release tomorrow morning.

**Comment by guybedford** [comment]
Released in SystemJS 0.18.

**Comment by frankwallis** [comment]
I am still having issues here, I have created an example which demonstrates the problem (copied from @vladima TypeScriptSamples/jspm) [here](https://github.com/frankwallis/jspm-ts-sample)

The issue is that I need to set the defaultExtension to '.ts' on the root package to load the entry point app.ts - so I configure a package called 'app' with a defaultExtension of '.ts', so far so good. But in app.ts I import "./greeter" and the defaultExtension setting is not applied so it 404s with "greeter.js" not found.

The issue seems to be to do with the way that SystemJS determines the current package (by using the location), for the root package this does not work. Is there something I am doing wrong with the configuration here?

**Comment by milkshakeuk** [comment]
@frankwallis I don't know if my [jspm branch](https://github.com/milkshakeuk/tsdemo/tree/jspm) of my typescript plus project might help.

**Comment by robwormald** [comment]
@frankwallis i just opened a PR on your demo, same pattern i've been using elsewhere. https://github.com/frankwallis/jspm-ts-sample/pull/1

**Comment by frankwallis** [comment]
Thanks for the responses, so by putting the code in a subdirectory you can get SystemJS to resolve all files in that sub directory to a package configured with the same name and then those package settings are applied to all files in that directory. 

It does work but I'm not sure that it is as intended.

**Comment by robwormald** [comment]
see also https://github.com/jspm/jspm-cli/issues/855

**Comment by guybedford** [comment]
I've updated the docs in https://github.com/systemjs/systemjs/commit/2416fc8632c98756491c99fee7ad419bf8a3314d to reflect this.
