### ISSUE TITLE
Add support for tsconfig.json.

### ISSUE THREAD

**Issue by Zoltu** [systemjs/systemjs#570]
https://github.com/Microsoft/TypeScript/wiki/tsconfig.json

`tsconfig.json` is the official project type for TypeScript projects.  In particular, it is where compiler options are stored.  In many situations, there may be several tools that are running the TypeScript compiler and they should all use the same options for a given project.  In order for this to not become a maintenance nightmare, each of the tools should leverage a shared configuration file, which is `tsconfig.json`.

I would like to see SystemJS's TypeScript transpiler support `tsconfig.json` so I don't have to store my compiler options in two places.

**Comment by guybedford** [comment]
Thanks for the suggestion, I didn't know about that. Unfortunately this is too specific for SystemJS. A plugin like the TypeScript plugin could certainly do something along these lines though.

**Comment by Zoltu** [comment]
Ah, I didn't realize typescript support come through a plugin.  Thanks!

**Comment by antonmoiseev** [comment]
:+1: I'd love to see it as well.

@guybedford what plugin do you mean, this one https://github.com/mhegazy/typescript?

Frankly I think SystemJS should probably support it rather than the plugin. Even if the plugin supports it SystemJS will need a configuration option to specify where _tsconfig.json_ can be found to pass it to the plugin, since only SystemJS aware of the structure of the project. My point is that the behavior of the plugin won't be transparent for SystemJS anyway, it will have to be aware about this feature and will have to provide a configuration option.

**Comment by Zoltu** [comment]
@antonmoiseev No, this is the one: https://github.com/frankwallis/plugin-typescript

**Comment by antonmoiseev** [comment]
@Zoltu thanks!
