### ISSUE TITLE
issue with AMD and named dependencies

### ISSUE THREAD

**Issue by yoavniran** [systemjs/systemjs#572]
In a project of mine Im trying to use a package I installed from GitHub.
I've running jspm 0.16.0-beta.3

The package I installed is using AMD so internally uses define() to expose its objects.
I noticed that when trying to require its objects, all I got is "**a{}**" instead of the actual implementation.
I noticed they use named dependencies in the form of:

``` javascript
define("thisObject", ["AnotherObject"], function (anotherObject) { ... }
```
For their code I dont see how this would work since "AnotherObject" is never loaded. However, I did a simple test in my project. In my app.js i did:

``` javascript
var amd1 = require("./common/amd1");
console.log(amd1);

var amd2 = require("./common/amd2");
console.log(amd2);

var amd3 = require("./common/amd3");
console.log(amd3);
```
This is the result in the console:

aaa
bbb
**a {}**

-----

*amd1.js*
``` javascript
define(function(){ //simple
    return "aaa";
});
```
*amd2.js*
``` javascript
define("amd2", function(){ //named module
    return "bbb";
});
```

*amd3.js*
``` javascript
define("amd3", ["amd2"], function(){ //named and declares dependency
   return "ccc";
});
```

If I do System.import("amd2") in the console the promise resolves with the return value ("bbb") so it does seem to have been registered.

This is all running in the browser open, not bundled in any way.

Is this supposed to work?

**Comment by guybedford** [comment]
Yes, named AMD is so common that we had to make these cases work doubling anonymous AMD when there is only one named define in a file. Let me know if anything about the behaviour is causing issues?

**Comment by yoavniran** [comment]
hi @guybedford 
im not sure I understand your answer. As I explained in the issue description. the export of amd3.js is not initialized correctly. This is if its using a named dependency. If leave the dependencies array empty, the export works just fine.

Unless Im doing something wrong, I think this is a bug. no?

thanks

**Comment by guybedford** [comment]
Yes this is supposed to work. Thanks this is a regression in SystemJS 0.18. Not sure how this missed the tests.

**Comment by guybedford** [comment]
Ok the issue here is that the named AMD being treated as an anonymous module only happens when it has no dependencies.

When modules have dependencies, it's treated directly as a bundled define, and that's the reason for this (say a bundle with a single module in it).

We could potentially look at extending this "anonymous AMD compatibility" to named modules with dependencies, but it isn't strictly the right thing to do, so would rather avoid it if possible.

**Comment by butchpeters** [comment]
When upgrading from 0.16 to 0.18, I was no longer able to load bundled AMD defines (i.e. the output of r.js optimizer), and I suspect that this issue is related.  The bundled define looks something like:

entry.js:
```javascript
define('libA', [], function () { /* ... */ });

define('entry', ['libA'], function (libA) { /* ... */ });
```

In 0.16, require('entry') would load entry.js and execute the define named 'entry'.  Now in 0.18, the file still loads, but none of the modules in entry are executed.  Is there something else I need to do to get the 'entry' module to run?

**Comment by guybedford** [comment]
@butchpeters are you using the `defaultJSExtensions` option here?

**Comment by guybedford** [comment]
Also be sure to read the upgrade guide at https://github.com/systemjs/systemjs/releases/tag/0.17.0.

**Comment by butchpeters** [comment]
yes, i have the defaultJSExtensions set to true in the config.

**Comment by yoavniran** [comment]
hi @butchpeters , from the tests I did, if you have a dependency like in your case or like in the example i gave (amd3.js) the code that expects that dependency is not executed.

**Comment by butchpeters** [comment]
Looks like this was actually working in 0.18.4, but not since.  I set up this live example to show the difference: http://plnkr.co/edit/nwH1bCDfFrYklwR9X1kQ?p=preview

**Comment by guybedford** [comment]
@butchpeters thanks for sharing. I believe this is fixed on the master branch of SystemJS. Working on getting out a release currently.
