### ISSUE TITLE
commonJS breaks if module also supports AMD !!!

### ISSUE THREAD

**Issue by yoavniran** [systemjs/systemjs#574]
This almost drove me crazy.

Im trying to use a library that supports the 3 formats: commonjs, amd and globals.
So I was expecting everything to work while I was using it through system js.

However the initiation of the module keeps failing because "exports" is undefined. 

This is basically how the module is written:

``` javascript

(function (root, factory) {
    "use strict";

 if ("object" === typeof exports) { 
   factory(root, exports, require("./utils/MyDependency");
 }
else if ("function" === typeof define && define.amd) {
  define("MyClass", ["MyNamedDependency"],  function (MyDependency) {
            return factory(root, root, MyDependency,  true);
        });
}
else{
     root.LibRoot= root.LibRoot || {};
        factory(root, root.LibRoot, root.LibRoot.MyDependency);
}

}(this, function(root, exports, MyDependency, dontExport){
 //do the stuff to create the module here
}));

```

Looks good, right? wrong! because of the check for "define", exports is not created and because of issue: #572 that I reported yesterday, the define only creates a dummy "a" empty object... :(

For testing purposes, If I remove the check for "define" everything works fine as "exports" is available!
btw, its not enough to comment out the code, I have to remove it...

This is on  jspm 0.16.0-beta.3

I did try to use the meta configuration to set the format to "cjs" but no luck. not sure if I used the correct name since the library resides under jspm_packages/github... so I tried:

``` json
meta: {
     "github:orgName/libName@master":{
          "format": "cjs"
     }
}
```

Is there anything I can do to work around this issue? besides modifying the downloaded code of the library?

thanks.

**Comment by guybedford** [comment]
Yes this can be confusing - because we have to interpret a module as one format, it means either running it as AMD OR as CommonJS. In the format detection process we let AMD take preference over CommonJS.

You're on exactly the right track setting the meta configuration, but it needs to be for the specific module not the package name. This can be done via:

```javascript
meta: {
  'github:orgName/libName@master/*': { format: 'cjs' }
}
```

Or by replacing the `*` with the actual module path (including .js extension).

I'd be interested to hear further why this is failing as AMD though. Is that the actual JavaScript error? It sounds odd as `exports` would just be the global object in AMD, which is surely defined.

**Comment by guybedford** [comment]
(that is if the exports in the factory closure IS undefined, that sounds suspiciously like a bug)

**Comment by yoavniran** [comment]
So the problem is two fold actually.

since AMD exports seem to fail because of the named dependency (see my issue: #572) I was hoping for exports to work. 

both "module" and "exports" are undefined within the factory closure when AMd is detected so that fails.

Luckily the meta format configuration does the trick, thanks!

**Comment by guybedford** [comment]
If I run your example factory module code above, the `exports` in the factory function is definitely defined. But the exports are returned to the module because `exports` is set to `window`. That is `window.exportName` is set but not on the returned AMD module. Again, I think this is invalid AMD.

**Comment by yoavniran** [comment]
sorry, something seems to be broken to me.

Running the same code with meta configuration:

``` javascript
System.config({
  "meta": {
    "github:yoavniran/chronosjs@master/*": {
      "format": "cjs"
    }
  }
});
```
This works:

![Uploading systemjs-amd-with_meta_config-with_amd.png…]()

Without changing the module's code, only removing the meta configuration and refreshing, **breaks** = no exports + no module:

![Uploading systemjs-amd-no_meta_config-with_amd.png…]()

Now, (only) removing the AMD support from the module and refreshing, back to work:

![Uploading systemjs-amd-no_meta_config-no_amd.png…]()

**Comment by guybedford** [comment]
Yes, `exports` is not defined for AMD modules, because we want to hit the AMD branch of the code at line 15. The issues then are exactly that this is a named define with dependencies (which won't work as described in the other issue) and also that `root` is taken to be the `window` object for the AMD module. Both of these decisions are incorrect use of AMD by the author of this code.

**Comment by guybedford** [comment]
This is just the way the format detection works unfortunately. These mechanics are one of the primary things to be aware of when developing with SystemJS.
