### ISSUE TITLE
optional transpiler cache in localStorage?

### ISSUE THREAD

**Issue by ohjames** [systemjs/systemjs#601]
It seems to me a bunch of time could be saved on reload if transpiled code could be loaded from a cache, I'm not certain but currently all the code is transpiled on every reload?

If not I guess a simple cache of `{ "systemjs:prefix:" + md5(sourceCode): transpiledCode }` should suffice? It seems the local storage limit is 5 megabytes per domain though, so perhaps the transpiled code should also be compressed, I dunno.

Or maybe it's better just to handle it at the build system level, transpile the code server side and point systemjs at that?

**Comment by ohjames** [comment]
Actually compressing the transpiled Code would be silly it's better just to tell the user to reconfigure the browser. It's in about:config in firefox and defaults to 5mb.

**Comment by Munter** [comment]
I think localstorage wold be a bad call given its synchronous api. The whole browser data storage story is a mess :(

I would be prefer to have an optional jspm-server that instructs the client that the server will take a care of all transpilation, so the client should just fech the url from the server. The server can do all manners of caching, and thus you should get maximum benefit from 304 response headers

**Comment by ohjames** [comment]
It's an async API as you can tell from it returning a promise. Although I don't believe asynchrocity is relevant to the issue of caching. Why do you believe local storage is "a mess"?

A special jspm server wouldn't be necessary, you can already precompile to commonjs server side.

**Comment by Munter** [comment]
I can do all sorts of precompile up front, yes. But if I do, that toolchain needs to be manually configured, and possibly the source code, and certainly the systemjs config.

What I'd like is to provide an opt-in tool that plugs in to the existing ecosystem without having to modify one single thing. It has to work on the premise of your existing code and leverage the knowledge of the existing configuration. There is no reason a server shouldn't be able to run systemjs and execute the translate hook of all loaders, while instructing the runtime not to. Then you build a cache on top of that and you're golden.

Localstorage is a mess because it's synchronous, can run out of space and in this case would purely be used as a hack for lack of access to the real browser cache. A service worker would have that access, but it would require a lot of extra from the consumer to leverage it

**Comment by ohjames** [comment]
Thanks for the clarifications and information, I'll close this issue while I consider the problem further.

**Comment by ohjames** [comment]
@Munter I wrote a configuration using `sigh` and `babel` that transpiles the es6 files (in the folder `src`) and outputs files to `lib` using the `system` module loader. I just need to have my `config.js` point at `lib` instead of `src` and I seem to get all the benefits of cached transpiled code. Even better my tests and browser don't have to both do the transpilation.

I'm really interested in your ideas for a jspm-server, I wonder what it could provide on top of the setup I just explained! Thanks once again for your patience and your time.

**Comment by ohjames** [comment]
This setup also distributes the transpilation over multiple CPUs and watches the source files and performing incremental rebuilds as they change and reloading the browser via livereload after transpilation is finished.

**Comment by Munter** [comment]
The server would provide the benefit of being able to reconfigure your frontend to consume the transpiled sources. How did you tell systemjs to not transpile in the browser after you made that setup? Did you also have to change your source code to disable that?

Ultimately I think the task runner approach is flawed, you can see my reasoning behind that in my [talk about making the transpiler flow simpler](https://www.youtube.com/watch?v=yBtQBvOv1z8&index=23&list=PLBevk0eXLOGfkVhE7PArRg6nKHqmMKgtB). I'm working on getting transpilation baked into a file system, which has a lot of benefits. The biggest one being that your urls never change

**Comment by ohjames** [comment]
> How did you tell systemjs to not transpile in the browser after you made that setup?

It isn't necessary, systemjs detects the type of module with a regex to determine whether it needs to be transpiled or converted from AMD/System etc. Task runners are definitely not a good way of building code but I think asset pipelines are cool. Not sure what you mean about URLs not changing.

**Comment by guybedford** [comment]
Yes the best cache is always the browser cache. A serving layer can be written for SystemJS that runs the plugin translation and module format compilation so that everything is CSP-compatible anonymous System.register / System.registerDynamic code. Has been the plan for a while, just don't have the resources to work on such a thing right now unfortunately.
