### ISSUE TITLE
Unable to find definition of 'require'

### ISSUE THREAD

**Issue by varghesep** [systemjs/systemjs#622]
I'm using **systemjs** in an ASP.NET MVC6 application. In the gulpfile.js, I have a task to compile a HelloWorld.jsx to HelloWorld.js file. I have shown below both the files. The application works if I include **react.js** as a script tag but not when I use *systemjs*.

The error that I see is *Uncaught ReferenceError: require is not defined*

I don't know whether or not I'm using the right pattern to use jsx as components. I appreciate your help in making all these pieces work together. 

```javascript

gulp.task("babel", function() {
    gulp.src("./Scripts/*.jsx")
        .pipe(babel())
        .pipe(gulp.dest(paths.webroot + "js/"));
});

```

**helloworld.jsx:**

```javascript

import React from 'react';

var HelloWorld = React.createClass({
    render: function () {
        return (<h1>Hello World</h1>);
    }
});

var parent = document.querySelector('#greeting');
React.render(<HelloWorld />, parent);
```
**helloworld.js:**

```javascript
'use strict';

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _react = require('react');

var _react2 = _interopRequireDefault(_react);

var HelloWorld = _react2['default'].createClass({
    displayName: 'HelloWorld',

    render: function render() {
        return _react2['default'].createElement(
            'h1',
            null,
            'Hello World'
        );
    }
});

var parent = document.querySelector('#greeting');
_react2['default'].render(_react2['default'].createElement(HelloWorld, null), parent);
```

The **bower.json** file having only the packages. It does not have requirejs, commonjs or amd.

```javascript
{
  "name": "ASP.NET",
  "private": true,
  "dependencies": {
    "bootstrap": "3.0.0",
    "bootstrap-touch-carousel": "0.8.0",
    "hammer.js": "2.0.4",
    "jquery": "2.1.4",
    "jquery-validation": "1.11.1",
    "jquery-validation-unobtrusive": "3.2.2",
    "react": "0.13.3",
    "systemjs": "*"
  }
}
```

**Comment by guybedford** [comment]
Are you getting the error when loading `helloworld.js` or `react.js`? If you can share the stack here that would help. It is likely due to the module format not being detected correctly - this can be set via meta configuration. See https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md for more info.

**Comment by varghesep** [comment]
I'm seeing the error in the html file where I have included the *helloworld.js* in a script tag, so not when react.js is loaded.

The code stack is **HTML5 (Web) + ReactJS + ASP.NET MVC6**. The build stack is **Visual Studio 2015 + Gulp + Bower + SystemJS **

I appreciate if you can answer some of these questions:

1. Is there any settings I have to code in **gulpfile.js** file where I have to tell *system.js* to use babel as the React JSX compiler so the JSX file will be compiled into JS file?

2. React recommends to use [webpack/browserify](http://facebook.github.io/react/docs/getting-started.html) for module management which I don't have. Am I correct in saying I don't have to use any other module management if I use system.js?

3. Can *system.js* work with the JS file generated from JSX by the **babel**? I ask this because it has the *require* which is causing the problem. Should that be *import* and not *require*?

**Comment by guybedford** [comment]
It would be worth first testing that you are able to just create a page and load `react` on its own. How are you setting up react or locating its js file? React has to be interpreted as the right module format in order to load correctly (as mentioned in the docs on module formats above).

Your build process should work as it stands, but I think that's the main thing to look at. It just sees the file generated by Babel as a "CommonJS module" (which uses the `require` function). Each JS file will be recognized as a single module format, but if it gets detected as the wrong one, SystemJS won't know how to load it properly.

**Comment by guybedford** [comment]
Closing, but feel free to continue discussion here.
