### ISSUE TITLE
Support existing source maps in code

### ISSUE THREAD

**Issue by matthewbauer** [systemjs/systemjs#638]
This is an obscure error that can be fixed by leaving out the export name field, but:

If a global module has a last line that is a source map, it should stay as the last line. But, see:

[lib/global.js#L85](/systemjs/systemjs/blob/adf3c24559d451c89412a131fff13e735918b5d9/lib/global.js#L85)

where execute method will add on to the source.

It makes me think that source maps need to be more robust than the last line thing but I am pretty sure I can confirm it's broken.

https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k

**Comment by guybedford** [comment]
Yes existing source maps in these formats would be broken here. We can certainly add back in the detection to check if the last line is a source map comment before adding the wrapper before that line. Also wrappings before the code can be made to be a single line and not many lines so that only the first line of the source map is interfered with, and the rest all line up still.

**Comment by manland** [comment]
:+1:

**Comment by guybedford** [comment]
Code after the `//# sourceMappingURL` comment doesn't actually affected it still being read in browsers. If there is a case though, where code after this at the end of the file stops the source map, then we can come back and reconsider this.
