### ISSUE TITLE
Dependency no longer working in SystemJS 0.18.6

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#655]
The output of the following code has changed with the new version of SystemJS:

``` js
System.config({
    paths: {
        'ophan/ng': 'http://j.ophan.co.uk/ophan.ng.js'
    }
});
require(['ophan/ng'], function (ophan) { console.log(ophan.record); });
// 0.18.4:
// => function
// 0.18.6:
// => undefined
```

Do you have any ideas why?

**Comment by OliverJAsh** [comment]
This is another good example of why we need https://github.com/jspm/jspm-cli/issues/743

**Comment by guybedford** [comment]
This is actually by design - it was a bug that it did work.

If you log `System.defined` you'll see what's going on here.

Basically `orphan/ng` uses named defines to define its modules (its a bundle). The named define it uses is `orphan/ng` which gets stored in the registry. We used to automatically add the default `.js` extension to this. That used to make the bundle name and import name coincidentally match up. Now that we don't the import is `orphan/ng.js` while the bundle name is `orphan/ng` that is they don't match up.

The following will work:

```javascript
System.config({
  paths: {
    'ophan-bundle': 'http://j.ophan.co.uk/ophan.ng.js'
  },
  packages: {
    'ophan': { defaultExtension: false }
  }
});
System.import('ophan-bundle').then(function() {
  System.import('ophan/ng').then(function(m) {
  });
});
```

Ideally we could avoid the nested System.import with a bundles configuration, but unfortunately the bundles configuration normalization isn't compatible with this. I've created an issue for this at https://github.com/systemjs/systemjs/issues/660.

**Comment by guybedford** [comment]
Here's a config that will work here:

```javascript
    System.bundles['http://j.ophan.co.uk/ophan.ng.js'] = [System.baseURL + 'ophan/ng'];
    System.config({
      packages: {
        'ophan': {
          defaultExtension: false
        }
      }
    });
    System.import('ophan/ng');
```

Will be less of a hack when defaultJSExtensions can be turned off.

**Comment by OliverJAsh** [comment]
Oddly enough, this seems to be working in SystemJS 0.18.8?

**Comment by guybedford** [comment]
Yes I reverted the bundle extension adding changes.
