### ISSUE TITLE
Docs config recipes page

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/systemjs#676]
As mentioned in https://github.com/systemjs/systemjs/issues/669#issuecomment-128468777 it might be interesting to create a configuration recipes / examples / scenarios page. 
I think most examples belong to specific parts of the documentation, like how to configure loaders, use globals etc. 
One example I can come up with is using Three.js and Three.js example code (from three.js package).

**Comment by JavascriptMick** [comment]
+1 for this.  Lots of confusion in this space, especially now with the angular-cli project choosing system.js for module loading.  If it wasn't already, system.js has now gone 'mainstream' and all sorts of folks are grappling with importing external modules into their Angular2/angular-cli/system.js projects.

**Comment by backspaces** [comment]
@peteruithoven: Do you have an example that works for three.js & the examples, like OrbitControls?

I've tried to get an answer for this from the Three folks 
https://github.com/mrdoob/three.js/issues/9562#issuecomment-261747407
but I think they're not considering moving away from script tags soon.

I'll probably go with the "OneScript" approach unless I can figure out a reasonable System.config solution. Sigh!

**Comment by peteruithoven** [comment]
Looking at https://github.com/mrdoob/three.js/issues/4776 I'm pretty sure people worked hard to enable other import methods than script tags. 

It's been a while since we figured this out, but we have been using it for many months. 
Looking at our `package.json` I think we've installed three.js using something like:
`jspm install three.js=github:mrdoob/three.js@r75 -o '{"format": "global}'`
And we have some extra `map` and `meta` configuration in `jspm.config.js`
``` js
SystemJS.config({
  ...
  meta: {
    ...
    "src/js/app.js": {
      "deps": [
        "three.js"
      ]
    },
    "three.js/controls/EditorControls": {
      "deps": [
        "three.js"
      ]
    },
    "three.js/postprocessing/ShaderPass": {
      "deps": [
        "three.js"
      ]
    },
    "three.js/postprocessing/RenderPass": {
      "deps": [
        "three.js"
      ]
    },
    "three.js/postprocessing/EffectComposer": {
      "deps": [
        "three.js",
        "three.js/postprocessing/ShaderPass",
        "three.js/postprocessing/MaskPass",
        "three.js/shaders/CopyShader"
      ]
    },
    "three.js/shaders/CopyShader": {
      "deps": [
        "three.js"
      ]
    },
    "three.js/postprocessing/MaskPass": {
      "deps": [
        "three.js"
      ]
    },
    "three.js/loaders/STLLoader": {
      "deps": [
        "three.js"
      ]
    },
  },
  map: {
    ...
    "mrdoob/three.js": "github:mrdoob/three.js@r75",
    "three.js/controls/EditorControls": "github:mrdoob/three.js@r75/examples/js/controls/EditorControls.js",
    "three.js/loaders/STLLoader": "github:mrdoob/three.js@r75/examples/js/loaders/STLLoader.js",
    "three.js/postprocessing/EffectComposer": "github:mrdoob/three.js@r75/examples/js/postprocessing/EffectComposer.js",
    "three.js/postprocessing/MaskPass": "github:mrdoob/three.js@r75/examples/js/postprocessing/MaskPass.js",
    "three.js/postprocessing/RenderPass": "github:mrdoob/three.js@r75/examples/js/postprocessing/RenderPass.js",
    "three.js/postprocessing/ShaderPass": "github:mrdoob/three.js@r75/examples/js/postprocessing/ShaderPass.js",
    "three.js/shaders/CopyShader": "github:mrdoob/three.js@r75/examples/js/shaders/CopyShader.js"
  }
```
We are currently using jspm@beta, but this shouldn't differ much with the stable.

**Comment by backspaces** [comment]
Thanks, *really* helpful. Another question?  What is three.modules.js?
Would it help make system.js usage easier?

Thanks again

   -- Owen

**Comment by backspaces** [comment]
Sigh, I ran into a problem _using_ OrbitControls after successfully importing it. This is the simplest example of it I can make.

Here's the usual System bootstrap for two imports: three.min.js and OrbitControls.js, in etc/ & etc/threelibs/ respectively.
```
<script>
  System.config({
    meta: {
      'etc/three.min.js': {
        format: 'global'
      },
      'etc/threelibs/OrbitControls.js': {
        globals: { THREE: 'etc/three.min.js' },
        deps: [ 'etc/three.min.js' ],
        exports: 'THREE.OrbitControls'
      }
    }
  })
  System.import('lib/foo.js')
</script>
```
The foo.js simply creates a renderer, camera, and orbit, a new OrbitControls.  See below.

This works, but it does so by creating a window.THREE as well as a local THREE, apparently because of the format: global.

Commenting out the format: 'global' for etc/three.min.js, there is no window.THREE, just the module THREE. 

The _loading_ for OrbitControls works (the exports: of THREE.OrbitControls basically requires no THREE to be present), but the _use_ of OrbitControls via `new` fails, THREE undefined, even tho it has a globals: for THREE.

If I add back the format: 'global' for three, and comment out the deps: (not needed anyway I think) and globals: for OrbitControls, leaving just the exports:, it works, using window.THREE.

Am I misunderstanding how globals: works? I assumed it adds/removes a THREE variable during use of the module. It's my impression that just this should work:
```
<script>
  System.config({
    meta: {
      'etc/threelibs/OrbitControls.js': {
        globals: { THREE: 'etc/three.min.js' },
        exports: 'THREE.OrbitControls'
      }
    }
  })
  System.import('lib/foo.js')
</script>
```
   -- Owen

```
import * as THREE from 'etc/three.min.js'
import OrbitControls from 'etc/threelibs/OrbitControls.js'

console.log('THREE', THREE, 'window.THREE', window.THREE)
console.log('OrbitControls', OrbitControls)
console.log('THREE.OrbitControls', THREE.OrbitControls)
console.log('window.OrbitControls', window.OrbitControls)

const renderer = new THREE.WebGLRenderer()
renderer.setSize(window.innerWidth, window.innerHeight)
document.body.appendChild(renderer.domElement)

const camera = new THREE.PerspectiveCamera(
  45, window.innerWidth / window.innerHeight, 1, 1000)

const orbit = new OrbitControls(camera, renderer.domElement)

console.log(renderer, camera, orbit)
```

**Comment by peteruithoven** [comment]
As far as I understand and remember it SystemJS as little control over the globals, they are created by a package. I didn't need any `globals` configuration. The Three.js packge should simply add itself to window (as it would in a script tag). 
For the same reason I probably didn't need to specify `exports`, because those examples / libs would make themselves accessible through THREE.library. Looks like `exports` are useful if you want to access that value through the module's import statement. 
You do need to clarify of which modules Three is a dependency, that's why we used the `deps` config. 

I had the same feeling about using window.THREE, but that's not something SystemJS controls, as far as I know. 

Could you clarify (write as comment) what came out of those console.log's in that last example?

**Comment by backspaces** [comment]
Hi Peter, thanks for the guidance through the minefield of "legacy" .. global modules, and the brave new world of es6 modules. 
- Nice to know that our findings agree: experimenting around with the System.config, we can get import/export to work, although with somewhat odd results with two THREE's .. a local one and a global one. 
- I think other workflow tooling would give different results .. jspm, rollup, webpack, etc. This can cause confusion in conversations like this. This is why I use none of those, just babel and the systemjs transform, although I certainly would jump on one if it helped.
- My goal, which you helped me reach, thanks!, is simply standard es6 syntax/semantics, and the same local variables for all imports, so that When Modules Arrive, I don't need to change my code, just remove System etc. We'll see!
- The console.logs were simply to see if the imports landed multiple THREE and OrbitControls variables.

So going forward, I'm writing a simple script that will convert the examples files into es6 module format. I did that by hand for OrbitControls and it works perfectly:
- Convert THREE.OrbitControls to simply OrbitControls everywhere.
- Add the THREE import at the top, and the export OrbitControls at the bottom.
This worked, but I need to automate it, so I can use all 177 of them. Yup, 177:
```
cd node_modules/three/examples/js/
grep '^ *THREE\.[^ .]* =' */*.js
```
This would let me be even closer to That Great Day when all projects support modules.

BTW: Speaking about conversion between es5 <> es6, including modules, it would seem to me better to start with an es6/modules base and simply use babel and other tools to convert back to es5/no-modules.

I'd also like the repos to supply a non-rollup, individual files folder of the project. This means imports/exports would give you just the code you need. Yeah, I know: tree-shaking etc but with http/2 and strict module semantics, I'd prefer individual files. For example, importing only the webgl modules.

Good luck and thanks again for the help.

**Comment by backspaces** [comment]
Here's what I ended up with for three/examples modules:
https://github.com/mrdoob/three.js/issues/9562#issuecomment-263076288
