### ISSUE TITLE
loader for plugin definitions

### ISSUE THREAD

**Issue by smcmurray** [systemjs/systemjs#688]
I am investigating Systemjs by porting a little AMD project.
I have started by simply adding a meta for '*.js': { format: 'amd' }

But when I try to load the text plugin, it fails because exports is undefined. What loader or format should I set for Systemjs plugins if all other *.js are set to amd?

**Comment by WorldMaker** [comment]
In general SystemJS should attempt to [auto-detect module format](https://github.com/systemjs/systemjs/wiki/Module-Format-Support#format-detection). Have you tried skipping the meta option and letting it auto-detect, only using the meta to override any it gets wrong? It's auto-detection has been correct in every case for me thus far.

Most plugins I've seen are either CommonJS or ES6 module format, and ES6 is the heavy favorite going forward. You probably have to actually open up each one to determine which format. If it is failing because exports is undefined my first guess would be CommonJS, but that's a guess without looking at the code myself.

I suggest just letting SystemJS module format detection do its job.

**Comment by guybedford** [comment]
Yes exactly, the plugin is CommonJS so can't be loaded as amd.
