### ISSUE TITLE
Applying package map to package meta path

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/systemjs#700]
Following up with https://github.com/systemjs/systemjs/issues/662#issuecomment-130269315 I'd like support for meta paths inside packages config to go through the map defined in that package config. 
Mainly because it creates more readable config and because I think it's a confusing limitation. 

Enabling for example:
``` javascript 
System.config({
  packages: {
    "three": {
      "map": {
        "./loaders/STLLoader": "./examples/js/loaders/STLLoader.js"
      },
      meta: {
        "loaders/STLLoader": {
          "deps": [
            "three"
          ],
          "globals": {
            "THREE": "three"
          },
          "exports": "THREE.STLLoader",
          "format": "global"
        }
      }
    }
  }
});
```

**Comment by guybedford** [comment]
Unfortunately this is not possible. The reason we can't do this is actually because of an undocumented feature, and that is conditional environment maps. Basically package maps are allowed to vary based on the environment to allow loading different versions of modules in different browsers / devices / locales etc. This package map needs to load asynchronously, while meta needs to work synchronously and be tied to the target module and not the original map name when we allow one-to-many environment maps.

For example you could write:

```javascript
System.config({
  packages: {
    'foo': {
      map: {
        browser: {
          './index.js': './index-browser.js'
        }
      }
    }
  }
});
```

Where the `browser` condition needs to be loaded asynchronously.

As such, meta needs to always be thought of as applying to "real paths" in the package. It should always be thought of that for all meta anyway. The handling of global map is more of an aliasing convenience over a virtual naming system, while package submap (`./x`) enables a sort of virtual naming system that we do need to distinguish from real paths.

Hope that makes some sense, it's very much a coding problem, although as I've attempted to explain the usability makes some sense I believe.
