### ISSUE TITLE
Modules loaded before global dependencies are loaded

### ISSUE THREAD

**Issue by Mosho1** [systemjs/systemjs#727]
I load several scripts from cdnjs using SystemJS. I set the up in `config.js` under `paths`, for example:

    paths: {
        "angular": "//cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.2/angular.min.js",
    }

This works well, but in the case of angular, moment and d3, I have to set `format: "global"` for them to work. This seems to result in a race where sometimes modules that require one of the above are executed and the module they import as the respective global module is an empty object. 

This happens around 5-15% of the time and seems to depend on the machine used/internet connection/ code itself, so it seems pretty random and leads me to my conclusion that it's a race.

**Comment by Mosho1** [comment]
I removed the `format` meta configuration from the 3 packages (angular, moment and d3) and everything seems to be working properly. That is, the app still runs (although this wasn't the case back when I added the configuration, I assume this was changed?). I see that the scripts are now imported using XHR and not script tags, like the rest of the cdn packages I import, that all work fine.

**Comment by guybedford** [comment]
You have to make sure that anything that depends on angular has an explicit dependency on angular. Otherwise things may work but you'll get timing issues if angular loads too late and something loads before it that didn't declare its dependency this way. Altering the format may alter the timing, or if it is AMD, that may catch the angular dependency as well.

**Comment by Mosho1** [comment]
I see, thanks for the tip!
