### ISSUE TITLE
Workflow to use React-Art in browsers

### ISSUE THREAD

**Issue by varghesep** [systemjs/systemjs#780]
Could you please suggest a good workflow to make [React-Art](https://github.com/reactjs/react-art) working in browsers. **React-Art** comes as only **npm** package. There is no bower package for React-Art neither CDN to work in the browsers.

I may have to use Browserify or webpack to create a browser version. However, looking for a short cut to use the npm package directly through systemjs to use on the browser. I use an ASP.NET MVC6 app, so it has already **bower**.

**Comment by guybedford** [comment]
@varghesep SystemJS needs configuration in order to understand npm modules. If you use jspm, it will create this configuration for you when running `jspm install npm:react-art`. Otherwise custom package configs in SystemJS can be worked out but takes a little consideration to understand the relations. If you do try installing with jspm, and are getting install issues, post an issue to the registry there at https://github.com/jspm/registry/issues.

**Comment by varghesep** [comment]
I used **jspm** and it is working fine.

**Comment by guybedford** [comment]
Great, thanks for reporting back.
