### ISSUE TITLE
Module after execute hook

### ISSUE THREAD

**Issue by kanoshin** [systemjs/systemjs#783]
Hi, @guybedford! I have a question. 

In my project I have a lot of so-called 'services', service has the following structure:
```javascript
var serviceA = function(){
    this.init(); // service initialization code
    this.load = function(){
        return asyncLoadA(); // returns promise, for example service is asynchronously reading data
                             // required for it's work from file or webSql
    }
}

var serviceB = function(depA){
    this.init(depA.data);
    this.load = function(){
        return asyncLoadB(depA.data);
    }
}

var a = new serviceA(), b;
a.load().then(function(){
    b = new serviceB(a).load();
})
```
So, services are dependent on each other and have async load function, and dependent service can be created only when it's dependencies are loaded. Example above is a pure javascript, but can be easily rewritten as ES6 modules.

Is it possible to load such services via system.js plugin (I don't want to modify system.js library source)? All I need is to delay module execution until it's dependencies are not ready. It seems that instantiate hook is not good for it because I still want standard ES6 linking and execution to work.

**Comment by guybedford** [comment]
@kanoshin you could potentially write a plugin for a service allowing code like:

```javascript
import data from 'my-db-service-name!db-service'
```

Or something like that, although it's probably more advisable just to export a promise from the service module, and rely on that. Mainly because you want to ensure you handle the failure cases properly, instead of having it become a global failure. So doing it via a promise system would give you this level of expressibility in the code.

**Comment by kanoshin** [comment]
But it means that I would have to manually wait for each promise:

```javascript
import aServicePromise from 'aService'
import aServicePromise from 'aService'
import aServicePromise from 'aService'

```

**Comment by guybedford** [comment]
Yes exactly.
