### ISSUE TITLE
Conditional loading problem in version 0.19

### ISSUE THREAD

**Issue by omerts** [systemjs/systemjs#824]
Hello,

I have been using conditional loading with version 0.18, which was working great. After moving to version 0.19, it seems that the way paths are resolved has changed, and isn't consistent between client and server. 

c:/fe is my base directory. 
Code in 0.18 (under: c:/fe/client/app/FetchSelector.js):
```javascript 
var path = '../../jspm_packages/npm/superagent@1.3.0/lib/node';

if (typeof window !== 'undefined' || 
    (typeof global !== 'undefined' && typeof global.bundle !== 'undefined')) {
  path = '../../jspm_packages/npm/superagent@1.3.0/lib/client';
}

export default path;
```

Running the above on server, tries to resolve from the base of my project directory, in my case c:/fe/../../jspm_packages..., which of course isn't the right path. Changing the code to:
```javascript 
var path = './jspm_packages/npm/superagent@1.3.0/lib/node';

if (typeof window !== 'undefined' || 
    (typeof global !== 'undefined' && typeof global.bundle !== 'undefined')) {
  path = './jspm_packages/npm/superagent@1.3.0/lib/client';
}

export default path;
```
works on the server side, but client side is looking for the path from the client's working directory, which is: /client/app/jspm_packages/npm/superagent@1.3.0/lib/client.js

**Comment by guybedford** [comment]
Can  you clarify exactly how you are running the require here of `path`? Is this using the interpolation syntax - `#{path}`?

**Comment by omerts** [comment]
```javascript
import agent from '#{FetchSelector}';
```

**Comment by guybedford** [comment]
The path would be resolved to the baseURL, not relative to the file doing the importing. This is because interoplation happens after applying all other normalizations.

So if your client baseURL is `client/app` then that is what would be loaded.

The better way to use conditional interpolation is to only substitute the part of the path that changes:

```javascript
import agent from 'npm:superagent@1.3.0/lib/#{env-type}
```

Where `env-type` is a conditional returning either `client` or `node`. I've added https://github.com/systemjs/systemjs/commit/cb0328999d50dbd2066f5b2d5b3b68c54f63da68 to restrict this usage in future.
