### ISSUE TITLE
Is import overloading part of the spec?

### ISSUE THREAD

**Issue by trusktr** [systemjs/systemjs#895]
Is it possible to define what happens if you

```js
import fragmentShader from 'path/to/fragment.glsl'
```

in the upcoming loader spec?

**Comment by kresli** [comment]
Im just guessing you can do this in a systemjs plugin.

**Comment by trusktr** [comment]
I know, but I'm wondering if it'll be possible with the native loader API in the future (when it becomes native).

**Comment by kresli** [comment]
Good question! Let me think loud about this. So when this will be a native implementation ( if it will be ) you will still need to handle different file formats than js. If you need to import lets say .osm file which have different syntax than js, then you need to have some transpiler or library for handle this. Otherwise the import method would be quite useless. But thats just my own view on this.

**Comment by trusktr** [comment]
@kresli That's true. SystemJS and JSPM could still continue to transpile even if custom file types aren't supported natively.

@guybedford ?

**Comment by guybedford** [comment]
SystemJS supports this via plugins, and everything SystemJS does works on top of the module loader spec APIs (https://github.com/ModuleLoader/es6-module-loader/blob/master/docs/loader-extensions.md is the description of the old hooks, which remain roughly the same), so yes.
