### ISSUE TITLE
A build without any ES5 / ES6 pollyfils  

### ISSUE THREAD

**Issue by pkozlowski-opensource** [systemjs/systemjs#900]
@guybedford did you consider providing a build that wouldn't add any ES5 / ES6  polyfills? Most of the time people already have those for older browser they need to support so it is a pity that we are duplicating those.

Any thoughts on this?

**Comment by guybedford** [comment]
Which polyfills specifically are you referring to here, the `core-js` ones?

If so that is then more of a jspm issue here.

Allowing custom Babel presets for builds will be the way to handle this stuff, which is completely possible by refining the Babel configuration, although this should become more transparent with the Babel 6 upgrade what exactly is applying.

We can also look at adding jspm-style package configuration to core-js itself, that would automatically null out polyfills not needed in the browser environment. This would be possible via conditional package configuration.

Feel free to play around with these workflows. I'm aiming to get the Babel 6 upgrade in with jspm 0.17 at the moment.

**Comment by guybedford** [comment]
Let me know this made sense or if I misunderstood which polyfills you were referring to here at all. Closing as it's out of scope of SystemJS as described.
