### ISSUE TITLE
Requiring file that was specified in an error message string

### ISSUE THREAD

**Issue by staxmanade** [systemjs/systemjs#903]
Hey there,

First want to say I'm LOVING this project. 

While prototyping something I tried pulling in the following project.

```
import postcssJs from 'npm:postcss-js';
```

Which resulted in
```
Uncaught (in promise) Error: XHR error (404 Not Found) loading https://registry.jspm.io/postcss-safe-parser.js
	Error loading https://registry.jspm.io/postcss-safe-parser.js as "postcss-safe-parser" from https://npm.jspm.io/postcss@5.0.10/lib/parse.js
    at o (https://jspm.io/system@0.19.1.js:5:13210)
    at XMLHttpRequest.s.onreadystatechange (https://jspm.io/system@0.19.1.js:5:13735)
```

It looks like it's trying to load `postcss-safe-parser` which is defined in `postcss/lib/parse.js` - but if I look at the [source code](https://github.com/postcss/postcss/blob/master/lib/parse.es6) there is no module attempting to be loaded. It looks like it's an error string that's defined this (I don't think SystemJS should be trying to load this module).

Here is the source for convenience:

```
import Parser from './parser';
import Input  from './input';

export default function parse(css, opts) {
    if ( opts && opts.safe ) {
        throw new Error('Option safe was removed. ' +
                 'Use parser: require("postcss-safe-parser")');
    }

    let input = new Input(css, opts);

    let parser = new Parser(input);
    parser.tokenize();
    parser.loop();

    return parser.root;
}
```

Any thoughts?

**Comment by guybedford** [comment]
It's great to hear you're enjoying the project. Has been a lot of work!

This issue is due to the way SystemJS parses require statements, catching the string itself there.

There is actually a fix for this at the PR - https://github.com/systemjs/systemjs/pull/726, which has just been waiting for enough people to hit it for it to make sense to land, as it will introduce a minor performance slowdown. I think this sounds like justification enough for it though, and have gone ahead and merged that in.

**Comment by staxmanade** [comment]
So awesome! :+1: Thank you!
