### ISSUE TITLE
Restrict `@node/x` imports to core Node modules

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#905]
To avoid invalid use cases of using this feature to load non-core load modules.

//cc @PinkaminaDianePie

**Comment by PinkaminaDianePie** [comment]
i never seen in any documentation how this feature works. so at first it wile nice to see some explanation anywhere. imusing systemjs under nodejs and faced with this cases:
1) i need to load node core module, such as ```fs```
2) i need to load external module from node_modules, such as ```express```
3) i need to load es6 external module from node_modules, which had not transpilled. I want to load it via systemjs on its import.

1 and 2 can be achieved with import ```'@node/x'``` but i dont know what can i do with 3d case.

**Comment by guybedford** [comment]
@PinkaminaDianePie I'd suggest following the recommended workflow here as described in https://github.com/systemjs/systemjs#nodejs. Only use `import '@node/fs'` to import Node core modules, not arbitrary modules. I've added this restriction now.

Loading libraries like `express` is not supported in SystemJS as it doesn't follow the Node resolution algorithm. It sounds like your needs may be better served by other tools than SystemJS, which focuses primarily on the browser.

**Comment by PinkaminaDianePie** [comment]
i use SystemJS only because i need override module loadin process, for example ```System.fetch``` or  ```System.translate```. Writing own polyfill is too long. I choose SystemJS because it is closest to the spec and when new spec will be shown in es2016 or later it will be easier to migrate to it from SystemJS than another loader. For now it will be enough to use current version, which can be used for loading any module from ```node_modules```

**Comment by guybedford** [comment]
Released in 0.19.6.
