### ISSUE TITLE
Unable to load @reactivex/rxjs

### ISSUE THREAD

**Issue by varghesep** [systemjs/systemjs#931]
My angular2 component has the following imports

```javascript
import {Component, View, bootstrap, NgFor} from 'angular2/angular2';
import {Http, HTTP_PROVIDERS} from 'angular2/http';
import * as Rx from '@reactivex/rxjs';
```
Since I've already installed **rxjs** via npm, I'm getting  the intellisense in the component.

This is what I have in the index file:

```javascript
<script src="https://npmcdn.com/@reactivex/rxjs@5.0.0-alpha.10/dist/global/Rx.js"></script>
```

When I run the app I get the error:

```javascript
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:5000/@reactivex/rxjs
```

I'm not using JSPM. All the angular2 components are loading correctly except the **rxjs**.

How can I make sure **@reactivex/rxjs** is loaded during the runtime?

**Comment by jackfranklin** [comment]
This is because the Angular files contain a bunch of `System.register` calls to register themselves as modules that SystemJS then knows about. Looking at the Rx.js source, it doesn't do that.

I think what you'd have to do is set up the SystemJS config to tell it that the above URL maps to `@reactive/rxjs` and that its format is CJS, I think. Have a look here on the docs for module formats and overrides: https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md.

If you want to ping me a link to a repo that recreates this I'm happy to take a look myself.
