### ISSUE TITLE
SystemJS do not execute all modules when one fails.

### ISSUE THREAD

**Issue by singerxt** [systemjs/systemjs#933]
Hello I noticed when we compiling files and one failing rest of modules do not execute I think this is not expected behaviours.

for example when we he have 3 js files script1.js, script2.js, script3.js and script2.js throwing type error.

Example: (Just standart script tags)
```
<script src="script1.js"></script> //this is executed
<script src="script2.js"></script> //throw error
<script src="script3.js"></script> //this is executed
```

When using System.js

```
import s1 from 'script1';
import s2 from 'script2';
import s3 from 'script3';

//magic
```

```
<script>
  System.import('/app/app.js'); // Everything fails script1 and script3 is not executed.
</script>
```

I noticed this problem with current version of [recordrtc module](https://www.npmjs.com/package/recordrtc) (version 5.2.3 throwing type error in Safari)

**Comment by jackfranklin** [comment]
I believe this is by design and actually correct behaviour.

Three script tags compared to three imports aren't identical in how they should function. The way I like to think about it is that:

```js
import A from X;
import B from Y;
import C from Z;

// my module goes here
```

Is creating a singular module that has three dependencies: X, Y and Z. For that module to correctly function, it needs modules X, Y and Z to function correctly and execute. If one or more of them fail, it's impossible to continue executing and defining the module, because it hasn't got all of its dependencies.

Does that make sense?

**Comment by singerxt** [comment]
So what in case when A B C are separated functionalities for example.

```
//contactPage.js
import A from X;
import B from Y;
import C from Z;

let contactPage = () {
  A.initSlider();
  B.initGallery(); //this fails
  C.initFormValidate();
};

exports contactPage;


//index.js

import contactPage from 'contactPage.js';
import crossroads from 'crossroads';

crossroads.addRoute('/contact', contactPage);
```
