### ISSUE TITLE
Sporadically get error: Main.js Interpreted as amd module format, but called System.register.

### ISSUE THREAD

**Issue by feena750** [systemjs/systemjs#970]
After adding the code meta: { '/AppTS/*': { scriptLoad: true } }, to my config.js so that I could debug typescript files in Visual studio I get the following error every 2nd or 3rd time I run my application.  I am not sure why it occurs sporadically:

Error:Module http://localhost:52404/AppTS/Main.js interpreted as amd module format, but called System.register. 

Here is a Gist with the related files: https://gist.github.com/anonymous/8cc442d3ee263efa3203. Also my tsconfig is steup as "module": "system".

Does anyone have an idea as to what may be causing this error?

**Comment by guybedford** [comment]
This can happen for a number of reasons. What web browser are you using here?

**Comment by feena750** [comment]
I was using IE11

**Comment by guybedford** [comment]
Feel free to report back if you track this down further.

**Comment by juminoz** [comment]
I just randomly got this on Chrome/Safari as well (but works fine in FireFox). We just migrated a server to Singapore and gave it a new domain name, but still using the same CDN. What I found is that this only happens in an iframe. The code outside iframe loaded perfectly fine. For my case, I tracked it down and found the issue was with importing moment.js and numeral.js using script tags. When I remove them, the problem goes away, but my code obviously would break. Then if I publish the same page in the iframe to a different domain (so it becomes a page outside iFrame), this problem goes away. I'm not sure if it's at all related, but I got this error as well before I got the one mentioned on this thread.

Multiple anonymous defines encountered

And then found this which led me to a workaround I'm currently using while I'm building the page.

https://github.com/cujojs/curl/issues/283

What's very strange is that it's only happens on a particular domain and inside iframe only. If you are up for it, I can screen share and show you on Skype. Maybe we can figure out something that will help other people as well.
