### ISSUE TITLE
Use systemjs import in ES6 project

### ISSUE THREAD

**Issue by mildful** [systemjs/systemjs#981]
Hi everyone.

I'm working on an ES6 project and I would like to load a HTML file (as text) in a class. Something like this :

```javascript
"use strict";

import myHTML from './file.html!text';

export default class MyClass {

  constructor() {
    this.html = myHTML
  }

}
```
So I'm using SystemJS to achieve that. This is my configuration :
```javascript
"use strict";

System.config({
    baseURL: '/',
    map: {
        text: './vendor/systemjs_text.js'
    }
});
```
But when I'm trying to import my HTML, an error is throw by gulp on the transpilation task :
`Error: Cannot find module 'login.html!text' from ...`

So is there a conflict between ES6 syntax and systemjs syntax ? Or what I am doing wrong ? How can I retrieve my html ?

**Comment by sberney** [comment]
Does `System.import('file.html!text')` work? I don't see anything about `login.html` in your code, so I'm assuming it's the same as `file.html`.

**Comment by mildful** [comment]
Sorry for the delay.

```javascript
System.import('./modules/login.html!text').then((res) => {
    console.log(res)
});
```
Works fine, thanks. But I think I missunderstand something with this syntax.
System.import() returns a promise so I need to wait for the result. But doing something like this seems pretty bad : 

```javascript
"use strict";

System.import('path').then((html) => {
  export default class MyClass {

    constructor() {
      this.html = html;
    }

  }
});
```

And I can't do this because I need to instantiate the class right now :
```javascript
"use strict";

export default class MyClass {

  constructor() {
    System.import('path').then((html) => {
      this.html = html;
    });
  }

}
```
So when I create my MyClass object, `this.html` is `undefined`.


If that can help, my class is a Backbone view. Here is the right code :
```javascript
"use strict";

import BaseView from '../views/base.view';
import LoginModel from './login.model';
//import HTMLTemplate from 'login.html!text';

export default class LoginView extends BaseView {

    constructor(opts) {
        super();

        this.el         = document.getElementById('core');
        this.model      = new LoginModel();
        this.events     = {
            'click #test': 'login',
        };

        System.import('./modules/login.html!text').then((res) => {
            this.template = res;
        });
    }

    initialize () {
        this.listenTo(this.model, "change", this.render);
    }

    render () {
        this.el.innerHTML = this.template;
    }

    login (e) {
        console.log(e, 'foobar');
    }

}
```

Oh and one last thing. System.import() cannot take a relative path ? When I say `'./modules/login.html!text'`, the `.` represents the folder of my app.

**Comment by sberney** [comment]
`System.import` returns a promise, as you noticed. In javascript, you can't generically turn promisified async results into sync results (before the advent of the `await` keyword, which I'm guessing internally elevates synchronous code to async), because the code which generates the async result is sitting on the javascript queue, while the currently executing synchronous code is sitting on the stack: the stack must be cleared before the next item on the queue is executed, so your promise-result dependent code must also be placed on the queue (i.e., as a promise).

Fortunately, you don't have to worry about that. You can just use the correct import path. These two lines are different from each other:
```javascript
import HTMLTemplate from './login.html!text';
import HTMLTemplate from './modules/login.html!text';
```

If you can `System.import` the path, then it should work as well in an es6 import statement.
