### ISSUE TITLE
architecting a legacy js project (with plugins) to be distributable with jspm and standalone

### ISSUE THREAD

**Issue by sandys** [systemjs/systemjs#989]
hi,
I'm asking this in the context of Handsontable - which is a very, very popular javascript based spreadsheet component. Handsontable is widely used by people as a direct include in their html through script tags. The relevant "dist" is https://github.com/handsontable/handsontable/tree/master/dist

HOT is also pretty flexible and there is a builder to build a version of HOT with only the components you need - https://github.com/handsontable/hot-builder

Handsontable is absolutely impossible to use via npm or jspm or systemjs because of its require system. Take a look at this comment - https://github.com/handsontable/handsontable/issues/2906#issuecomment-167149256.

The question is - is systemjs+jspm a good infrastructure for HOT.. given its goals. One of which is to produce a standalong js component that can be used via direct <script> include.

**Comment by amenadiel** [comment]
Well, this is far from ideal, but you could install HOT with

```sh
jspm install github:handsontable/handsontable@^0.20.2
```

This will create an entry in `config.js` saying that `handsontable/handsontable` translates to `github:handsontable/handsontable@0.20.2`.

If you import `handsontable/handsontable` you will get just the bare module without its dependencies, but you can explicitly point to the full build.

```js
import * as HOT from 'handsontable/handsontable/dist/handsontable.full';
```

Since handsontable doesn't declare ES6 exports, the `Handsontable` takes the place of the `default` export. This means you have to grab it from the `default` property of the imported object

```js
let Handsontable = HOT.default;
console.log('Handsontable is ', Handsontable);
```

And then you are ready to invoke the constructor as if it was in the global scope.

The steps vary a little if you use AMD's define, CJS require or Systemjs.import, but the important part is you actually have to point to the full build yourself.

**Comment by guybedford** [comment]
Responded at https://github.com/jspm/registry/issues/697.
