### ISSUE TITLE
Istanbul support

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#992]
From https://github.com/jspm/jspm-cli/issues/1378.

@Munter suggested this support would be as simple as including [this snippet](https://github.com/podio/requirejs-react-jsx/blob/master/jsx.js#L29-L37) in the translate hook after compilation.

Such a translate hook adjustment could potentially also be done by Istanbul itself by attaching into the System.translate function:

```javascript
if (typeof System != 'undefined' && System.translate) {
  var systemTranslate = System.translate;
  System.translate = function(load) {
    return systemTranslate.call(this, load)
    .then(function(compiled) {
      return injectInto(compiled);
    });
  };
}
```

//cc @typhonrt @gotwarlost

**Comment by typhonrt** [comment]
Thanks for taking a look @guybedford. I moved the example test case to a different location. It can be found here now:
https://github.com/typhonjs-demos/istanbul-jspm-coverage-example

**Comment by dara76** [comment]
Hi,

I've just come across this issue and the one at  https://github.com/gotwarlost/istanbul/issues/498 . 

Could somebody expand on where the code above should be included or added to and what does `injectInto` look like?

Thanks.

**Comment by typhonrt** [comment]
After much gnashing of teeth I have a stable Istanbul instrumentation hook published on NPM that can be used from within a Mocha test kicked off by CLI Istanbul usage:

- [typhonjs-istanbul-instrument-jspm](https://www.npmjs.com/package/typhonjs-istanbul-instrument-jspm)

And an all inclusive module including the JSPM / SystemJS hook in addition to transpiling (Babel), docs (ESDoc + plugins for JSPM), ESLint (2+), testing (Mocha / Istanbul), NPM publish / prepublish detection / script runner, coverage upload (Codecov):
- [typhonjs-npm-build-test](https://www.npmjs.com/package/typhonjs-npm-build-test)

I have updated [istanbul-jspm-coverage-example](https://github.com/typhonjs-demos-test/istanbul-jspm-coverage-example) giving a concise demo showing coverage of SystemJS loaded code. In particular see [TestJSPM.js](https://github.com/typhonjs-demos-test/istanbul-jspm-coverage-example/blob/master/test/src/TestJSPM.js)

And here is the final instrumentation hook for System.translate [instrumentIstanbulSystem.js](https://github.com/typhonjs-node-jspm/typhonjs-istanbul-instrument-jspm/blob/master/src/instrumentIstanbulSystem.js)

Tested on JSPM / SystemJS 0.16.x and 0.17.x.... Turns out I had to get a little clever as 0.16.x doesn't output source maps in System.translate (oi @guybedford took hours to figure that out!). Two Istanbul instrumenters are created; one for ES5 and one for ES6+ / ES Modules and instrumentation occurs before invoking the original System.translate function which has the benefit of not needing to use source maps. In the tests CJS and ESM code is covered. 

A caveat with CLI Istanbul usage and "remote" instrumentation is that the run-cover / cover command will not fully complete the report with the SystemJS covered code. So there is a particular NPM script available [mocha-istanbul-report.js](https://www.npmjs.com/package/typhonjs-npm-scripts-test-mocha) that will run the cover command then follow up with the CLI report command which properly picks up SystemJS instrumented source code. 

Up next... Get code coverage of headless browser tests of SystemJS using NightmareJS... Oi that is going to be a nightmare! 

@guybedford  feel free to add this to JSPM / SystemJS utility resources as it's handy...

**Comment by guybedford** [comment]
@typhonrt nice work! Perhaps we should compare notes - https://github.com/guybedford/jspm-test-demo.

**Comment by typhonrt** [comment]
@guybedford Thanks! Yeah, I'll take another look at your test repo next week on how it handles PhantomJS integration. If you were to continue to work in this direction separating the testing infrastructure into a separate installable dev dependency seems reasonable. 

The main problem that I'm going to have with CLI Istanbul / Mocha / Nightmare integration for covering JSPM / SystemJS browser use cases is that Electron under the hood is launched in a separate process via spawn thus IPC is going to be necessary internally between the render process of Electron then Electron to Nightmare runner back to the Istanbul / Mocha process. That may be difficult / error prone and will require significant effort / likely custom Instrumenter for Istanbul, so is not the first option.

I've already tested being able to inject custom JS and accessing / bootstrapping SystemJS running in Nightmare.

I'll probably first see if I can instrument / output an independent coverage json file from the Electron process then run report separately. Kind of similar to what the `test-phantom.sh` file in your repo does. As far as I can tell there has been no discussion in the Nightmare repo in issues or documentation regarding coverage examples or reports, so seemingly not many are doing this yet. Having SystemJS facilitate instrumentation / coverage via `System.translate` is a benefit in this regard. 

I'm interested in using Nightmare over PhantomJS as the high level API is simpler more or less and I'm already supporting Electron desktop deployment of JSPM / SystemJS web apps via [typhonjs-core-gulptasks](https://www.npmjs.com/package/typhonjs-core-gulptasks)

**Comment by guybedford** [comment]
I will aim to do some more polishing there later this month. The way the
approach there works is by piping the coverage report json to stdout
effectively just the UNIX style version of the independent json approach.

The other important thing handled there is the reverse mapping of source
maps to support all possible variations of the translate hook (eg the
approach there should give typescript coverage with the original sources).

**Comment by typhonrt** [comment]
I saw the remap-istanbul usage. At first there was a bit of head scratching since things aren't commented. I should mention that I'm using the v1.0 alpha version of Istanbul. It seems like [istanbul-lib-source-maps](https://github.com/istanbuljs/istanbul-lib-source-maps) would handle the storing of source maps and resolution against coverage files. The dev velocity is slow with Istanbul, but I like that they are separating it into modules. 

I think the most important thing is clearly separating your effort into a single installable component in the jspm->devDepedencies section. IMHO mixing a bespoke testing infrastructure in each repo that may use it is not too handy. It's also nice to clearly see the actual dependencies for the repo / module at hand. 

I'm just going through all of the TyphonJS repos now updating things with the initial build / testing setup recently finalized. With my approach the Node devDependencies section is minimal and mostly the same for all repos:
```
  "devDependencies": {
    "gulp": "^3.0.0",
    "jspm": "^0.16.0",
    "typhonjs-config-eslint": "^0.4.0",
    "typhonjs-core-gulptasks": "^0.6.0",
    "typhonjs-npm-build-test": "^0.1.0"
  },
```

So all testing resources are located external to the actual `jspm` section which is reserved for anything specific to the module / repo at hand w/ gulp & the gulp tasks being omitted for some NPM module only repos.

**Comment by typhonrt** [comment]
Just adding a note here for JSPM `17.x` usage w/ Babel 6 to explore. It seems like there is now a babel plugin [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul). 

I'll be swinging back around to exploring instrumenting JSPM 17.x tests soon especially hopefully getting things to work in the browser via [ava](https://www.npmjs.com/package/ava) / [nyc](https://www.npmjs.com/package/nyc) / [nightmare](https://www.npmjs.com/package/nightmare) and babel-plugin-istanbul.

**Comment by guybedford** [comment]
@typhonrt see also http://guybedford.com/systemjs-mocha-istanbul for a generic approach, although there's many ways of going about the same thing.

**Comment by typhonrt** [comment]
@guybedford Thanks for the blog post; glad you have put a little more time into testing / coverage! I'll take a look soon. I assume this works JSPM `17.x+` which is not mentioned in the post.  

I'd like to add an RSS feed to your blog so I don't miss these pertinent posts; couldn't find one.
